// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/service/usb.proto

package android.service.usb;

/** @hide */
// message UsbAccessoryFilterProto
public final class UsbAccessoryFilterProto {

    // optional string manufacturer = 1;
    public static final long MANUFACTURER = 0x0000010900000001L;

    // optional string model = 2;
    public static final long MODEL = 0x0000010900000002L;

    // optional string version = 3;
    public static final long VERSION = 0x0000010900000003L;

}

