// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/service/usb.proto

package android.service.usb;

/** @hide */
// message UsbDeviceManagerProto
public final class UsbDeviceManagerProto {

    // optional .android.service.usb.UsbHandlerProto handler = 1;
    public static final long HANDLER = 0x0000010b00000001L;

    // optional .android.service.usb.UsbDebuggingManagerProto debugging_manager = 2;
    public static final long DEBUGGING_MANAGER = 0x0000010b00000002L;

}

