// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/service/usb.proto

package android.service.usb;

/** @hide */
// message UsbDebuggingManagerProto
public final class UsbDebuggingManagerProto {

    // optional bool connected_to_adb = 1;
    public static final long CONNECTED_TO_ADB = 0x0000010800000001L;

    // optional string last_key_received = 2;
    public static final long LAST_KEY_RECEIVED = 0x0000010900000002L;

    // optional string user_keys = 3;
    public static final long USER_KEYS = 0x0000010900000003L;

    // optional string system_keys = 4;
    public static final long SYSTEM_KEYS = 0x0000010900000004L;

}

