// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/service/usb.proto

package android.service.usb;

/** @hide */
// message UsbEndPointProto
public final class UsbEndPointProto {

    // optional int32 endpoint_number = 1;
    public static final long ENDPOINT_NUMBER = 0x0000010500000001L;

    // optional .android.service.UsbEndPointDirection direction = 2;
    public static final long DIRECTION = 0x0000010e00000002L;

    // optional int32 address = 3;
    public static final long ADDRESS = 0x0000010500000003L;

    // optional .android.service.UsbEndPointType type = 4;
    public static final long TYPE = 0x0000010e00000004L;

    // optional uint32 attributes = 5;
    public static final long ATTRIBUTES = 0x0000010d00000005L;

    // optional int32 max_packet_size = 6;
    public static final long MAX_PACKET_SIZE = 0x0000010500000006L;

    // optional int32 interval = 7;
    public static final long INTERVAL = 0x0000010500000007L;

}

