// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/service/usb.proto

package android.service.usb;

/** @hide */
// message UsbIsHeadsetProto
public final class UsbIsHeadsetProto {

    // optional bool in = 1;
    public static final long IN = 0x0000010800000001L;

    // optional bool out = 2;
    public static final long OUT = 0x0000010800000002L;

}

