// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/service/usb.proto

package android.service.usb;

/** @hide */
// message UsbMidiDeviceProto
public final class UsbMidiDeviceProto {

    // optional int32 card = 1;
    public static final long CARD = 0x0000010500000001L;

    // optional int32 device = 2;
    public static final long DEVICE = 0x0000010500000002L;

    // optional string device_address = 3;
    public static final long DEVICE_ADDRESS = 0x0000010900000003L;

}

