// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/service/usb.proto

package android.service.usb;

/** @hide */
// message UsbPortStatusProto
public final class UsbPortStatusProto {

    // enum PowerRole
    public static final int POWER_ROLE_NONE = 0;
    public static final int POWER_ROLE_SOURCE = 1;
    public static final int POWER_ROLE_SINK = 2;

    // enum DataRole
    public static final int DATA_ROLE_NONE = 0;
    public static final int DATA_ROLE_HOST = 1;
    public static final int DATA_ROLE_DEVICE = 2;

    // optional bool connected = 1;
    public static final long CONNECTED = 0x0000010800000001L;

    // optional .android.service.usb.UsbPortProto.Mode current_mode = 2;
    public static final long CURRENT_MODE = 0x0000010e00000002L;

    // optional .android.service.usb.UsbPortStatusProto.PowerRole power_role = 3;
    public static final long POWER_ROLE = 0x0000010e00000003L;

    // optional .android.service.usb.UsbPortStatusProto.DataRole data_role = 4;
    public static final long DATA_ROLE = 0x0000010e00000004L;

    // repeated .android.service.usb.UsbPortStatusRoleCombinationProto role_combinations = 5;
    public static final long ROLE_COMBINATIONS = 0x0000020b00000005L;

}

