// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/service/usb.proto

package android.service.usb;

/** @hide */
// message UsbSettingsDevicePermissionProto
public final class UsbSettingsDevicePermissionProto {

    // optional string device_name = 1;
    public static final long DEVICE_NAME = 0x0000010900000001L;

    // repeated int32 uids = 2;
    public static final long UIDS = 0x0000020500000002L;

}

