// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/service/usb.proto

package android.service.usb;

/** @hide */
// message UsbServiceDumpProto
public final class UsbServiceDumpProto {

    // optional .android.service.usb.UsbDeviceManagerProto device_manager = 1;
    public static final long DEVICE_MANAGER = 0x0000010b00000001L;

    // optional .android.service.usb.UsbHostManagerProto host_manager = 2;
    public static final long HOST_MANAGER = 0x0000010b00000002L;

    // optional .android.service.usb.UsbPortManagerProto port_manager = 3;
    public static final long PORT_MANAGER = 0x0000010b00000003L;

    // optional .android.service.usb.UsbAlsaManagerProto alsa_manager = 4;
    public static final long ALSA_MANAGER = 0x0000010b00000004L;

    // optional .android.service.usb.UsbSettingsManagerProto settings_manager = 5;
    public static final long SETTINGS_MANAGER = 0x0000010b00000005L;

}

