// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/util/common.proto

package android.util;

/** @hide */
// message AggStats
public final class AggStats {

    // optional int64 min = 1;
    public static final long MIN = 0x0000010300000001L;

    // optional int64 average = 2;
    public static final long AVERAGE = 0x0000010300000002L;

    // optional int64 max = 3;
    public static final long MAX = 0x0000010300000003L;

}

