// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/util/log.proto

package android.util;

/** @hide */
// message BinaryLogEntry
public final class BinaryLogEntry {

    // message Elem
    public final class Elem {

        // enum Type
        public static final int EVENT_TYPE_LIST_STOP = 10;
        public static final int EVENT_TYPE_UNKNOWN = 63;
        public static final int EVENT_TYPE_INT = 0;
        public static final int EVENT_TYPE_LONG = 1;
        public static final int EVENT_TYPE_STRING = 2;
        public static final int EVENT_TYPE_LIST = 3;
        public static final int EVENT_TYPE_FLOAT = 4;

        // optional .android.util.BinaryLogEntry.Elem.Type type = 1;
        public static final long TYPE = 0x0000010e00000001L;

        // optional int32 val_int32 = 2;
        public static final long VAL_INT32 = 0x0000010500000002L;

        // optional int64 val_int64 = 3;
        public static final long VAL_INT64 = 0x0000010300000003L;

        // optional string val_string = 4;
        public static final long VAL_STRING = 0x0000010900000004L;

        // optional float val_float = 5;
        public static final long VAL_FLOAT = 0x0000010200000005L;

    }

    // optional uint64 sec = 1;
    public static final long SEC = 0x0000010400000001L;

    // optional uint64 nanosec = 2;
    public static final long NANOSEC = 0x0000010400000002L;

    // optional int32 uid = 3;
    public static final long UID = 0x0000010500000003L;

    // optional int32 pid = 4;
    public static final long PID = 0x0000010500000004L;

    // optional int32 tid = 5;
    public static final long TID = 0x0000010500000005L;

    // optional uint32 tag_index = 6;
    public static final long TAG_INDEX = 0x0000010d00000006L;

    // repeated .android.util.BinaryLogEntry.Elem elems = 7;
    public static final long ELEMS = 0x0000020b00000007L;

}

