// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/util/log.proto

package android.util;

/** @hide */
// message LogProto
public final class LogProto {

    // repeated .android.util.TextLogEntry text_logs = 1;
    public static final long TEXT_LOGS = 0x0000020b00000001L;

    // repeated .android.util.BinaryLogEntry binary_logs = 2;
    public static final long BINARY_LOGS = 0x0000020b00000002L;

}

