// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/service/diskstats.proto

package android.service.diskstats;

/** @hide */
// message DiskStatsCachedValuesProto
public final class DiskStatsCachedValuesProto {

    // optional int64 agg_apps_size_kb = 1;
    public static final long AGG_APPS_SIZE_KB = 0x0000010300000001L;

    // optional int64 agg_apps_cache_size_kb = 2;
    public static final long AGG_APPS_CACHE_SIZE_KB = 0x0000010300000002L;

    // optional int64 photos_size_kb = 3;
    public static final long PHOTOS_SIZE_KB = 0x0000010300000003L;

    // optional int64 videos_size_kb = 4;
    public static final long VIDEOS_SIZE_KB = 0x0000010300000004L;

    // optional int64 audio_size_kb = 5;
    public static final long AUDIO_SIZE_KB = 0x0000010300000005L;

    // optional int64 downloads_size_kb = 6;
    public static final long DOWNLOADS_SIZE_KB = 0x0000010300000006L;

    // optional int64 system_size_kb = 7;
    public static final long SYSTEM_SIZE_KB = 0x0000010300000007L;

    // optional int64 other_size_kb = 8;
    public static final long OTHER_SIZE_KB = 0x0000010300000008L;

    // repeated .android.service.diskstats.DiskStatsAppSizesProto app_sizes = 9;
    public static final long APP_SIZES = 0x0000020b00000009L;

    // optional int64 agg_apps_data_size_kb = 10;
    public static final long AGG_APPS_DATA_SIZE_KB = 0x000001030000000aL;

}

