// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/os/batterystats.proto

package android.os;

/** @hide */
// message ControllerActivityProto
public final class ControllerActivityProto {

    // message TxLevel
    public final class TxLevel {

        // optional int32 level = 1;
        public static final long LEVEL = 0x0000010500000001L;

        // optional int64 duration_ms = 2;
        public static final long DURATION_MS = 0x0000010300000002L;

    }

    // optional int64 idle_duration_ms = 1;
    public static final long IDLE_DURATION_MS = 0x0000010300000001L;

    // optional int64 rx_duration_ms = 2;
    public static final long RX_DURATION_MS = 0x0000010300000002L;

    // optional int64 power_mah = 3;
    public static final long POWER_MAH = 0x0000010300000003L;

    // repeated .android.os.ControllerActivityProto.TxLevel tx = 4;
    public static final long TX = 0x0000020b00000004L;

}

