// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/os/incident.proto

package android.os;

/** @hide */
// message IncidentProto
public final class IncidentProto {

    // repeated .android.os.IncidentHeaderProto header = 1;
    public static final long HEADER = 0x0000020b00000001L;

    // optional .android.os.IncidentMetadata metadata = 2;
    public static final long METADATA = 0x0000010b00000002L;

    // optional .android.os.SystemPropertiesProto system_properties = 1000;
    public static final long SYSTEM_PROPERTIES = 0x0000010b000003e8L;

    // optional .android.util.EventLogTagMapProto event_log_tag_map = 1100;
    public static final long EVENT_LOG_TAG_MAP = 0x0000010b0000044cL;

    // optional .android.util.LogProto main_logs = 1101;
    public static final long MAIN_LOGS = 0x0000010b0000044dL;

    // optional .android.util.LogProto radio_logs = 1102;
    public static final long RADIO_LOGS = 0x0000010b0000044eL;

    // optional .android.util.LogProto events_logs = 1103;
    public static final long EVENTS_LOGS = 0x0000010b0000044fL;

    // optional .android.util.LogProto system_logs = 1104;
    public static final long SYSTEM_LOGS = 0x0000010b00000450L;

    // optional .android.util.LogProto crash_logs = 1105;
    public static final long CRASH_LOGS = 0x0000010b00000451L;

    // optional .android.util.LogProto stats_logs = 1106;
    public static final long STATS_LOGS = 0x0000010b00000452L;

    // optional .android.util.LogProto security_logs = 1107;
    public static final long SECURITY_LOGS = 0x0000010b00000453L;

    // optional .android.util.LogProto kernel_logs = 1108;
    public static final long KERNEL_LOGS = 0x0000010b00000454L;

    // optional .android.os.BackTraceProto native_traces = 1200;
    public static final long NATIVE_TRACES = 0x0000010b000004b0L;

    // optional .android.os.BackTraceProto hal_traces = 1201;
    public static final long HAL_TRACES = 0x0000010b000004b1L;

    // optional .android.os.BackTraceProto java_traces = 1202;
    public static final long JAVA_TRACES = 0x0000010b000004b2L;

    // optional .android.os.ProcrankProto procrank = 2000;
    public static final long PROCRANK = 0x0000010b000007d0L;

    // optional .android.os.PageTypeInfoProto page_type_info = 2001;
    public static final long PAGE_TYPE_INFO = 0x0000010b000007d1L;

    // optional .android.os.KernelWakeSourcesProto kernel_wake_sources = 2002;
    public static final long KERNEL_WAKE_SOURCES = 0x0000010b000007d2L;

    // optional .android.os.CpuInfoProto cpu_info = 2003;
    public static final long CPU_INFO = 0x0000010b000007d3L;

    // optional .android.os.CpuFreqProto cpu_freq = 2004;
    public static final long CPU_FREQ = 0x0000010b000007d4L;

    // optional .android.os.PsProto processes_and_threads = 2005;
    public static final long PROCESSES_AND_THREADS = 0x0000010b000007d5L;

    // optional .android.os.BatteryTypeProto battery_type = 2006;
    public static final long BATTERY_TYPE = 0x0000010b000007d6L;

    // optional .android.os.GZippedFileProto last_kmsg = 2007;
    public static final long LAST_KMSG = 0x0000010b000007d7L;

    // optional .com.android.server.fingerprint.FingerprintServiceDumpProto fingerprint = 3000;
    public static final long FINGERPRINT = 0x0000010b00000bb8L;

    // optional .android.service.NetworkStatsServiceDumpProto netstats = 3001;
    public static final long NETSTATS = 0x0000010b00000bb9L;

    // optional .android.providers.settings.SettingsServiceDumpProto settings = 3002;
    public static final long SETTINGS = 0x0000010b00000bbaL;

    // optional .android.service.appwidget.AppWidgetServiceDumpProto appwidget = 3003;
    public static final long APPWIDGET = 0x0000010b00000bbbL;

    // optional .android.service.notification.NotificationServiceDumpProto notification = 3004;
    public static final long NOTIFICATION = 0x0000010b00000bbcL;

    // optional .android.service.batterystats.BatteryStatsServiceDumpProto batterystats = 3005;
    public static final long BATTERYSTATS = 0x0000010b00000bbdL;

    // optional .android.service.battery.BatteryServiceDumpProto battery = 3006;
    public static final long BATTERY = 0x0000010b00000bbeL;

    // optional .android.service.diskstats.DiskStatsServiceDumpProto diskstats = 3007;
    public static final long DISKSTATS = 0x0000010b00000bbfL;

    // optional .android.service.pm.PackageServiceDumpProto package = 3008;
    public static final long PACKAGE = 0x0000010b00000bc0L;

    // optional .com.android.server.power.PowerManagerServiceDumpProto power = 3009;
    public static final long POWER = 0x0000010b00000bc1L;

    // optional .android.service.print.PrintServiceDumpProto print = 3010;
    public static final long PRINT = 0x0000010b00000bc2L;

    // optional .android.service.procstats.ProcessStatsServiceDumpProto procstats = 3011;
    public static final long PROCSTATS = 0x0000010b00000bc3L;

    // optional .com.android.server.am.ActivityManagerServiceDumpActivitiesProto activities = 3012;
    public static final long ACTIVITIES = 0x0000010b00000bc4L;

    // optional .com.android.server.am.ActivityManagerServiceDumpBroadcastsProto broadcasts = 3013;
    public static final long BROADCASTS = 0x0000010b00000bc5L;

    // optional .com.android.server.am.ActivityManagerServiceDumpServicesProto amservices = 3014;
    public static final long AMSERVICES = 0x0000010b00000bc6L;

    // optional .com.android.server.am.ActivityManagerServiceDumpProcessesProto amprocesses = 3015;
    public static final long AMPROCESSES = 0x0000010b00000bc7L;

    // optional .com.android.server.AlarmManagerServiceDumpProto alarm = 3016;
    public static final long ALARM = 0x0000010b00000bc8L;

    // optional .com.android.server.wm.WindowManagerServiceDumpProto window = 3017;
    public static final long WINDOW = 0x0000010b00000bc9L;

    // optional .com.android.server.am.MemInfoDumpProto meminfo = 3018;
    public static final long MEMINFO = 0x0000010b00000bcaL;

    // optional .android.service.GraphicsStatsServiceDumpProto graphicsstats = 3019;
    public static final long GRAPHICSSTATS = 0x0000010b00000bcbL;

    // optional .com.android.server.job.JobSchedulerServiceDumpProto jobscheduler = 3020;
    public static final long JOBSCHEDULER = 0x0000010b00000bccL;

    // optional .android.service.usb.UsbServiceDumpProto usb = 3021;
    public static final long USB = 0x0000010b00000bcdL;

    // optional .android.service.batterystats.BatteryStatsServiceDumpHistoryProto battery_history = 3022;
    public static final long BATTERY_HISTORY = 0x0000010b00000bceL;

}

