// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/os/batterystats.proto

package android.os;

/** @hide */
// message SystemProto
public final class SystemProto {

    // message Battery
    public final class Battery {

        // optional int64 start_clock_time_ms = 1;
        public static final long START_CLOCK_TIME_MS = 0x0000010300000001L;

        // optional int64 start_count = 2;
        public static final long START_COUNT = 0x0000010300000002L;

        // optional int64 total_realtime_ms = 3;
        public static final long TOTAL_REALTIME_MS = 0x0000010300000003L;

        // optional int64 total_uptime_ms = 4;
        public static final long TOTAL_UPTIME_MS = 0x0000010300000004L;

        // optional int64 battery_realtime_ms = 5;
        public static final long BATTERY_REALTIME_MS = 0x0000010300000005L;

        // optional int64 battery_uptime_ms = 6;
        public static final long BATTERY_UPTIME_MS = 0x0000010300000006L;

        // optional int64 screen_off_realtime_ms = 7;
        public static final long SCREEN_OFF_REALTIME_MS = 0x0000010300000007L;

        // optional int64 screen_off_uptime_ms = 8;
        public static final long SCREEN_OFF_UPTIME_MS = 0x0000010300000008L;

        // optional int64 screen_doze_duration_ms = 9;
        public static final long SCREEN_DOZE_DURATION_MS = 0x0000010300000009L;

        // optional int64 estimated_battery_capacity_mah = 10;
        public static final long ESTIMATED_BATTERY_CAPACITY_MAH = 0x000001030000000aL;

        // optional int64 min_learned_battery_capacity_uah = 11;
        public static final long MIN_LEARNED_BATTERY_CAPACITY_UAH = 0x000001030000000bL;

        // optional int64 max_learned_battery_capacity_uah = 12;
        public static final long MAX_LEARNED_BATTERY_CAPACITY_UAH = 0x000001030000000cL;

    }

    // message BatteryDischarge
    public final class BatteryDischarge {

        // optional int32 lower_bound_since_charge = 1;
        public static final long LOWER_BOUND_SINCE_CHARGE = 0x0000010500000001L;

        // optional int32 upper_bound_since_charge = 2;
        public static final long UPPER_BOUND_SINCE_CHARGE = 0x0000010500000002L;

        // optional int32 screen_on_since_charge = 3;
        public static final long SCREEN_ON_SINCE_CHARGE = 0x0000010500000003L;

        // optional int32 screen_off_since_charge = 4;
        public static final long SCREEN_OFF_SINCE_CHARGE = 0x0000010500000004L;

        // optional int32 screen_doze_since_charge = 5;
        public static final long SCREEN_DOZE_SINCE_CHARGE = 0x0000010500000005L;

        // optional int64 total_mah = 6;
        public static final long TOTAL_MAH = 0x0000010300000006L;

        // optional int64 total_mah_screen_off = 7;
        public static final long TOTAL_MAH_SCREEN_OFF = 0x0000010300000007L;

        // optional int64 total_mah_screen_doze = 8;
        public static final long TOTAL_MAH_SCREEN_DOZE = 0x0000010300000008L;

        // optional int64 total_mah_light_doze = 9;
        public static final long TOTAL_MAH_LIGHT_DOZE = 0x0000010300000009L;

        // optional int64 total_mah_deep_doze = 10;
        public static final long TOTAL_MAH_DEEP_DOZE = 0x000001030000000aL;

    }

    // message BatteryLevelStep
    public final class BatteryLevelStep {

        // enum DisplayState
        public static final int DS_MIXED = 0;
        public static final int DS_ON = 1;
        public static final int DS_OFF = 2;
        public static final int DS_DOZE = 3;
        public static final int DS_DOZE_SUSPEND = 4;
        public static final int DS_ERROR = 5;

        // enum PowerSaveMode
        public static final int PSM_MIXED = 0;
        public static final int PSM_ON = 1;
        public static final int PSM_OFF = 2;

        // enum IdleMode
        public static final int IM_MIXED = 0;
        public static final int IM_ON = 2;
        public static final int IM_OFF = 3;

        // optional int64 duration_ms = 1;
        public static final long DURATION_MS = 0x0000010300000001L;

        // optional int32 level = 2;
        public static final long LEVEL = 0x0000010500000002L;

        // optional .android.os.SystemProto.BatteryLevelStep.DisplayState display_state = 3;
        public static final long DISPLAY_STATE = 0x0000010e00000003L;

        // optional .android.os.SystemProto.BatteryLevelStep.PowerSaveMode power_save_mode = 4;
        public static final long POWER_SAVE_MODE = 0x0000010e00000004L;

        // optional .android.os.SystemProto.BatteryLevelStep.IdleMode idle_mode = 5;
        public static final long IDLE_MODE = 0x0000010e00000005L;

    }

    // message DataConnection
    public final class DataConnection {

        // optional .android.telephony.NetworkTypeEnum name = 1;
        public static final long NAME = 0x0000010e00000001L;

        // optional bool is_none = 2;
        public static final long IS_NONE = 0x0000010800000002L;

        // optional .android.os.TimerProto total = 3;
        public static final long TOTAL = 0x0000010b00000003L;

    }

    // message GlobalNetwork
    public final class GlobalNetwork {

        // optional int64 mobile_bytes_rx = 1;
        public static final long MOBILE_BYTES_RX = 0x0000010300000001L;

        // optional int64 mobile_bytes_tx = 2;
        public static final long MOBILE_BYTES_TX = 0x0000010300000002L;

        // optional int64 wifi_bytes_rx = 3;
        public static final long WIFI_BYTES_RX = 0x0000010300000003L;

        // optional int64 wifi_bytes_tx = 4;
        public static final long WIFI_BYTES_TX = 0x0000010300000004L;

        // optional int64 mobile_packets_rx = 5;
        public static final long MOBILE_PACKETS_RX = 0x0000010300000005L;

        // optional int64 mobile_packets_tx = 6;
        public static final long MOBILE_PACKETS_TX = 0x0000010300000006L;

        // optional int64 wifi_packets_rx = 7;
        public static final long WIFI_PACKETS_RX = 0x0000010300000007L;

        // optional int64 wifi_packets_tx = 8;
        public static final long WIFI_PACKETS_TX = 0x0000010300000008L;

        // optional int64 bt_bytes_rx = 9;
        public static final long BT_BYTES_RX = 0x0000010300000009L;

        // optional int64 bt_bytes_tx = 10;
        public static final long BT_BYTES_TX = 0x000001030000000aL;

    }

    // message GlobalWifi
    public final class GlobalWifi {

        // optional int64 on_duration_ms = 1;
        public static final long ON_DURATION_MS = 0x0000010300000001L;

        // optional int64 running_duration_ms = 2;
        public static final long RUNNING_DURATION_MS = 0x0000010300000002L;

    }

    // message KernelWakelock
    public final class KernelWakelock {

        // optional string name = 1;
        public static final long NAME = 0x0000010900000001L;

        // optional .android.os.TimerProto total = 2;
        public static final long TOTAL = 0x0000010b00000002L;

    }

    // message Misc
    public final class Misc {

        // optional int64 screen_on_duration_ms = 1;
        public static final long SCREEN_ON_DURATION_MS = 0x0000010300000001L;

        // optional int64 phone_on_duration_ms = 2;
        public static final long PHONE_ON_DURATION_MS = 0x0000010300000002L;

        // optional int64 full_wakelock_total_duration_ms = 3;
        public static final long FULL_WAKELOCK_TOTAL_DURATION_MS = 0x0000010300000003L;

        // optional int64 partial_wakelock_total_duration_ms = 4;
        public static final long PARTIAL_WAKELOCK_TOTAL_DURATION_MS = 0x0000010300000004L;

        // optional int64 mobile_radio_active_duration_ms = 5;
        public static final long MOBILE_RADIO_ACTIVE_DURATION_MS = 0x0000010300000005L;

        // optional int64 mobile_radio_active_adjusted_time_ms = 6;
        public static final long MOBILE_RADIO_ACTIVE_ADJUSTED_TIME_MS = 0x0000010300000006L;

        // optional int32 mobile_radio_active_count = 7;
        public static final long MOBILE_RADIO_ACTIVE_COUNT = 0x0000010500000007L;

        // optional int32 mobile_radio_active_unknown_duration_ms = 8;
        public static final long MOBILE_RADIO_ACTIVE_UNKNOWN_DURATION_MS = 0x0000010500000008L;

        // optional int64 interactive_duration_ms = 9;
        public static final long INTERACTIVE_DURATION_MS = 0x0000010300000009L;

        // optional int64 battery_saver_mode_enabled_duration_ms = 10;
        public static final long BATTERY_SAVER_MODE_ENABLED_DURATION_MS = 0x000001030000000aL;

        // optional int32 num_connectivity_changes = 11;
        public static final long NUM_CONNECTIVITY_CHANGES = 0x000001050000000bL;

        // optional int64 deep_doze_enabled_duration_ms = 12;
        public static final long DEEP_DOZE_ENABLED_DURATION_MS = 0x000001030000000cL;

        // optional int32 deep_doze_count = 13;
        public static final long DEEP_DOZE_COUNT = 0x000001050000000dL;

        // optional int64 deep_doze_idling_duration_ms = 14;
        public static final long DEEP_DOZE_IDLING_DURATION_MS = 0x000001030000000eL;

        // optional int32 deep_doze_idling_count = 15;
        public static final long DEEP_DOZE_IDLING_COUNT = 0x000001050000000fL;

        // optional int64 longest_deep_doze_duration_ms = 16;
        public static final long LONGEST_DEEP_DOZE_DURATION_MS = 0x0000010300000010L;

        // optional int64 light_doze_enabled_duration_ms = 17;
        public static final long LIGHT_DOZE_ENABLED_DURATION_MS = 0x0000010300000011L;

        // optional int32 light_doze_count = 18;
        public static final long LIGHT_DOZE_COUNT = 0x0000010500000012L;

        // optional int64 light_doze_idling_duration_ms = 19;
        public static final long LIGHT_DOZE_IDLING_DURATION_MS = 0x0000010300000013L;

        // optional int32 light_doze_idling_count = 20;
        public static final long LIGHT_DOZE_IDLING_COUNT = 0x0000010500000014L;

        // optional int64 longest_light_doze_duration_ms = 21;
        public static final long LONGEST_LIGHT_DOZE_DURATION_MS = 0x0000010300000015L;

    }

    // message PhoneSignalStrength
    public final class PhoneSignalStrength {

        // optional .android.telephony.SignalStrengthEnum name = 1;
        public static final long NAME = 0x0000010e00000001L;

        // optional .android.os.TimerProto total = 2;
        public static final long TOTAL = 0x0000010b00000002L;

    }

    // message PowerUseItem
    public final class PowerUseItem {

        // enum Sipper
        public static final int UNKNOWN_SIPPER = 0;
        public static final int IDLE = 1;
        public static final int CELL = 2;
        public static final int PHONE = 3;
        public static final int WIFI = 4;
        public static final int BLUETOOTH = 5;
        public static final int FLASHLIGHT = 6;
        public static final int SCREEN = 7;
        public static final int USER = 8;
        public static final int UNACCOUNTED = 9;
        public static final int OVERCOUNTED = 10;
        public static final int CAMERA = 11;
        public static final int MEMORY = 12;
        public static final int AMBIENT_DISPLAY = 13;

        // optional .android.os.SystemProto.PowerUseItem.Sipper name = 1;
        public static final long NAME = 0x0000010e00000001L;

        // optional int32 uid = 2;
        public static final long UID = 0x0000010500000002L;

        // optional double computed_power_mah = 3;
        public static final long COMPUTED_POWER_MAH = 0x0000010100000003L;

        // optional bool should_hide = 4;
        public static final long SHOULD_HIDE = 0x0000010800000004L;

        // optional double screen_power_mah = 5;
        public static final long SCREEN_POWER_MAH = 0x0000010100000005L;

        // optional double proportional_smear_mah = 6;
        public static final long PROPORTIONAL_SMEAR_MAH = 0x0000010100000006L;

    }

    // message PowerUseSummary
    public final class PowerUseSummary {

        // optional double battery_capacity_mah = 1;
        public static final long BATTERY_CAPACITY_MAH = 0x0000010100000001L;

        // optional double computed_power_mah = 2;
        public static final long COMPUTED_POWER_MAH = 0x0000010100000002L;

        // optional double min_drained_power_mah = 3;
        public static final long MIN_DRAINED_POWER_MAH = 0x0000010100000003L;

        // optional double max_drained_power_mah = 4;
        public static final long MAX_DRAINED_POWER_MAH = 0x0000010100000004L;

    }

    // message ResourcePowerManager
    public final class ResourcePowerManager {

        // optional string name = 1;
        public static final long NAME = 0x0000010900000001L;

        // optional .android.os.TimerProto total = 2;
        public static final long TOTAL = 0x0000010b00000002L;

        // optional .android.os.TimerProto screen_off = 3;
        public static final long SCREEN_OFF = 0x0000010b00000003L;

    }

    // message ScreenBrightness
    public final class ScreenBrightness {

        // enum Name
        public static final int DARK = 0;
        public static final int DIM = 1;
        public static final int MEDIUM = 2;
        public static final int LIGHT = 3;
        public static final int BRIGHT = 4;

        // optional .android.os.SystemProto.ScreenBrightness.Name name = 1;
        public static final long NAME = 0x0000010e00000001L;

        // optional .android.os.TimerProto total = 2;
        public static final long TOTAL = 0x0000010b00000002L;

    }

    // message WakeupReason
    public final class WakeupReason {

        // optional string name = 1;
        public static final long NAME = 0x0000010900000001L;

        // optional .android.os.TimerProto total = 2;
        public static final long TOTAL = 0x0000010b00000002L;

    }

    // message WifiMulticastWakelockTotal
    public final class WifiMulticastWakelockTotal {

        // optional int64 duration_ms = 1;
        public static final long DURATION_MS = 0x0000010300000001L;

        // optional int32 count = 2;
        public static final long COUNT = 0x0000010500000002L;

    }

    // message WifiSignalStrength
    public final class WifiSignalStrength {

        // enum Name
        public static final int NONE = 0;
        public static final int POOR = 1;
        public static final int MODERATE = 2;
        public static final int GOOD = 3;
        public static final int GREAT = 4;

        // optional .android.os.SystemProto.WifiSignalStrength.Name name = 1;
        public static final long NAME = 0x0000010e00000001L;

        // optional .android.os.TimerProto total = 2;
        public static final long TOTAL = 0x0000010b00000002L;

    }

    // message WifiState
    public final class WifiState {

        // enum Name
        public static final int OFF = 0;
        public static final int OFF_SCANNING = 1;
        public static final int ON_NO_NETWORKS = 2;
        public static final int ON_DISCONNECTED = 3;
        public static final int ON_CONNECTED_STA = 4;
        public static final int ON_CONNECTED_P2P = 5;
        public static final int ON_CONNECTED_STA_P2P = 6;
        public static final int SOFT_AP = 7;

        // optional .android.os.SystemProto.WifiState.Name name = 1;
        public static final long NAME = 0x0000010e00000001L;

        // optional .android.os.TimerProto total = 2;
        public static final long TOTAL = 0x0000010b00000002L;

    }

    // message WifiSupplicantState
    public final class WifiSupplicantState {

        // enum Name
        public static final int INVALID = 0;
        public static final int DISCONNECTED = 1;
        public static final int INTERFACE_DISABLED = 2;
        public static final int INACTIVE = 3;
        public static final int SCANNING = 4;
        public static final int AUTHENTICATING = 5;
        public static final int ASSOCIATING = 6;
        public static final int ASSOCIATED = 7;
        public static final int FOUR_WAY_HANDSHAKE = 8;
        public static final int GROUP_HANDSHAKE = 9;
        public static final int COMPLETED = 10;
        public static final int DORMANT = 11;
        public static final int UNINITIALIZED = 12;

        // optional .android.os.SystemProto.WifiSupplicantState.Name name = 1;
        public static final long NAME = 0x0000010e00000001L;

        // optional .android.os.TimerProto total = 2;
        public static final long TOTAL = 0x0000010b00000002L;

    }

    // optional .android.os.SystemProto.Battery battery = 1;
    public static final long BATTERY = 0x0000010b00000001L;

    // optional .android.os.SystemProto.BatteryDischarge battery_discharge = 2;
    public static final long BATTERY_DISCHARGE = 0x0000010b00000002L;

    // optional int64 charge_time_remaining_ms = 3;
    public static final long CHARGE_TIME_REMAINING_MS = 0x0000010300000003L;

    // optional int64 discharge_time_remaining_ms = 4;
    public static final long DISCHARGE_TIME_REMAINING_MS = 0x0000010300000004L;

    // repeated .android.os.SystemProto.BatteryLevelStep charge_step = 5;
    public static final long CHARGE_STEP = 0x0000020b00000005L;

    // repeated .android.os.SystemProto.BatteryLevelStep discharge_step = 6;
    public static final long DISCHARGE_STEP = 0x0000020b00000006L;

    // repeated int64 cpu_frequency = 7;
    public static final long CPU_FREQUENCY = 0x0000020300000007L;

    // repeated .android.os.SystemProto.DataConnection data_connection = 8;
    public static final long DATA_CONNECTION = 0x0000020b00000008L;

    // optional .android.os.ControllerActivityProto global_bluetooth_controller = 9;
    public static final long GLOBAL_BLUETOOTH_CONTROLLER = 0x0000010b00000009L;

    // optional .android.os.ControllerActivityProto global_modem_controller = 10;
    public static final long GLOBAL_MODEM_CONTROLLER = 0x0000010b0000000aL;

    // optional .android.os.ControllerActivityProto global_wifi_controller = 11;
    public static final long GLOBAL_WIFI_CONTROLLER = 0x0000010b0000000bL;

    // optional .android.os.SystemProto.GlobalNetwork global_network = 12;
    public static final long GLOBAL_NETWORK = 0x0000010b0000000cL;

    // optional .android.os.SystemProto.GlobalWifi global_wifi = 13;
    public static final long GLOBAL_WIFI = 0x0000010b0000000dL;

    // repeated .android.os.SystemProto.KernelWakelock kernel_wakelock = 14;
    public static final long KERNEL_WAKELOCK = 0x0000020b0000000eL;

    // optional .android.os.SystemProto.Misc misc = 15;
    public static final long MISC = 0x0000010b0000000fL;

    // repeated .android.os.SystemProto.PhoneSignalStrength phone_signal_strength = 16;
    public static final long PHONE_SIGNAL_STRENGTH = 0x0000020b00000010L;

    // repeated .android.os.SystemProto.PowerUseItem power_use_item = 17;
    public static final long POWER_USE_ITEM = 0x0000020b00000011L;

    // optional .android.os.SystemProto.PowerUseSummary power_use_summary = 18;
    public static final long POWER_USE_SUMMARY = 0x0000010b00000012L;

    // repeated .android.os.SystemProto.ResourcePowerManager resource_power_manager = 19;
    public static final long RESOURCE_POWER_MANAGER = 0x0000020b00000013L;

    // repeated .android.os.SystemProto.ScreenBrightness screen_brightness = 20;
    public static final long SCREEN_BRIGHTNESS = 0x0000020b00000014L;

    // optional .android.os.TimerProto signal_scanning = 21;
    public static final long SIGNAL_SCANNING = 0x0000010b00000015L;

    // repeated .android.os.SystemProto.WakeupReason wakeup_reason = 22;
    public static final long WAKEUP_REASON = 0x0000020b00000016L;

    // optional .android.os.SystemProto.WifiMulticastWakelockTotal wifi_multicast_wakelock_total = 23;
    public static final long WIFI_MULTICAST_WAKELOCK_TOTAL = 0x0000010b00000017L;

    // repeated .android.os.SystemProto.WifiSignalStrength wifi_signal_strength = 24;
    public static final long WIFI_SIGNAL_STRENGTH = 0x0000020b00000018L;

    // repeated .android.os.SystemProto.WifiState wifi_state = 25;
    public static final long WIFI_STATE = 0x0000020b00000019L;

    // repeated .android.os.SystemProto.WifiSupplicantState wifi_supplicant_state = 26;
    public static final long WIFI_SUPPLICANT_STATE = 0x0000020b0000001aL;

}

