// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/service/package.proto

package android.service.pm;

/** @hide */
// message PackageServiceDumpProto
public final class PackageServiceDumpProto {

    // message PackageShortProto
    public final class PackageShortProto {

        // optional string name = 1;
        public static final long NAME = 0x0000010900000001L;

        // optional int32 uid = 2;
        public static final long UID = 0x0000010500000002L;

    }

    // message SharedLibraryProto
    public final class SharedLibraryProto {

        // optional string name = 1;
        public static final long NAME = 0x0000010900000001L;

        // optional bool is_jar = 2;
        public static final long IS_JAR = 0x0000010800000002L;

        // optional string path = 3;
        public static final long PATH = 0x0000010900000003L;

        // optional string apk = 4;
        public static final long APK = 0x0000010900000004L;

    }

    // message SharedUserProto
    public final class SharedUserProto {

        // optional int32 user_id = 1;
        public static final long USER_ID = 0x0000010500000001L;

        // optional string name = 2;
        public static final long NAME = 0x0000010900000002L;

    }

    // optional .android.service.pm.PackageServiceDumpProto.PackageShortProto required_verifier_package = 1;
    public static final long REQUIRED_VERIFIER_PACKAGE = 0x0000010b00000001L;

    // optional .android.service.pm.PackageServiceDumpProto.PackageShortProto verifier_package = 2;
    public static final long VERIFIER_PACKAGE = 0x0000010b00000002L;

    // repeated .android.service.pm.PackageServiceDumpProto.SharedLibraryProto shared_libraries = 3;
    public static final long SHARED_LIBRARIES = 0x0000020b00000003L;

    // repeated .android.content.pm.FeatureInfoProto features = 4;
    public static final long FEATURES = 0x0000020b00000004L;

    // repeated .android.service.pm.PackageProto packages = 5;
    public static final long PACKAGES = 0x0000020b00000005L;

    // repeated .android.service.pm.PackageServiceDumpProto.SharedUserProto shared_users = 6;
    public static final long SHARED_USERS = 0x0000020b00000006L;

    // repeated string messages = 7;
    public static final long MESSAGES = 0x0000020900000007L;

}

