// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/internal/locallog.proto

package com.android.internal.util;

/** @hide */
// message LocalLogProto
public final class LocalLogProto {

    // repeated string lines = 1;
    public static final long LINES = 0x0000020900000001L;

}

