// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/server/intentresolver.proto

package com.android.server;

/** @hide */
// message IntentResolverProto
public final class IntentResolverProto {

    // message ArrayMapEntry
    public final class ArrayMapEntry {

        // optional string key = 1;
        public static final long KEY = 0x0000010900000001L;

        // repeated string values = 2;
        public static final long VALUES = 0x0000020900000002L;

    }

    // repeated .com.android.server.IntentResolverProto.ArrayMapEntry full_mime_types = 1;
    public static final long FULL_MIME_TYPES = 0x0000020b00000001L;

    // repeated .com.android.server.IntentResolverProto.ArrayMapEntry base_mime_types = 2;
    public static final long BASE_MIME_TYPES = 0x0000020b00000002L;

    // repeated .com.android.server.IntentResolverProto.ArrayMapEntry wild_mime_types = 3;
    public static final long WILD_MIME_TYPES = 0x0000020b00000003L;

    // repeated .com.android.server.IntentResolverProto.ArrayMapEntry schemes = 4;
    public static final long SCHEMES = 0x0000020b00000004L;

    // repeated .com.android.server.IntentResolverProto.ArrayMapEntry non_data_actions = 5;
    public static final long NON_DATA_ACTIONS = 0x0000020b00000005L;

    // repeated .com.android.server.IntentResolverProto.ArrayMapEntry mime_typed_actions = 6;
    public static final long MIME_TYPED_ACTIONS = 0x0000020b00000006L;

}

