// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/service/enums.proto

package android.service;

/** @hide */
public final class ServiceProtoEnums {

    // enum UsbEndPointType
    public static final int USB_ENDPOINT_TYPE_XFER_CONTROL = 0;
    public static final int USB_ENDPOINT_TYPE_XFER_ISOC = 1;
    public static final int USB_ENDPOINT_TYPE_XFER_BULK = 2;
    public static final int USB_ENDPOINT_TYPE_XFER_INT = 3;

    // enum UsbEndPointDirection
    public static final int USB_ENDPOINT_DIR_OUT = 0;
    public static final int USB_ENDPOINT_DIR_IN = 128;

    // enum UsbConnectionRecordMode
    public static final int USB_CONNECTION_RECORD_MODE_CONNECT = 0;
    public static final int USB_CONNECTION_RECORD_MODE_CONNECT_BADPARSE = 1;
    public static final int USB_CONNECTION_RECORD_MODE_CONNECT_BADDEVICE = 2;
    public static final int USB_CONNECTION_RECORD_MODE_DISCONNECT = -1;

}
