// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/view/surfacecontrol.proto

package android.view;

/** @hide */
// message SurfaceControlProto
public final class SurfaceControlProto {

    // optional int32 hash_code = 1;
    public static final long HASH_CODE = 0x0000010500000001L;

    // optional string name = 2;
    public static final long NAME = 0x0000010900000002L;

}

