// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/service/procstats.proto

package android.service.procstats;

/** @hide */
// message ProcessStatsServiceDumpProto
public final class ProcessStatsServiceDumpProto {

    // optional .android.service.procstats.ProcessStatsSectionProto procstats_now = 1;
    public static final long PROCSTATS_NOW = 0x0000010b00000001L;

    // optional .android.service.procstats.ProcessStatsSectionProto procstats_over_3hrs = 2;
    public static final long PROCSTATS_OVER_3HRS = 0x0000010b00000002L;

    // optional .android.service.procstats.ProcessStatsSectionProto procstats_over_24hrs = 3;
    public static final long PROCSTATS_OVER_24HRS = 0x0000010b00000003L;

}

