// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/service/procstats.proto

package android.service.procstats;

/** @hide */
// message ProcessStatsProto
public final class ProcessStatsProto {

    // message Kill
    public final class Kill {

        // optional int32 cpu = 1;
        public static final long CPU = 0x0000010500000001L;

        // optional int32 cached = 2;
        public static final long CACHED = 0x0000010500000002L;

        // optional .android.util.AggStats cached_pss = 3;
        public static final long CACHED_PSS = 0x0000010b00000003L;

    }

    // message State
    public final class State {

        // enum ScreenState
        public static final int SCREEN_UNKNOWN = 0;
        public static final int OFF = 1;
        public static final int ON = 2;

        // enum MemoryState
        public static final int MEMORY_UNKNOWN = 0;
        public static final int NORMAL = 1;
        public static final int MODERATE = 2;
        public static final int LOW = 3;
        public static final int CRITICAL = 4;

        // enum ProcessState
        public static final int PROCESS_UNKNOWN = 0;
        public static final int PERSISTENT = 1;
        public static final int TOP = 2;
        public static final int IMPORTANT_FOREGROUND = 3;
        public static final int IMPORTANT_BACKGROUND = 4;
        public static final int BACKUP = 5;
        public static final int SERVICE = 6;
        public static final int SERVICE_RESTARTING = 7;
        public static final int RECEIVER = 8;
        public static final int HEAVY_WEIGHT = 9;
        public static final int HOME = 10;
        public static final int LAST_ACTIVITY = 11;
        public static final int CACHED_ACTIVITY = 12;
        public static final int CACHED_ACTIVITY_CLIENT = 13;
        public static final int CACHED_EMPTY = 14;

        // optional .android.service.procstats.ProcessStatsProto.State.ScreenState screen_state = 1;
        public static final long SCREEN_STATE = 0x0000010e00000001L;

        // optional .android.service.procstats.ProcessStatsProto.State.MemoryState memory_state = 2;
        public static final long MEMORY_STATE = 0x0000010e00000002L;

        // optional .android.service.procstats.ProcessStatsProto.State.ProcessState process_state = 3;
        public static final long PROCESS_STATE = 0x0000010e00000003L;

        // optional int64 duration_ms = 4;
        public static final long DURATION_MS = 0x0000010300000004L;

        // optional int32 sample_size = 5;
        public static final long SAMPLE_SIZE = 0x0000010500000005L;

        // optional .android.util.AggStats pss = 6;
        public static final long PSS = 0x0000010b00000006L;

        // optional .android.util.AggStats uss = 7;
        public static final long USS = 0x0000010b00000007L;

        // optional .android.util.AggStats rss = 8;
        public static final long RSS = 0x0000010b00000008L;

    }

    // optional string process = 1;
    public static final long PROCESS = 0x0000010900000001L;

    // optional int32 uid = 2;
    public static final long UID = 0x0000010500000002L;

    // optional .android.service.procstats.ProcessStatsProto.Kill kill = 3;
    public static final long KILL = 0x0000010b00000003L;

    // repeated .android.service.procstats.ProcessStatsProto.State states = 5;
    public static final long STATES = 0x0000020b00000005L;

}

