// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/service/print.proto

package android.service.print;

/** @hide */
// message PageRangeProto
public final class PageRangeProto {

    // optional int32 start = 1;
    public static final long START = 0x0000010500000001L;

    // optional int32 end = 2;
    public static final long END = 0x0000010500000002L;

}

