// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/service/print.proto

package android.service.print;

/** @hide */
// message PrintSpoolerInternalStateProto
public final class PrintSpoolerInternalStateProto {

    // repeated .android.service.print.PrintJobInfoProto print_jobs = 1;
    public static final long PRINT_JOBS = 0x0000020b00000001L;

    // repeated string print_job_files = 2;
    public static final long PRINT_JOB_FILES = 0x0000020900000002L;

    // repeated .android.content.ComponentNameProto approved_services = 3;
    public static final long APPROVED_SERVICES = 0x0000020b00000003L;

}

