// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/service/print.proto

package android.service.print;

/** @hide */
// message PrintSpoolerStateProto
public final class PrintSpoolerStateProto {

    // optional bool is_destroyed = 1;
    public static final long IS_DESTROYED = 0x0000010800000001L;

    // optional bool is_bound = 2;
    public static final long IS_BOUND = 0x0000010800000002L;

    // optional .android.service.print.PrintSpoolerInternalStateProto internal_state = 3;
    public static final long INTERNAL_STATE = 0x0000010b00000003L;

}

