// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/app/activitymanager.proto

package android.app;

/** @hide */
public final class ActivityManagerProto {

    // enum UidObserverFlag
    public static final int UID_OBSERVER_FLAG_PROCSTATE = 1;
    public static final int UID_OBSERVER_FLAG_GONE = 2;
    public static final int UID_OBSERVER_FLAG_IDLE = 3;
    public static final int UID_OBSERVER_FLAG_ACTIVE = 4;
    public static final int UID_OBSERVER_FLAG_CACHED = 5;

}
