// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/view/remote_animation_target.proto

package android.app;

/** @hide */
// message RemoteAnimationTargetProto
public final class RemoteAnimationTargetProto {

    // optional int32 task_id = 1;
    public static final long TASK_ID = 0x0000010500000001L;

    // optional int32 mode = 2;
    public static final long MODE = 0x0000010500000002L;

    // optional .android.view.SurfaceControlProto leash = 3;
    public static final long LEASH = 0x0000010b00000003L;

    // optional bool is_translucent = 4;
    public static final long IS_TRANSLUCENT = 0x0000010800000004L;

    // optional .android.graphics.RectProto clip_rect = 5;
    public static final long CLIP_RECT = 0x0000010b00000005L;

    // optional .android.graphics.RectProto contentInsets = 6;
    public static final long CONTENT_INSETS = 0x0000010b00000006L;

    // optional int32 prefix_order_index = 7;
    public static final long PREFIX_ORDER_INDEX = 0x0000010500000007L;

    // optional .android.graphics.PointProto position = 8;
    public static final long POSITION = 0x0000010b00000008L;

    // optional .android.graphics.RectProto source_container_bounds = 9;
    public static final long SOURCE_CONTAINER_BOUNDS = 0x0000010b00000009L;

    // optional .android.app.WindowConfigurationProto window_configuration = 10;
    public static final long WINDOW_CONFIGURATION = 0x0000010b0000000aL;

}

