// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/util/event_log_tags.proto

package android.util;

/** @hide */
// message EventLogTagMapProto
public final class EventLogTagMapProto {

    // repeated .android.util.EventLogTag event_log_tags = 1;
    public static final long EVENT_LOG_TAGS = 0x0000020b00000001L;

}

