// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/app/alarmmanager.proto

package android.app;

/** @hide */
// message AlarmClockInfoProto
public final class AlarmClockInfoProto {

    // optional int64 trigger_time_ms = 1;
    public static final long TRIGGER_TIME_MS = 0x0000010300000001L;

    // optional .android.app.PendingIntentProto show_intent = 2;
    public static final long SHOW_INTENT = 0x0000010b00000002L;

}

