// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/app/notification_channel_group.proto

package android.app;

/** @hide */
// message NotificationChannelGroupProto
public final class NotificationChannelGroupProto {

    // optional string id = 1;
    public static final long ID = 0x0000010900000001L;

    // optional string name = 2;
    public static final long NAME = 0x0000010900000002L;

    // optional string description = 3;
    public static final long DESCRIPTION = 0x0000010900000003L;

    // optional bool is_blocked = 4;
    public static final long IS_BLOCKED = 0x0000010800000004L;

    // repeated .android.app.NotificationChannelProto channels = 5;
    public static final long CHANNELS = 0x0000020b00000005L;

}

