// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/app/notification_channel.proto

package android.app;

/** @hide */
// message NotificationChannelProto
public final class NotificationChannelProto {

    // optional string id = 1;
    public static final long ID = 0x0000010900000001L;

    // optional string name = 2;
    public static final long NAME = 0x0000010900000002L;

    // optional string description = 3;
    public static final long DESCRIPTION = 0x0000010900000003L;

    // optional int32 importance = 4;
    public static final long IMPORTANCE = 0x0000010500000004L;

    // optional bool can_bypass_dnd = 5;
    public static final long CAN_BYPASS_DND = 0x0000010800000005L;

    // optional int32 lockscreen_visibility = 6;
    public static final long LOCKSCREEN_VISIBILITY = 0x0000010500000006L;

    // optional string sound = 7;
    public static final long SOUND = 0x0000010900000007L;

    // optional bool use_lights = 8;
    public static final long USE_LIGHTS = 0x0000010800000008L;

    // optional int32 light_color = 9;
    public static final long LIGHT_COLOR = 0x0000010500000009L;

    // repeated int64 vibration = 10;
    public static final long VIBRATION = 0x000002030000000aL;

    // optional int32 user_locked_fields = 11;
    public static final long USER_LOCKED_FIELDS = 0x000001050000000bL;

    // optional bool is_vibration_enabled = 12;
    public static final long IS_VIBRATION_ENABLED = 0x000001080000000cL;

    // optional bool show_badge = 13;
    public static final long SHOW_BADGE = 0x000001080000000dL;

    // optional bool is_deleted = 14;
    public static final long IS_DELETED = 0x000001080000000eL;

    // optional string group = 15;
    public static final long GROUP = 0x000001090000000fL;

    // optional .android.media.AudioAttributesProto audio_attributes = 16;
    public static final long AUDIO_ATTRIBUTES = 0x0000010b00000010L;

    // optional bool is_blockable_system = 17;
    public static final long IS_BLOCKABLE_SYSTEM = 0x0000010800000011L;

    // optional bool fg_service_shown = 18;
    public static final long FG_SERVICE_SHOWN = 0x0000010800000012L;

}

