// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/service/appwidget.proto

package android.service.appwidget;

/** @hide */
// message WidgetProto
public final class WidgetProto {

    // optional bool isCrossProfile = 1;
    public static final long IS_CROSS_PROFILE = 0x0000010800000001L;

    // optional bool isHostStopped = 2;
    public static final long IS_HOST_STOPPED = 0x0000010800000002L;

    // optional string hostPackage = 3;
    public static final long HOST_PACKAGE = 0x0000010900000003L;

    // optional string providerPackage = 4;
    public static final long PROVIDER_PACKAGE = 0x0000010900000004L;

    // optional string providerClass = 5;
    public static final long PROVIDER_CLASS = 0x0000010900000005L;

    // optional int32 minWidth = 6;
    public static final long MIN_WIDTH = 0x0000010500000006L;

    // optional int32 minHeight = 7;
    public static final long MIN_HEIGHT = 0x0000010500000007L;

    // optional int32 maxWidth = 8;
    public static final long MAX_WIDTH = 0x0000010500000008L;

    // optional int32 maxHeight = 9;
    public static final long MAX_HEIGHT = 0x0000010500000009L;

}

