// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/server/jobscheduler.proto

package com.android.server.job;

/** @hide */
// message GrantedUriPermissionsDumpProto
public final class GrantedUriPermissionsDumpProto {

    // optional int32 flags = 1;
    public static final long FLAGS = 0x0000010500000001L;

    // optional int32 source_user_id = 2;
    public static final long SOURCE_USER_ID = 0x0000010500000002L;

    // optional string tag = 3;
    public static final long TAG = 0x0000010900000003L;

    // optional string permission_owner = 4;
    public static final long PERMISSION_OWNER = 0x0000010900000004L;

    // repeated string uris = 5;
    public static final long URIS = 0x0000020900000005L;

}

