// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/server/jobscheduler.proto

package com.android.server.job;

/** @hide */
// message JobPackageTrackerDumpProto
public final class JobPackageTrackerDumpProto {

    // repeated .com.android.server.job.DataSetProto historical_stats = 1;
    public static final long HISTORICAL_STATS = 0x0000020b00000001L;

    // optional .com.android.server.job.DataSetProto current_stats = 2;
    public static final long CURRENT_STATS = 0x0000010b00000002L;

}

