// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/service/notification.proto

package android.service.notification;

/** @hide */
// message ListenersDisablingEffectsProto
public final class ListenersDisablingEffectsProto {

    // optional int32 hint = 1;
    public static final long HINT = 0x0000010500000001L;

    // repeated .android.service.notification.ManagedServiceInfoProto listeners = 2;
    public static final long LISTENERS = 0x0000020b00000002L;

}

