// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/net/network.proto

package android.net;

/** @hide */
// message NetworkProto
public final class NetworkProto {

    // optional int32 net_id = 1;
    public static final long NET_ID = 0x0000010500000001L;

}

