// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/server/windowmanagerservice.proto

package com.android.server.wm;

/** @hide */
// message AppWindowTokenProto
public final class AppWindowTokenProto {

    // optional string name = 1;
    public static final long NAME = 0x0000010900000001L;

    // optional .com.android.server.wm.WindowTokenProto window_token = 2;
    public static final long WINDOW_TOKEN = 0x0000010b00000002L;

    // optional bool last_surface_showing = 3;
    public static final long LAST_SURFACE_SHOWING = 0x0000010800000003L;

    // optional bool is_waiting_for_transition_start = 4;
    public static final long IS_WAITING_FOR_TRANSITION_START = 0x0000010800000004L;

    // optional bool is_really_animating = 5;
    public static final long IS_REALLY_ANIMATING = 0x0000010800000005L;

    // optional .com.android.server.wm.AppWindowThumbnailProto thumbnail = 6;
    public static final long THUMBNAIL = 0x0000010b00000006L;

    // optional bool fills_parent = 7;
    public static final long FILLS_PARENT = 0x0000010800000007L;

    // optional bool app_stopped = 8;
    public static final long APP_STOPPED = 0x0000010800000008L;

    // optional bool hidden_requested = 9;
    public static final long HIDDEN_REQUESTED = 0x0000010800000009L;

    // optional bool client_hidden = 10;
    public static final long CLIENT_HIDDEN = 0x000001080000000aL;

    // optional bool defer_hiding_client = 11;
    public static final long DEFER_HIDING_CLIENT = 0x000001080000000bL;

    // optional bool reported_drawn = 12;
    public static final long REPORTED_DRAWN = 0x000001080000000cL;

    // optional bool reported_visible = 13;
    public static final long REPORTED_VISIBLE = 0x000001080000000dL;

    // optional int32 num_interesting_windows = 14;
    public static final long NUM_INTERESTING_WINDOWS = 0x000001050000000eL;

    // optional int32 num_drawn_windows = 15;
    public static final long NUM_DRAWN_WINDOWS = 0x000001050000000fL;

    // optional bool all_drawn = 16;
    public static final long ALL_DRAWN = 0x0000010800000010L;

    // optional bool last_all_drawn = 17;
    public static final long LAST_ALL_DRAWN = 0x0000010800000011L;

    // optional bool removed = 18;
    public static final long REMOVED = 0x0000010800000012L;

    // optional .com.android.server.wm.IdentifierProto starting_window = 19;
    public static final long STARTING_WINDOW = 0x0000010b00000013L;

    // optional bool starting_displayed = 20;
    public static final long STARTING_DISPLAYED = 0x0000010800000014L;

    // optional bool starting_moved = 21;
    public static final long STARTING_MOVED = 0x0000010800000015L;

    // optional bool hidden_set_from_transferred_starting_window = 22;
    public static final long HIDDEN_SET_FROM_TRANSFERRED_STARTING_WINDOW = 0x0000010800000016L;

    // repeated .android.graphics.RectProto frozen_bounds = 23;
    public static final long FROZEN_BOUNDS = 0x0000020b00000017L;

}

