// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/server/windowmanagerservice.proto

package com.android.server.wm;

/** @hide */
// message BarControllerProto
public final class BarControllerProto {

    // optional .android.app.StatusBarManagerProto.WindowState state = 1;
    public static final long STATE = 0x0000010e00000001L;

    // optional .android.app.StatusBarManagerProto.TransientWindowState transient_state = 2;
    public static final long TRANSIENT_STATE = 0x0000010e00000002L;

}

