// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/server/windowmanagerservice.proto

package com.android.server.wm;

/** @hide */
// message ConfigurationContainerProto
public final class ConfigurationContainerProto {

    // optional .android.content.ConfigurationProto override_configuration = 1;
    public static final long OVERRIDE_CONFIGURATION = 0x0000010b00000001L;

    // optional .android.content.ConfigurationProto full_configuration = 2;
    public static final long FULL_CONFIGURATION = 0x0000010b00000002L;

    // optional .android.content.ConfigurationProto merged_override_configuration = 3;
    public static final long MERGED_OVERRIDE_CONFIGURATION = 0x0000010b00000003L;

}

