// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/server/animationadapter.proto

package com.android.server.wm;

/** @hide */
// message MoveAnimationSpecProto
public final class MoveAnimationSpecProto {

    // optional .android.graphics.PointProto from = 1;
    public static final long FROM = 0x0000010b00000001L;

    // optional .android.graphics.PointProto to = 2;
    public static final long TO = 0x0000010b00000002L;

    // optional int64 duration_ms = 3;
    public static final long DURATION_MS = 0x0000010300000003L;

}

