// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/server/windowmanagerservice.proto

package com.android.server.wm;

/** @hide */
// message WindowStateProto
public final class WindowStateProto {

    // optional .com.android.server.wm.WindowContainerProto window_container = 1;
    public static final long WINDOW_CONTAINER = 0x0000010b00000001L;

    // optional .com.android.server.wm.IdentifierProto identifier = 2;
    public static final long IDENTIFIER = 0x0000010b00000002L;

    // optional int32 display_id = 3;
    public static final long DISPLAY_ID = 0x0000010500000003L;

    // optional int32 stack_id = 4;
    public static final long STACK_ID = 0x0000010500000004L;

    // optional .android.view.WindowLayoutParamsProto attributes = 5;
    public static final long ATTRIBUTES = 0x0000010b00000005L;

    // optional .android.graphics.RectProto given_content_insets = 6;
    public static final long GIVEN_CONTENT_INSETS = 0x0000010b00000006L;

    // optional .android.graphics.RectProto frame = 7;
    public static final long FRAME = 0x0000010b00000007L;

    // optional .android.graphics.RectProto containing_frame = 8;
    public static final long CONTAINING_FRAME = 0x0000010b00000008L;

    // optional .android.graphics.RectProto parent_frame = 9;
    public static final long PARENT_FRAME = 0x0000010b00000009L;

    // optional .android.graphics.RectProto content_frame = 10;
    public static final long CONTENT_FRAME = 0x0000010b0000000aL;

    // optional .android.graphics.RectProto content_insets = 11;
    public static final long CONTENT_INSETS = 0x0000010b0000000bL;

    // optional .android.graphics.RectProto surface_insets = 12;
    public static final long SURFACE_INSETS = 0x0000010b0000000cL;

    // optional .com.android.server.wm.WindowStateAnimatorProto animator = 13;
    public static final long ANIMATOR = 0x0000010b0000000dL;

    // optional bool animating_exit = 14;
    public static final long ANIMATING_EXIT = 0x000001080000000eL;

    // repeated .com.android.server.wm.WindowStateProto child_windows = 15;
    public static final long CHILD_WINDOWS = 0x0000020b0000000fL;

    // optional .android.graphics.RectProto surface_position = 16;
    public static final long SURFACE_POSITION = 0x0000010b00000010L;

    // optional int32 requested_width = 18;
    public static final long REQUESTED_WIDTH = 0x0000010500000012L;

    // optional int32 requested_height = 19;
    public static final long REQUESTED_HEIGHT = 0x0000010500000013L;

    // optional int32 view_visibility = 20;
    public static final long VIEW_VISIBILITY = 0x0000010500000014L;

    // optional int32 system_ui_visibility = 21;
    public static final long SYSTEM_UI_VISIBILITY = 0x0000010500000015L;

    // optional bool has_surface = 22;
    public static final long HAS_SURFACE = 0x0000010800000016L;

    // optional bool is_ready_for_display = 23;
    public static final long IS_READY_FOR_DISPLAY = 0x0000010800000017L;

    // optional .android.graphics.RectProto display_frame = 24;
    public static final long DISPLAY_FRAME = 0x0000010b00000018L;

    // optional .android.graphics.RectProto overscan_frame = 25;
    public static final long OVERSCAN_FRAME = 0x0000010b00000019L;

    // optional .android.graphics.RectProto visible_frame = 26;
    public static final long VISIBLE_FRAME = 0x0000010b0000001aL;

    // optional .android.graphics.RectProto decor_frame = 27;
    public static final long DECOR_FRAME = 0x0000010b0000001bL;

    // optional .android.graphics.RectProto outset_frame = 28;
    public static final long OUTSET_FRAME = 0x0000010b0000001cL;

    // optional .android.graphics.RectProto overscan_insets = 29;
    public static final long OVERSCAN_INSETS = 0x0000010b0000001dL;

    // optional .android.graphics.RectProto visible_insets = 30;
    public static final long VISIBLE_INSETS = 0x0000010b0000001eL;

    // optional .android.graphics.RectProto stable_insets = 31;
    public static final long STABLE_INSETS = 0x0000010b0000001fL;

    // optional .android.graphics.RectProto outsets = 32;
    public static final long OUTSETS = 0x0000010b00000020L;

    // optional .android.view.DisplayCutoutProto cutout = 33;
    public static final long CUTOUT = 0x0000010b00000021L;

    // optional bool remove_on_exit = 34;
    public static final long REMOVE_ON_EXIT = 0x0000010800000022L;

    // optional bool destroying = 35;
    public static final long DESTROYING = 0x0000010800000023L;

    // optional bool removed = 36;
    public static final long REMOVED = 0x0000010800000024L;

    // optional bool is_on_screen = 37;
    public static final long IS_ON_SCREEN = 0x0000010800000025L;

    // optional bool is_visible = 38;
    public static final long IS_VISIBLE = 0x0000010800000026L;

    // optional bool pending_forced_seamless_rotation = 39;
    public static final long PENDING_FORCED_SEAMLESS_ROTATION = 0x0000010800000027L;

    // optional int64 finished_forced_seamless_rotation_frame = 40;
    public static final long FINISHED_FORCED_SEAMLESS_ROTATION_FRAME = 0x0000010300000028L;

}

