// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/server/windowmanagertrace.proto

package com.android.server.wm;

/** @hide */
// message WindowManagerTraceProto
public final class WindowManagerTraceProto {

    // optional fixed64 elapsed_realtime_nanos = 1;
    public static final long ELAPSED_REALTIME_NANOS = 0x0000010600000001L;

    // optional string where = 2;
    public static final long WHERE = 0x0000010900000002L;

    // optional .com.android.server.wm.WindowManagerServiceDumpProto window_manager_service = 3;
    public static final long WINDOW_MANAGER_SERVICE = 0x0000010b00000003L;

}

