// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/server/windowmanagertrace.proto

package com.android.server.wm;

/** @hide */
// message WindowManagerTraceFileProto
public final class WindowManagerTraceFileProto {

    // enum MagicNumber
    public static final int INVALID = 0;
    public static final int MAGIC_NUMBER_L = 1414416727;
    public static final int MAGIC_NUMBER_H = 1162035538;

    // optional fixed64 magic_number = 1;
    public static final long MAGIC_NUMBER = 0x0000010600000001L;

    // repeated .com.android.server.wm.WindowManagerTraceProto entry = 2;
    public static final long ENTRY = 0x0000020b00000002L;

}

