// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/server/windowmanagerservice.proto

package com.android.server.wm;

/** @hide */
// message WindowContainerProto
public final class WindowContainerProto {

    // optional .com.android.server.wm.ConfigurationContainerProto configuration_container = 1;
    public static final long CONFIGURATION_CONTAINER = 0x0000010b00000001L;

    // optional int32 orientation = 2;
    public static final long ORIENTATION = 0x0000010500000002L;

    // optional bool visible = 3;
    public static final long VISIBLE = 0x0000010800000003L;

    // optional .com.android.server.wm.SurfaceAnimatorProto surface_animator = 4;
    public static final long SURFACE_ANIMATOR = 0x0000010b00000004L;

}

