// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/server/windowmanagerservice.proto

package com.android.server.wm;

/** @hide */
// message WindowStateAnimatorProto
public final class WindowStateAnimatorProto {

    // enum DrawState
    public static final int NO_SURFACE = 0;
    public static final int DRAW_PENDING = 1;
    public static final int COMMIT_DRAW_PENDING = 2;
    public static final int READY_TO_SHOW = 3;
    public static final int HAS_DRAWN = 4;

    // optional .android.graphics.RectProto last_clip_rect = 1;
    public static final long LAST_CLIP_RECT = 0x0000010b00000001L;

    // optional .com.android.server.wm.WindowSurfaceControllerProto surface = 2;
    public static final long SURFACE = 0x0000010b00000002L;

    // optional .com.android.server.wm.WindowStateAnimatorProto.DrawState draw_state = 3;
    public static final long DRAW_STATE = 0x0000010e00000003L;

    // optional .android.graphics.RectProto system_decor_rect = 4;
    public static final long SYSTEM_DECOR_RECT = 0x0000010b00000004L;

}

