// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/view/displayinfo.proto

package android.view;

/** @hide */
// message DisplayInfoProto
public final class DisplayInfoProto {

    // optional int32 logical_width = 1;
    public static final long LOGICAL_WIDTH = 0x0000010500000001L;

    // optional int32 logical_height = 2;
    public static final long LOGICAL_HEIGHT = 0x0000010500000002L;

    // optional int32 app_width = 3;
    public static final long APP_WIDTH = 0x0000010500000003L;

    // optional int32 app_height = 4;
    public static final long APP_HEIGHT = 0x0000010500000004L;

    // optional string name = 5;
    public static final long NAME = 0x0000010900000005L;

}

