// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/view/windowlayoutparams.proto

package android.view;

/** @hide */
// message WindowLayoutParamsProto
public final class WindowLayoutParamsProto {

    // enum RotationAnimation
    public static final int ROTATION_ANIMATION_UNSPECIFIED = -1;
    public static final int ROTATION_ANIMATION_CROSSFADE = 1;
    public static final int ROTATION_ANIMATION_JUMPCUT = 2;
    public static final int ROTATION_ANIMATION_SEAMLESS = 3;

    // enum NeedsMenuState
    public static final int NEEDS_MENU_UNSET = 0;
    public static final int NEEDS_MENU_SET_TRUE = 1;
    public static final int NEEDS_MENU_SET_FALSE = 2;

    // optional int32 type = 1;
    public static final long TYPE = 0x0000010500000001L;

    // optional int32 x = 2;
    public static final long X = 0x0000010500000002L;

    // optional int32 y = 3;
    public static final long Y = 0x0000010500000003L;

    // optional int32 width = 4;
    public static final long WIDTH = 0x0000010500000004L;

    // optional int32 height = 5;
    public static final long HEIGHT = 0x0000010500000005L;

    // optional float horizontal_margin = 6;
    public static final long HORIZONTAL_MARGIN = 0x0000010200000006L;

    // optional float vertical_margin = 7;
    public static final long VERTICAL_MARGIN = 0x0000010200000007L;

    // optional int32 gravity = 8;
    public static final long GRAVITY = 0x0000010500000008L;

    // optional int32 soft_input_mode = 9;
    public static final long SOFT_INPUT_MODE = 0x0000010500000009L;

    // optional .android.graphics.PixelFormatProto.Format format = 10;
    public static final long FORMAT = 0x0000010e0000000aL;

    // optional int32 window_animations = 11;
    public static final long WINDOW_ANIMATIONS = 0x000001050000000bL;

    // optional float alpha = 12;
    public static final long ALPHA = 0x000001020000000cL;

    // optional float screen_brightness = 13;
    public static final long SCREEN_BRIGHTNESS = 0x000001020000000dL;

    // optional float button_brightness = 14;
    public static final long BUTTON_BRIGHTNESS = 0x000001020000000eL;

    // optional .android.view.WindowLayoutParamsProto.RotationAnimation rotation_animation = 15;
    public static final long ROTATION_ANIMATION = 0x0000010e0000000fL;

    // optional float preferred_refresh_rate = 16;
    public static final long PREFERRED_REFRESH_RATE = 0x0000010200000010L;

    // optional int32 preferred_display_mode_id = 17;
    public static final long PREFERRED_DISPLAY_MODE_ID = 0x0000010500000011L;

    // optional bool has_system_ui_listeners = 18;
    public static final long HAS_SYSTEM_UI_LISTENERS = 0x0000010800000012L;

    // optional uint32 input_feature_flags = 19;
    public static final long INPUT_FEATURE_FLAGS = 0x0000010d00000013L;

    // optional int64 user_activity_timeout = 20;
    public static final long USER_ACTIVITY_TIMEOUT = 0x0000010300000014L;

    // optional .android.view.WindowLayoutParamsProto.NeedsMenuState needs_menu_key = 22;
    public static final long NEEDS_MENU_KEY = 0x0000010e00000016L;

    // optional .android.view.DisplayProto.ColorMode color_mode = 23;
    public static final long COLOR_MODE = 0x0000010e00000017L;

    // optional uint32 flags = 24;
    public static final long FLAGS = 0x0000010d00000018L;

    // optional uint32 private_flags = 26;
    public static final long PRIVATE_FLAGS = 0x0000010d0000001aL;

    // optional uint32 system_ui_visibility_flags = 27;
    public static final long SYSTEM_UI_VISIBILITY_FLAGS = 0x0000010d0000001bL;

    // optional uint32 subtree_system_ui_visibility_flags = 28;
    public static final long SUBTREE_SYSTEM_UI_VISIBILITY_FLAGS = 0x0000010d0000001cL;

}

