// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/content/clipdescription.proto

package android.content;

/** @hide */
// message ClipDescriptionProto
public final class ClipDescriptionProto {

    // repeated string mime_types = 1;
    public static final long MIME_TYPES = 0x0000020900000001L;

    // optional string label = 2;
    public static final long LABEL = 0x0000010900000002L;

    // optional .android.os.PersistableBundleProto extras = 3;
    public static final long EXTRAS = 0x0000010b00000003L;

    // optional int64 timestamp_ms = 4;
    public static final long TIMESTAMP_MS = 0x0000010300000004L;

}

