// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/content/configuration.proto

package android.content;

/** @hide */
// message ConfigurationProto
public final class ConfigurationProto {

    // optional float font_scale = 1;
    public static final long FONT_SCALE = 0x0000010200000001L;

    // optional uint32 mcc = 2;
    public static final long MCC = 0x0000010d00000002L;

    // optional uint32 mnc = 3;
    public static final long MNC = 0x0000010d00000003L;

    // repeated .android.content.LocaleProto locales = 4;
    public static final long LOCALES = 0x0000020b00000004L;

    // optional uint32 screen_layout = 5;
    public static final long SCREEN_LAYOUT = 0x0000010d00000005L;

    // optional uint32 color_mode = 6;
    public static final long COLOR_MODE = 0x0000010d00000006L;

    // optional uint32 touchscreen = 7;
    public static final long TOUCHSCREEN = 0x0000010d00000007L;

    // optional uint32 keyboard = 8;
    public static final long KEYBOARD = 0x0000010d00000008L;

    // optional uint32 keyboard_hidden = 9;
    public static final long KEYBOARD_HIDDEN = 0x0000010d00000009L;

    // optional uint32 hard_keyboard_hidden = 10;
    public static final long HARD_KEYBOARD_HIDDEN = 0x0000010d0000000aL;

    // optional uint32 navigation = 11;
    public static final long NAVIGATION = 0x0000010d0000000bL;

    // optional uint32 navigation_hidden = 12;
    public static final long NAVIGATION_HIDDEN = 0x0000010d0000000cL;

    // optional uint32 orientation = 13;
    public static final long ORIENTATION = 0x0000010d0000000dL;

    // optional uint32 ui_mode = 14;
    public static final long UI_MODE = 0x0000010d0000000eL;

    // optional uint32 screen_width_dp = 15;
    public static final long SCREEN_WIDTH_DP = 0x0000010d0000000fL;

    // optional uint32 screen_height_dp = 16;
    public static final long SCREEN_HEIGHT_DP = 0x0000010d00000010L;

    // optional uint32 smallest_screen_width_dp = 17;
    public static final long SMALLEST_SCREEN_WIDTH_DP = 0x0000010d00000011L;

    // optional uint32 density_dpi = 18;
    public static final long DENSITY_DPI = 0x0000010d00000012L;

    // optional .android.app.WindowConfigurationProto window_configuration = 19;
    public static final long WINDOW_CONFIGURATION = 0x0000010b00000013L;

}

