// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/app/alarmmanager.proto

package android.app;

/** @hide */
// message AlarmManagerProto
public final class AlarmManagerProto {

    // enum AlarmType
    public static final int RTC_WAKEUP = 0;
    public static final int RTC = 1;
    public static final int ELAPSED_REALTIME_WAKEUP = 2;
    public static final int ELAPSED_REALTIME = 3;

}

