// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/app/window_configuration.proto

package android.app;

/** @hide */
// message WindowConfigurationProto
public final class WindowConfigurationProto {

    // optional .android.graphics.RectProto app_bounds = 1;
    public static final long APP_BOUNDS = 0x0000010b00000001L;

    // optional int32 windowing_mode = 2;
    public static final long WINDOWING_MODE = 0x0000010500000002L;

    // optional int32 activity_type = 3;
    public static final long ACTIVITY_TYPE = 0x0000010500000003L;

}

