// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/server/alarmmanagerservice.proto

package com.android.server;

/** @hide */
// message BatchProto
public final class BatchProto {

    // optional int64 start_realtime = 1;
    public static final long START_REALTIME = 0x0000010300000001L;

    // optional int64 end_realtime = 2;
    public static final long END_REALTIME = 0x0000010300000002L;

    // optional int32 flags = 3;
    public static final long FLAGS = 0x0000010500000003L;

    // repeated .com.android.server.AlarmProto alarms = 4;
    public static final long ALARMS = 0x0000020b00000004L;

}

