// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/server/alarmmanagerservice.proto

package com.android.server;

/** @hide */
// message ConstantsProto
public final class ConstantsProto {

    // optional int64 min_futurity_duration_ms = 1;
    public static final long MIN_FUTURITY_DURATION_MS = 0x0000010300000001L;

    // optional int64 min_interval_duration_ms = 2;
    public static final long MIN_INTERVAL_DURATION_MS = 0x0000010300000002L;

    // optional int64 listener_timeout_duration_ms = 3;
    public static final long LISTENER_TIMEOUT_DURATION_MS = 0x0000010300000003L;

    // optional int64 allow_while_idle_short_duration_ms = 4;
    public static final long ALLOW_WHILE_IDLE_SHORT_DURATION_MS = 0x0000010300000004L;

    // optional int64 allow_while_idle_long_duration_ms = 5;
    public static final long ALLOW_WHILE_IDLE_LONG_DURATION_MS = 0x0000010300000005L;

    // optional int64 allow_while_idle_whitelist_duration_ms = 6;
    public static final long ALLOW_WHILE_IDLE_WHITELIST_DURATION_MS = 0x0000010300000006L;

    // optional int64 max_interval_duration_ms = 7;
    public static final long MAX_INTERVAL_DURATION_MS = 0x0000010300000007L;

}

