// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/server/enums.proto

package android.server;

/** @hide */
public final class ServerProtoEnums {

    // enum DeviceIdleModeEnum
    public static final int DEVICE_IDLE_MODE_OFF = 0;
    public static final int DEVICE_IDLE_MODE_LIGHT = 1;
    public static final int DEVICE_IDLE_MODE_DEEP = 2;

}
