// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/service/graphicsstats.proto

package android.service;

/** @hide */
// message GraphicsStatsJankSummaryProto
public final class GraphicsStatsJankSummaryProto {

    // optional int32 total_frames = 1;
    public static final long TOTAL_FRAMES = 0x0000010500000001L;

    // optional int32 janky_frames = 2;
    public static final long JANKY_FRAMES = 0x0000010500000002L;

    // optional int32 missed_vsync_count = 3;
    public static final long MISSED_VSYNC_COUNT = 0x0000010500000003L;

    // optional int32 high_input_latency_count = 4;
    public static final long HIGH_INPUT_LATENCY_COUNT = 0x0000010500000004L;

    // optional int32 slow_ui_thread_count = 5;
    public static final long SLOW_UI_THREAD_COUNT = 0x0000010500000005L;

    // optional int32 slow_bitmap_upload_count = 6;
    public static final long SLOW_BITMAP_UPLOAD_COUNT = 0x0000010500000006L;

    // optional int32 slow_draw_count = 7;
    public static final long SLOW_DRAW_COUNT = 0x0000010500000007L;

    // optional int32 missed_deadline_count = 8;
    public static final long MISSED_DEADLINE_COUNT = 0x0000010500000008L;

}

