// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/server/windowmanagerservice.proto

package com.android.server.wm;

/** @hide */
// message PinnedStackControllerProto
public final class PinnedStackControllerProto {

    // optional .android.graphics.RectProto default_bounds = 1;
    public static final long DEFAULT_BOUNDS = 0x0000010b00000001L;

    // optional .android.graphics.RectProto movement_bounds = 2;
    public static final long MOVEMENT_BOUNDS = 0x0000010b00000002L;

}

