// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/server/windowmanagerservice.proto

package com.android.server.wm;

/** @hide */
// message StackProto
public final class StackProto {

    // optional .com.android.server.wm.WindowContainerProto window_container = 1;
    public static final long WINDOW_CONTAINER = 0x0000010b00000001L;

    // optional int32 id = 2;
    public static final long ID = 0x0000010500000002L;

    // repeated .com.android.server.wm.TaskProto tasks = 3;
    public static final long TASKS = 0x0000020b00000003L;

    // optional bool fills_parent = 4;
    public static final long FILLS_PARENT = 0x0000010800000004L;

    // optional .android.graphics.RectProto bounds = 5;
    public static final long BOUNDS = 0x0000010b00000005L;

    // optional bool animation_background_surface_is_dimming = 6;
    public static final long ANIMATION_BACKGROUND_SURFACE_IS_DIMMING = 0x0000010800000006L;

    // optional bool defer_removal = 7;
    public static final long DEFER_REMOVAL = 0x0000010800000007L;

    // optional float minimize_amount = 8;
    public static final long MINIMIZE_AMOUNT = 0x0000010200000008L;

    // optional bool adjusted_for_ime = 9;
    public static final long ADJUSTED_FOR_IME = 0x0000010800000009L;

    // optional float adjust_ime_amount = 10;
    public static final long ADJUST_IME_AMOUNT = 0x000001020000000aL;

    // optional float adjust_divider_amount = 11;
    public static final long ADJUST_DIVIDER_AMOUNT = 0x000001020000000bL;

    // optional .android.graphics.RectProto adjusted_bounds = 12;
    public static final long ADJUSTED_BOUNDS = 0x0000010b0000000cL;

    // optional bool animating_bounds = 13;
    public static final long ANIMATING_BOUNDS = 0x000001080000000dL;

}

