// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/server/surfaceanimator.proto

package com.android.server.wm;

/** @hide */
// message SurfaceAnimatorProto
public final class SurfaceAnimatorProto {

    // optional .android.view.SurfaceControlProto leash = 1;
    public static final long LEASH = 0x0000010b00000001L;

    // optional bool animation_start_delayed = 2;
    public static final long ANIMATION_START_DELAYED = 0x0000010800000002L;

    // optional .com.android.server.wm.AnimationAdapterProto animation_adapter = 3;
    public static final long ANIMATION_ADAPTER = 0x0000010b00000003L;

}

