// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/server/windowmanagerservice.proto

package com.android.server.wm;

/** @hide */
// message WindowOrientationListenerProto
public final class WindowOrientationListenerProto {

    // optional bool enabled = 1;
    public static final long ENABLED = 0x0000010800000001L;

    // optional .android.view.SurfaceProto.Rotation rotation = 2;
    public static final long ROTATION = 0x0000010e00000002L;

}

