// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/server/animationadapter.proto

package com.android.server.wm;

/** @hide */
// message AnimationSpecProto
public final class AnimationSpecProto {

    // optional .com.android.server.wm.WindowAnimationSpecProto window = 1;
    public static final long WINDOW = 0x0000010b00000001L;

    // optional .com.android.server.wm.MoveAnimationSpecProto move = 2;
    public static final long MOVE = 0x0000010b00000002L;

    // optional .com.android.server.wm.AlphaAnimationSpecProto alpha = 3;
    public static final long ALPHA = 0x0000010b00000003L;

}

