// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/server/appwindowthumbnail.proto

package com.android.server.wm;

/** @hide */
// message AppWindowThumbnailProto
public final class AppWindowThumbnailProto {

    // optional int32 width = 1;
    public static final long WIDTH = 0x0000010500000001L;

    // optional int32 height = 2;
    public static final long HEIGHT = 0x0000010500000002L;

    // optional .com.android.server.wm.SurfaceAnimatorProto surface_animator = 3;
    public static final long SURFACE_ANIMATOR = 0x0000010b00000003L;

}

