// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/server/windowmanagerservice.proto

package com.android.server.wm;

/** @hide */
// message DisplayProto
public final class DisplayProto {

    // optional .com.android.server.wm.WindowContainerProto window_container = 1;
    public static final long WINDOW_CONTAINER = 0x0000010b00000001L;

    // optional int32 id = 2;
    public static final long ID = 0x0000010500000002L;

    // repeated .com.android.server.wm.StackProto stacks = 3;
    public static final long STACKS = 0x0000020b00000003L;

    // optional .com.android.server.wm.DockedStackDividerControllerProto docked_stack_divider_controller = 4;
    public static final long DOCKED_STACK_DIVIDER_CONTROLLER = 0x0000010b00000004L;

    // optional .com.android.server.wm.PinnedStackControllerProto pinned_stack_controller = 5;
    public static final long PINNED_STACK_CONTROLLER = 0x0000010b00000005L;

    // repeated .com.android.server.wm.WindowTokenProto above_app_windows = 6;
    public static final long ABOVE_APP_WINDOWS = 0x0000020b00000006L;

    // repeated .com.android.server.wm.WindowTokenProto below_app_windows = 7;
    public static final long BELOW_APP_WINDOWS = 0x0000020b00000007L;

    // repeated .com.android.server.wm.WindowTokenProto ime_windows = 8;
    public static final long IME_WINDOWS = 0x0000020b00000008L;

    // optional int32 dpi = 9;
    public static final long DPI = 0x0000010500000009L;

    // optional .android.view.DisplayInfoProto display_info = 10;
    public static final long DISPLAY_INFO = 0x0000010b0000000aL;

    // optional int32 rotation = 11;
    public static final long ROTATION = 0x000001050000000bL;

    // optional .com.android.server.wm.ScreenRotationAnimationProto screen_rotation_animation = 12;
    public static final long SCREEN_ROTATION_ANIMATION = 0x0000010b0000000cL;

    // optional .com.android.server.wm.DisplayFramesProto display_frames = 13;
    public static final long DISPLAY_FRAMES = 0x0000010b0000000dL;

}

