// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/server/windowmanagerservice.proto

package com.android.server.wm;

/** @hide */
// message IdentifierProto
public final class IdentifierProto {

    // optional int32 hash_code = 1;
    public static final long HASH_CODE = 0x0000010500000001L;

    // optional int32 user_id = 2;
    public static final long USER_ID = 0x0000010500000002L;

    // optional string title = 3;
    public static final long TITLE = 0x0000010900000003L;

}

