// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/server/animationadapter.proto

package com.android.server.wm;

/** @hide */
// message LocalAnimationAdapterProto
public final class LocalAnimationAdapterProto {

    // optional .com.android.server.wm.AnimationSpecProto animation_spec = 1;
    public static final long ANIMATION_SPEC = 0x0000010b00000001L;

}

