// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/server/animationadapter.proto

package com.android.server.wm;

/** @hide */
// message RemoteAnimationAdapterWrapperProto
public final class RemoteAnimationAdapterWrapperProto {

    // optional .android.view.RemoteAnimationTargetProto target = 1;
    public static final long TARGET = 0x0000010b00000001L;

}

