// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/server/windowmanagerservice.proto

package com.android.server.wm;

/** @hide */
// message ScreenRotationAnimationProto
public final class ScreenRotationAnimationProto {

    // optional bool started = 1;
    public static final long STARTED = 0x0000010800000001L;

    // optional bool animation_running = 2;
    public static final long ANIMATION_RUNNING = 0x0000010800000002L;

}

