// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/server/windowmanagerservice.proto

package com.android.server.wm;

/** @hide */
// message WindowTokenProto
public final class WindowTokenProto {

    // optional .com.android.server.wm.WindowContainerProto window_container = 1;
    public static final long WINDOW_CONTAINER = 0x0000010b00000001L;

    // optional int32 hash_code = 2;
    public static final long HASH_CODE = 0x0000010500000002L;

    // repeated .com.android.server.wm.WindowStateProto windows = 3;
    public static final long WINDOWS = 0x0000020b00000003L;

    // optional bool hidden = 4;
    public static final long HIDDEN = 0x0000010800000004L;

    // optional bool waiting_to_show = 5;
    public static final long WAITING_TO_SHOW = 0x0000010800000005L;

    // optional bool paused = 6;
    public static final long PAUSED = 0x0000010800000006L;

}

