// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/server/animationadapter.proto

package com.android.server.wm;

/** @hide */
// message WindowAnimationSpecProto
public final class WindowAnimationSpecProto {

    // optional string animation = 1;
    public static final long ANIMATION = 0x0000010900000001L;

}

