// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/service/batterystats.proto

package android.service.batterystats;

/** @hide */
// message BatteryStatsServiceDumpHistoryProto
public final class BatteryStatsServiceDumpHistoryProto {

    // message Key
    public final class Key {

        // optional int32 index = 1;
        public static final long INDEX = 0x0000010500000001L;

        // optional int32 uid = 2;
        public static final long UID = 0x0000010500000002L;

        // optional string tag = 3;
        public static final long TAG = 0x0000010900000003L;

    }

    // optional int32 report_version = 1;
    public static final long REPORT_VERSION = 0x0000010500000001L;

    // optional int64 parcel_version = 2;
    public static final long PARCEL_VERSION = 0x0000010300000002L;

    // optional string start_platform_version = 3;
    public static final long START_PLATFORM_VERSION = 0x0000010900000003L;

    // optional string end_platform_version = 4;
    public static final long END_PLATFORM_VERSION = 0x0000010900000004L;

    // repeated .android.service.batterystats.BatteryStatsServiceDumpHistoryProto.Key keys = 5;
    public static final long KEYS = 0x0000020b00000005L;

    // repeated string csv_lines = 6;
    public static final long CSV_LINES = 0x0000020900000006L;

}

