// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/service/batterystats.proto

package android.service.batterystats;

/** @hide */
// message BatteryStatsServiceDumpProto
public final class BatteryStatsServiceDumpProto {

    // optional .android.os.BatteryStatsProto batterystats = 1;
    public static final long BATTERYSTATS = 0x0000010b00000001L;

}

