// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/content/package_item_info.proto

package android.content.pm;

/** @hide */
// message ApplicationInfoProto
public final class ApplicationInfoProto {

    // message Version
    public final class Version {

        // optional bool enabled = 1;
        public static final long ENABLED = 0x0000010800000001L;

        // optional int32 min_sdk_version = 2;
        public static final long MIN_SDK_VERSION = 0x0000010500000002L;

        // optional int32 target_sdk_version = 3;
        public static final long TARGET_SDK_VERSION = 0x0000010500000003L;

        // optional int32 version_code = 4;
        public static final long VERSION_CODE = 0x0000010500000004L;

        // optional int32 target_sandbox_version = 5;
        public static final long TARGET_SANDBOX_VERSION = 0x0000010500000005L;

    }

    // message Detail
    public final class Detail {

        // optional string class_name = 1;
        public static final long CLASS_NAME = 0x0000010900000001L;

        // optional string task_affinity = 2;
        public static final long TASK_AFFINITY = 0x0000010900000002L;

        // optional int32 requires_smallest_width_dp = 3;
        public static final long REQUIRES_SMALLEST_WIDTH_DP = 0x0000010500000003L;

        // optional int32 compatible_width_limit_dp = 4;
        public static final long COMPATIBLE_WIDTH_LIMIT_DP = 0x0000010500000004L;

        // optional int32 largest_width_limit_dp = 5;
        public static final long LARGEST_WIDTH_LIMIT_DP = 0x0000010500000005L;

        // optional string seinfo = 6;
        public static final long SEINFO = 0x0000010900000006L;

        // optional string seinfo_user = 7;
        public static final long SEINFO_USER = 0x0000010900000007L;

        // optional string device_protected_data_dir = 8;
        public static final long DEVICE_PROTECTED_DATA_DIR = 0x0000010900000008L;

        // optional string credential_protected_data_dir = 9;
        public static final long CREDENTIAL_PROTECTED_DATA_DIR = 0x0000010900000009L;

        // repeated string shared_library_files = 10;
        public static final long SHARED_LIBRARY_FILES = 0x000002090000000aL;

        // optional string manage_space_activity_name = 11;
        public static final long MANAGE_SPACE_ACTIVITY_NAME = 0x000001090000000bL;

        // optional int32 description_res = 12;
        public static final long DESCRIPTION_RES = 0x000001050000000cL;

        // optional int32 ui_options = 13;
        public static final long UI_OPTIONS = 0x000001050000000dL;

        // optional bool supports_rtl = 14;
        public static final long SUPPORTS_RTL = 0x000001080000000eL;

        // optional string content = 15;
        public static final long CONTENT = 0x000001090000000fL;

        // optional bool is_full_backup = 16;
        public static final long IS_FULL_BACKUP = 0x0000010800000010L;

        // optional int32 networkSecurity_config_res = 17;
        public static final long NETWORK_SECURITY_CONFIG_RES = 0x0000010500000011L;

        // optional int32 category = 18;
        public static final long CATEGORY = 0x0000010500000012L;

    }

    // optional .android.content.pm.PackageItemInfoProto package = 1;
    public static final long PACKAGE = 0x0000010b00000001L;

    // optional string permission = 2;
    public static final long PERMISSION = 0x0000010900000002L;

    // optional string process_name = 3;
    public static final long PROCESS_NAME = 0x0000010900000003L;

    // optional int32 uid = 4;
    public static final long UID = 0x0000010500000004L;

    // optional int32 flags = 5;
    public static final long FLAGS = 0x0000010500000005L;

    // optional int32 private_flags = 6;
    public static final long PRIVATE_FLAGS = 0x0000010500000006L;

    // optional int32 theme = 7;
    public static final long THEME = 0x0000010500000007L;

    // optional string source_dir = 8;
    public static final long SOURCE_DIR = 0x0000010900000008L;

    // optional string public_source_dir = 9;
    public static final long PUBLIC_SOURCE_DIR = 0x0000010900000009L;

    // repeated string split_source_dirs = 10;
    public static final long SPLIT_SOURCE_DIRS = 0x000002090000000aL;

    // repeated string split_public_source_dirs = 11;
    public static final long SPLIT_PUBLIC_SOURCE_DIRS = 0x000002090000000bL;

    // repeated string resource_dirs = 12;
    public static final long RESOURCE_DIRS = 0x000002090000000cL;

    // optional string data_dir = 13;
    public static final long DATA_DIR = 0x000001090000000dL;

    // optional string class_loader_name = 14;
    public static final long CLASS_LOADER_NAME = 0x000001090000000eL;

    // repeated string split_class_loader_names = 15;
    public static final long SPLIT_CLASS_LOADER_NAMES = 0x000002090000000fL;

    // optional .android.content.pm.ApplicationInfoProto.Version version = 16;
    public static final long VERSION = 0x0000010b00000010L;

    // optional .android.content.pm.ApplicationInfoProto.Detail detail = 17;
    public static final long DETAIL = 0x0000010b00000011L;

}

