// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/internal/processstats.proto

package com.android.internal.app.procstats;

/** @hide */
public final class Processstats {

    // message ProcessStatsProto
    public final class ProcessStatsProto {

        // enum MemoryFactor
        public static final int MEM_FACTOR_NORMAL = 0;
        public static final int MEM_FACTOR_MODERATE = 1;
        public static final int MEM_FACTOR_LOW = 2;
        public static final int MEM_FACTOR_CRITICAL = 3;

    }

}
