// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/server/jobscheduler.proto

package com.android.server.job;

/** @hide */
// message ConstantsProto
public final class ConstantsProto {

    // optional int32 min_idle_count = 1;
    public static final long MIN_IDLE_COUNT = 0x0000010500000001L;

    // optional int32 min_charging_count = 2;
    public static final long MIN_CHARGING_COUNT = 0x0000010500000002L;

    // optional int32 min_battery_not_low_count = 3;
    public static final long MIN_BATTERY_NOT_LOW_COUNT = 0x0000010500000003L;

    // optional int32 min_storage_not_low_count = 4;
    public static final long MIN_STORAGE_NOT_LOW_COUNT = 0x0000010500000004L;

    // optional int32 min_connectivity_count = 5;
    public static final long MIN_CONNECTIVITY_COUNT = 0x0000010500000005L;

    // optional int32 min_content_count = 6;
    public static final long MIN_CONTENT_COUNT = 0x0000010500000006L;

    // optional int32 min_ready_jobs_count = 7;
    public static final long MIN_READY_JOBS_COUNT = 0x0000010500000007L;

    // optional double heavy_use_factor = 8;
    public static final long HEAVY_USE_FACTOR = 0x0000010100000008L;

    // optional double moderate_use_factor = 9;
    public static final long MODERATE_USE_FACTOR = 0x0000010100000009L;

    // optional int32 fg_job_count = 10;
    public static final long FG_JOB_COUNT = 0x000001050000000aL;

    // optional int32 bg_normal_job_count = 11;
    public static final long BG_NORMAL_JOB_COUNT = 0x000001050000000bL;

    // optional int32 bg_moderate_job_count = 12;
    public static final long BG_MODERATE_JOB_COUNT = 0x000001050000000cL;

    // optional int32 bg_low_job_count = 13;
    public static final long BG_LOW_JOB_COUNT = 0x000001050000000dL;

    // optional int32 bg_critical_job_count = 14;
    public static final long BG_CRITICAL_JOB_COUNT = 0x000001050000000eL;

    // optional int32 max_standard_reschedule_count = 15;
    public static final long MAX_STANDARD_RESCHEDULE_COUNT = 0x000001050000000fL;

    // optional int32 max_work_reschedule_count = 16;
    public static final long MAX_WORK_RESCHEDULE_COUNT = 0x0000010500000010L;

    // optional int64 min_linear_backoff_time_ms = 17;
    public static final long MIN_LINEAR_BACKOFF_TIME_MS = 0x0000010300000011L;

    // optional int64 min_exp_backoff_time_ms = 18;
    public static final long MIN_EXP_BACKOFF_TIME_MS = 0x0000010300000012L;

    // optional int64 standby_heartbeat_time_ms = 19;
    public static final long STANDBY_HEARTBEAT_TIME_MS = 0x0000010300000013L;

    // repeated int32 standby_beats = 20;
    public static final long STANDBY_BEATS = 0x0000020500000014L;

    // optional double conn_congestion_delay_frac = 21;
    public static final long CONN_CONGESTION_DELAY_FRAC = 0x0000010100000015L;

    // optional double conn_prefetch_relax_frac = 22;
    public static final long CONN_PREFETCH_RELAX_FRAC = 0x0000010100000016L;

}

