// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/server/jobscheduler.proto

package com.android.server.job;

/** @hide */
// message JobStatusShortInfoProto
public final class JobStatusShortInfoProto {

    // optional int32 calling_uid = 1;
    public static final long CALLING_UID = 0x0000010500000001L;

    // optional int32 job_id = 2;
    public static final long JOB_ID = 0x0000010500000002L;

    // optional string battery_name = 3;
    public static final long BATTERY_NAME = 0x0000010900000003L;

}

