// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/server/jobscheduler.proto

package com.android.server.job;

/** @hide */
// message JobSchedulerServiceDumpProto
public final class JobSchedulerServiceDumpProto {

    // message RegisteredJob
    public final class RegisteredJob {

        // optional .com.android.server.job.JobStatusShortInfoProto info = 1;
        public static final long INFO = 0x0000010b00000001L;

        // optional .com.android.server.job.JobStatusDumpProto dump = 2;
        public static final long DUMP = 0x0000010b00000002L;

        // optional bool is_job_ready = 3;
        public static final long IS_JOB_READY = 0x0000010800000003L;

        // optional bool is_user_started = 4;
        public static final long IS_USER_STARTED = 0x0000010800000004L;

        // optional bool is_job_pending = 5;
        public static final long IS_JOB_PENDING = 0x0000010800000005L;

        // optional bool is_job_currently_active = 6;
        public static final long IS_JOB_CURRENTLY_ACTIVE = 0x0000010800000006L;

        // optional bool is_uid_backing_up = 7;
        public static final long IS_UID_BACKING_UP = 0x0000010800000007L;

        // optional bool is_component_present = 8;
        public static final long IS_COMPONENT_PRESENT = 0x0000010800000008L;

        // optional int64 last_run_heartbeat = 9;
        public static final long LAST_RUN_HEARTBEAT = 0x0000010300000009L;

    }

    // message PriorityOverride
    public final class PriorityOverride {

        // optional int32 uid = 1;
        public static final long UID = 0x0000010500000001L;

        // optional sint32 override_value = 2;
        public static final long OVERRIDE_VALUE = 0x0000011100000002L;

    }

    // message PendingJob
    public final class PendingJob {

        // optional .com.android.server.job.JobStatusShortInfoProto info = 1;
        public static final long INFO = 0x0000010b00000001L;

        // optional .com.android.server.job.JobStatusDumpProto dump = 2;
        public static final long DUMP = 0x0000010b00000002L;

        // optional sint32 evaluated_priority = 3;
        public static final long EVALUATED_PRIORITY = 0x0000011100000003L;

        // optional int64 enqueued_duration_ms = 4;
        public static final long ENQUEUED_DURATION_MS = 0x0000010300000004L;

    }

    // message ActiveJob
    public final class ActiveJob {

        // message InactiveJob
        public final class InactiveJob {

            // optional int64 time_since_stopped_ms = 1;
            public static final long TIME_SINCE_STOPPED_MS = 0x0000010300000001L;

            // optional string stopped_reason = 2;
            public static final long STOPPED_REASON = 0x0000010900000002L;

        }

        // message RunningJob
        public final class RunningJob {

            // optional .com.android.server.job.JobStatusShortInfoProto info = 1;
            public static final long INFO = 0x0000010b00000001L;

            // optional int64 running_duration_ms = 2;
            public static final long RUNNING_DURATION_MS = 0x0000010300000002L;

            // optional int64 time_until_timeout_ms = 3;
            public static final long TIME_UNTIL_TIMEOUT_MS = 0x0000010300000003L;

            // optional .com.android.server.job.JobStatusDumpProto dump = 4;
            public static final long DUMP = 0x0000010b00000004L;

            // optional sint32 evaluated_priority = 5;
            public static final long EVALUATED_PRIORITY = 0x0000011100000005L;

            // optional int64 time_since_made_active_ms = 6;
            public static final long TIME_SINCE_MADE_ACTIVE_MS = 0x0000010300000006L;

            // optional int64 pending_duration_ms = 7;
            public static final long PENDING_DURATION_MS = 0x0000010300000007L;

        }

        // optional .com.android.server.job.JobSchedulerServiceDumpProto.ActiveJob.InactiveJob inactive = 1;
        public static final long INACTIVE = 0x0000010b00000001L;

        // optional .com.android.server.job.JobSchedulerServiceDumpProto.ActiveJob.RunningJob running = 2;
        public static final long RUNNING = 0x0000010b00000002L;

    }

    // optional .com.android.server.job.ConstantsProto settings = 1;
    public static final long SETTINGS = 0x0000010b00000001L;

    // optional int32 current_heartbeat = 14;
    public static final long CURRENT_HEARTBEAT = 0x000001050000000eL;

    // repeated int32 next_heartbeat = 15;
    public static final long NEXT_HEARTBEAT = 0x000002050000000fL;

    // optional int64 last_heartbeat_time_millis = 16;
    public static final long LAST_HEARTBEAT_TIME_MILLIS = 0x0000010300000010L;

    // optional int64 next_heartbeat_time_millis = 17;
    public static final long NEXT_HEARTBEAT_TIME_MILLIS = 0x0000010300000011L;

    // optional bool in_parole = 18;
    public static final long IN_PAROLE = 0x0000010800000012L;

    // repeated int32 started_users = 2;
    public static final long STARTED_USERS = 0x0000020500000002L;

    // repeated .com.android.server.job.JobSchedulerServiceDumpProto.RegisteredJob registered_jobs = 3;
    public static final long REGISTERED_JOBS = 0x0000020b00000003L;

    // repeated .com.android.server.job.StateControllerProto controllers = 4;
    public static final long CONTROLLERS = 0x0000020b00000004L;

    // repeated .com.android.server.job.JobSchedulerServiceDumpProto.PriorityOverride priority_overrides = 5;
    public static final long PRIORITY_OVERRIDES = 0x0000020b00000005L;

    // repeated int32 backing_up_uids = 6;
    public static final long BACKING_UP_UIDS = 0x0000020500000006L;

    // optional .com.android.server.job.JobPackageHistoryProto history = 7;
    public static final long HISTORY = 0x0000010b00000007L;

    // optional .com.android.server.job.JobPackageTrackerDumpProto package_tracker = 8;
    public static final long PACKAGE_TRACKER = 0x0000010b00000008L;

    // repeated .com.android.server.job.JobSchedulerServiceDumpProto.PendingJob pending_jobs = 9;
    public static final long PENDING_JOBS = 0x0000020b00000009L;

    // repeated .com.android.server.job.JobSchedulerServiceDumpProto.ActiveJob active_jobs = 10;
    public static final long ACTIVE_JOBS = 0x0000020b0000000aL;

    // optional bool is_ready_to_rock = 11;
    public static final long IS_READY_TO_ROCK = 0x000001080000000bL;

    // optional bool reported_active = 12;
    public static final long REPORTED_ACTIVE = 0x000001080000000cL;

    // optional int32 max_active_jobs = 13;
    public static final long MAX_ACTIVE_JOBS = 0x000001050000000dL;

}

