// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/service/print.proto

package android.service.print;

/** @hide */
// message ResolutionProto
public final class ResolutionProto {

    // optional string id = 1;
    public static final long ID = 0x0000010900000001L;

    // optional string label = 2;
    public static final long LABEL = 0x0000010900000002L;

    // optional int32 horizontal_dpi = 3;
    public static final long HORIZONTAL_DPI = 0x0000010500000003L;

    // optional int32 vertical_dpi = 4;
    public static final long VERTICAL_DPI = 0x0000010500000004L;

}

