// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/cmds/am/proto/instrumentation_data.proto

package com.android.commands.am;

/** @hide */
public final class InstrumentationData {

    // enum SessionStatusCode
    public static final int SESSION_FINISHED = 0;
    public static final int SESSION_ABORTED = 1;

    // message ResultsBundleEntry
    public final class ResultsBundleEntry {

        // optional string key = 1;
        public static final long KEY = 0x0000010900000001L;

        // optional string value_string = 2;
        public static final long VALUE_STRING = 0x0000010900000002L;

        // optional sint32 value_int = 3;
        public static final long VALUE_INT = 0x0000011100000003L;

        // optional float value_float = 4;
        public static final long VALUE_FLOAT = 0x0000010200000004L;

        // optional double value_double = 5;
        public static final long VALUE_DOUBLE = 0x0000010100000005L;

        // optional sint64 value_long = 6;
        public static final long VALUE_LONG = 0x0000011200000006L;

        // optional .android.am.ResultsBundle value_bundle = 7;
        public static final long VALUE_BUNDLE = 0x0000010b00000007L;

        // optional bytes value_bytes = 8;
        public static final long VALUE_BYTES = 0x0000010c00000008L;

    }

    // message ResultsBundle
    public final class ResultsBundle {

        // repeated .android.am.ResultsBundleEntry entries = 1;
        public static final long ENTRIES = 0x0000020b00000001L;

    }

    // message TestStatus
    public final class TestStatus {

        // optional sint32 result_code = 3;
        public static final long RESULT_CODE = 0x0000011100000003L;

        // optional .android.am.ResultsBundle results = 4;
        public static final long RESULTS = 0x0000010b00000004L;

    }

    // message SessionStatus
    public final class SessionStatus {

        // optional .android.am.SessionStatusCode status_code = 1;
        public static final long STATUS_CODE = 0x0000010e00000001L;

        // optional string error_text = 2;
        public static final long ERROR_TEXT = 0x0000010900000002L;

        // optional sint32 result_code = 3;
        public static final long RESULT_CODE = 0x0000011100000003L;

        // optional .android.am.ResultsBundle results = 4;
        public static final long RESULTS = 0x0000010b00000004L;

    }

    // message Session
    public final class Session {

        // repeated .android.am.TestStatus test_status = 1;
        public static final long TEST_STATUS = 0x0000020b00000001L;

        // optional .android.am.SessionStatus session_status = 2;
        public static final long SESSION_STATUS = 0x0000010b00000002L;

    }

}
