// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/server/alarmmanagerservice.proto

package com.android.server;

/** @hide */
// message AlarmProto
public final class AlarmProto {

    // optional string tag = 1;
    public static final long TAG = 0x0000010900000001L;

    // optional .android.app.AlarmManagerProto.AlarmType type = 2;
    public static final long TYPE = 0x0000010e00000002L;

    // optional int64 time_until_when_elapsed_ms = 3;
    public static final long TIME_UNTIL_WHEN_ELAPSED_MS = 0x0000010300000003L;

    // optional int64 window_length_ms = 4;
    public static final long WINDOW_LENGTH_MS = 0x0000010300000004L;

    // optional int64 repeat_interval_ms = 5;
    public static final long REPEAT_INTERVAL_MS = 0x0000010300000005L;

    // optional int32 count = 6;
    public static final long COUNT = 0x0000010500000006L;

    // optional int32 flags = 7;
    public static final long FLAGS = 0x0000010500000007L;

    // optional .android.app.AlarmClockInfoProto alarm_clock = 8;
    public static final long ALARM_CLOCK = 0x0000010b00000008L;

    // optional .android.app.PendingIntentProto operation = 9;
    public static final long OPERATION = 0x0000010b00000009L;

    // optional string listener = 10;
    public static final long LISTENER = 0x000001090000000aL;

}

