// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/server/alarmmanagerservice.proto

package com.android.server;

/** @hide */
// message AlarmClockMetadataProto
public final class AlarmClockMetadataProto {

    // optional int32 user = 1;
    public static final long USER = 0x0000010500000001L;

    // optional bool is_pending_send = 2;
    public static final long IS_PENDING_SEND = 0x0000010800000002L;

    // optional int64 trigger_time_ms = 3;
    public static final long TRIGGER_TIME_MS = 0x0000010300000003L;

}

