// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/server/alarmmanagerservice.proto

package com.android.server;

/** @hide */
// message BroadcastStatsProto
public final class BroadcastStatsProto {

    // optional int32 uid = 1;
    public static final long UID = 0x0000010500000001L;

    // optional string package_name = 2;
    public static final long PACKAGE_NAME = 0x0000010900000002L;

    // optional int64 total_flight_duration_ms = 3;
    public static final long TOTAL_FLIGHT_DURATION_MS = 0x0000010300000003L;

    // optional int32 count = 4;
    public static final long COUNT = 0x0000010500000004L;

    // optional int32 wakeup_count = 5;
    public static final long WAKEUP_COUNT = 0x0000010500000005L;

    // optional int64 start_time_realtime = 6;
    public static final long START_TIME_REALTIME = 0x0000010300000006L;

    // optional int32 nesting = 7;
    public static final long NESTING = 0x0000010500000007L;

}

