// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/server/alarmmanagerservice.proto

package com.android.server;

/** @hide */
// message IdleDispatchEntryProto
public final class IdleDispatchEntryProto {

    // optional int32 uid = 1;
    public static final long UID = 0x0000010500000001L;

    // optional string pkg = 2;
    public static final long PKG = 0x0000010900000002L;

    // optional string tag = 3;
    public static final long TAG = 0x0000010900000003L;

    // optional string op = 4;
    public static final long OP = 0x0000010900000004L;

    // optional int64 entry_creation_realtime = 5;
    public static final long ENTRY_CREATION_REALTIME = 0x0000010300000005L;

    // optional int64 arg_realtime = 6;
    public static final long ARG_REALTIME = 0x0000010300000006L;

}

