// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/server/alarmmanagerservice.proto

package com.android.server;

/** @hide */
// message WakeupEventProto
public final class WakeupEventProto {

    // optional int32 uid = 1;
    public static final long UID = 0x0000010500000001L;

    // optional string action = 2;
    public static final long ACTION = 0x0000010900000002L;

    // optional int64 when = 3;
    public static final long WHEN = 0x0000010300000003L;

}

