// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/service/print.proto

package android.service.print;

/** @hide */
// message CachedPrintJobProto
public final class CachedPrintJobProto {

    // optional int32 app_id = 1;
    public static final long APP_ID = 0x0000010500000001L;

    // optional .android.service.print.PrintJobInfoProto print_job = 2;
    public static final long PRINT_JOB = 0x0000010b00000002L;

}

