// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/service/print.proto

package android.service.print;

/** @hide */
// message MarginsProto
public final class MarginsProto {

    // optional int32 top_mils = 1;
    public static final long TOP_MILS = 0x0000010500000001L;

    // optional int32 left_mils = 2;
    public static final long LEFT_MILS = 0x0000010500000002L;

    // optional int32 right_mils = 3;
    public static final long RIGHT_MILS = 0x0000010500000003L;

    // optional int32 bottom_mils = 4;
    public static final long BOTTOM_MILS = 0x0000010500000004L;

}

