// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/service/print.proto

package android.service.print;

/** @hide */
// message PrintServiceDumpProto
public final class PrintServiceDumpProto {

    // repeated .android.service.print.PrintUserStateProto userStates = 1;
    public static final long USER_STATES = 0x0000020b00000001L;

}

