// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/service/print.proto

package android.service.print;

/** @hide */
// message PrinterIdProto
public final class PrinterIdProto {

    // optional .android.content.ComponentNameProto service_name = 1;
    public static final long SERVICE_NAME = 0x0000010b00000001L;

    // optional string local_id = 2;
    public static final long LOCAL_ID = 0x0000010900000002L;

}

