// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/service/print.proto

package android.service.print;

/** @hide */
// message PrinterInfoProto
public final class PrinterInfoProto {

    // enum Status
    public static final int __STATUS_UNUSED = 0;
    public static final int STATUS_IDLE = 1;
    public static final int STATUS_BUSY = 2;
    public static final int STATUS_UNAVAILABLE = 3;

    // optional .android.service.print.PrinterIdProto id = 1;
    public static final long ID = 0x0000010b00000001L;

    // optional string name = 2;
    public static final long NAME = 0x0000010900000002L;

    // optional .android.service.print.PrinterInfoProto.Status status = 3;
    public static final long STATUS = 0x0000010e00000003L;

    // optional string description = 4;
    public static final long DESCRIPTION = 0x0000010900000004L;

    // optional .android.service.print.PrinterCapabilitiesProto capabilities = 5;
    public static final long CAPABILITIES = 0x0000010b00000005L;

}

