// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/service/print.proto

package android.service.print;

/** @hide */
// message PrintJobInfoProto
public final class PrintJobInfoProto {

    // enum State
    public static final int STATE_UNKNOWN = 0;
    public static final int STATE_CREATED = 1;
    public static final int STATE_QUEUED = 2;
    public static final int STATE_STARTED = 3;
    public static final int STATE_BLOCKED = 4;
    public static final int STATE_COMPLETED = 5;
    public static final int STATE_FAILED = 6;
    public static final int STATE_CANCELED = 7;

    // optional string label = 1;
    public static final long LABEL = 0x0000010900000001L;

    // optional string print_job_id = 2;
    public static final long PRINT_JOB_ID = 0x0000010900000002L;

    // optional .android.service.print.PrintJobInfoProto.State state = 3;
    public static final long STATE = 0x0000010e00000003L;

    // optional .android.service.print.PrinterIdProto printer = 4;
    public static final long PRINTER = 0x0000010b00000004L;

    // optional string tag = 5;
    public static final long TAG = 0x0000010900000005L;

    // optional int64 creation_time = 6;
    public static final long CREATION_TIME = 0x0000010300000006L;

    // optional .android.service.print.PrintAttributesProto attributes = 7;
    public static final long ATTRIBUTES = 0x0000010b00000007L;

    // optional .android.service.print.PrintDocumentInfoProto document_info = 8;
    public static final long DOCUMENT_INFO = 0x0000010b00000008L;

    // optional bool is_canceling = 9;
    public static final long IS_CANCELING = 0x0000010800000009L;

    // repeated .android.service.print.PageRangeProto pages = 10;
    public static final long PAGES = 0x0000020b0000000aL;

    // optional bool has_advanced_options = 11;
    public static final long HAS_ADVANCED_OPTIONS = 0x000001080000000bL;

    // optional float progress = 12;
    public static final long PROGRESS = 0x000001020000000cL;

    // optional string status = 13;
    public static final long STATUS = 0x000001090000000dL;

}

