// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/service/print.proto

package android.service.print;

/** @hide */
// message PrintDocumentInfoProto
public final class PrintDocumentInfoProto {

    // optional string name = 1;
    public static final long NAME = 0x0000010900000001L;

    // optional int32 page_count = 2;
    public static final long PAGE_COUNT = 0x0000010500000002L;

    // optional int32 content_type = 3;
    public static final long CONTENT_TYPE = 0x0000010500000003L;

    // optional int64 data_size = 4;
    public static final long DATA_SIZE = 0x0000010300000004L;

}

