// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/service/print.proto

package android.service.print;

/** @hide */
// message PrinterCapabilitiesProto
public final class PrinterCapabilitiesProto {

    // optional .android.service.print.MarginsProto min_margins = 1;
    public static final long MIN_MARGINS = 0x0000010b00000001L;

    // repeated .android.service.print.MediaSizeProto media_sizes = 2;
    public static final long MEDIA_SIZES = 0x0000020b00000002L;

    // repeated .android.service.print.ResolutionProto resolutions = 3;
    public static final long RESOLUTIONS = 0x0000020b00000003L;

    // repeated .android.service.print.PrintAttributesProto.ColorMode color_modes = 4;
    public static final long COLOR_MODES = 0x0000020e00000004L;

    // repeated .android.service.print.PrintAttributesProto.DuplexMode duplex_modes = 5;
    public static final long DUPLEX_MODES = 0x0000020e00000005L;

}

