// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/server/fingerprint.proto

package com.android.server.fingerprint;

/** @hide */
// message FingerprintServiceDumpProto
public final class FingerprintServiceDumpProto {

    // repeated .com.android.server.fingerprint.FingerprintUserStatsProto users = 1;
    public static final long USERS = 0x0000020b00000001L;

}

