// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/server/fingerprint.proto

package com.android.server.fingerprint;

/** @hide */
// message FingerprintUserStatsProto
public final class FingerprintUserStatsProto {

    // optional int32 user_id = 1;
    public static final long USER_ID = 0x0000010500000001L;

    // optional int32 num_fingerprints = 2;
    public static final long NUM_FINGERPRINTS = 0x0000010500000002L;

    // optional .com.android.server.fingerprint.PerformanceStatsProto normal = 3;
    public static final long NORMAL = 0x0000010b00000003L;

    // optional .com.android.server.fingerprint.PerformanceStatsProto crypto = 4;
    public static final long CRYPTO = 0x0000010b00000004L;

}

