// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/server/fingerprint.proto

package com.android.server.fingerprint;

/** @hide */
// message PerformanceStatsProto
public final class PerformanceStatsProto {

    // optional int32 accept = 1;
    public static final long ACCEPT = 0x0000010500000001L;

    // optional int32 reject = 2;
    public static final long REJECT = 0x0000010500000002L;

    // optional int32 acquire = 3;
    public static final long ACQUIRE = 0x0000010500000003L;

    // optional int32 lockout = 4;
    public static final long LOCKOUT = 0x0000010500000004L;

    // optional int32 permanent_lockout = 5;
    public static final long PERMANENT_LOCKOUT = 0x0000010500000005L;

}

