// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/libs/incident/proto/android/privacy.proto

package com.android.incident;

/** @hide */
// message PrivacyFlags
public final class PrivacyFlags {

    // optional .android.Destination dest = 1;
    public static final long DEST = 0x0000010e00000001L;

    // repeated string patterns = 2;
    public static final long PATTERNS = 0x0000020900000002L;

}

