// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/libs/incident/proto/android/privacy.proto

package com.android.incident;

/** @hide */
public final class Privacy {

    // enum Destination
    public static final int DEST_LOCAL = 0;
    public static final int DEST_EXPLICIT = 100;
    public static final int DEST_AUTOMATIC = 200;
    public static final int DEST_UNSET = 255;

}
