// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/server/activitymanagerservice.proto

package com.android.server.am;

/** @hide */
// message ImportanceTokenProto
public final class ImportanceTokenProto {

    // optional int32 pid = 1;
    public static final long PID = 0x0000010500000001L;

    // optional string token = 2;
    public static final long TOKEN = 0x0000010900000002L;

    // optional string reason = 3;
    public static final long REASON = 0x0000010900000003L;

}

