// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/server/activitymanagerservice.proto

package com.android.server.am;

/** @hide */
// message KeyguardControllerProto
public final class KeyguardControllerProto {

    // optional bool keyguard_showing = 1;
    public static final long KEYGUARD_SHOWING = 0x0000010800000001L;

    // optional bool keyguard_occluded = 2;
    public static final long KEYGUARD_OCCLUDED = 0x0000010800000002L;

}

