// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/service/notification.proto

package android.service.notification;

/** @hide */
// message ConditionProto
public final class ConditionProto {

    // enum State
    public static final int STATE_FALSE = 0;
    public static final int STATE_TRUE = 1;
    public static final int STATE_UNKNOWN = 2;
    public static final int STATE_ERROR = 3;

    // optional string id = 1;
    public static final long ID = 0x0000010900000001L;

    // optional string summary = 2;
    public static final long SUMMARY = 0x0000010900000002L;

    // optional string line_1 = 3;
    public static final long LINE_1 = 0x0000010900000003L;

    // optional string line_2 = 4;
    public static final long LINE_2 = 0x0000010900000004L;

    // optional int32 icon = 5;
    public static final long ICON = 0x0000010500000005L;

    // optional .android.service.notification.ConditionProto.State state = 6;
    public static final long STATE = 0x0000010e00000006L;

    // optional int32 flags = 7;
    public static final long FLAGS = 0x0000010500000007L;

}

