// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/service/notification.proto

package android.service.notification;

/** @hide */
// message ManagedServicesProto
public final class ManagedServicesProto {

    // message ServiceProto
    public final class ServiceProto {

        // repeated string name = 1;
        public static final long NAME = 0x0000020900000001L;

        // optional int32 user_id = 2;
        public static final long USER_ID = 0x0000010500000002L;

        // optional bool is_primary = 3;
        public static final long IS_PRIMARY = 0x0000010800000003L;

    }

    // optional string caption = 1;
    public static final long CAPTION = 0x0000010900000001L;

    // repeated .android.service.notification.ManagedServicesProto.ServiceProto approved = 2;
    public static final long APPROVED = 0x0000020b00000002L;

    // repeated .android.content.ComponentNameProto enabled = 3;
    public static final long ENABLED = 0x0000020b00000003L;

    // repeated .android.service.notification.ManagedServiceInfoProto live_services = 4;
    public static final long LIVE_SERVICES = 0x0000020b00000004L;

    // repeated .android.content.ComponentNameProto snoozed = 5;
    public static final long SNOOZED = 0x0000020b00000005L;

}

