// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/service/notification.proto

package android.service.notification;

/** @hide */
// message ManagedServiceInfoProto
public final class ManagedServiceInfoProto {

    // optional .android.content.ComponentNameProto component = 1;
    public static final long COMPONENT = 0x0000010b00000001L;

    // optional int32 user_id = 2;
    public static final long USER_ID = 0x0000010500000002L;

    // optional string service = 3;
    public static final long SERVICE = 0x0000010900000003L;

    // optional bool is_system = 4;
    public static final long IS_SYSTEM = 0x0000010800000004L;

    // optional bool is_guest = 5;
    public static final long IS_GUEST = 0x0000010800000005L;

}

