// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/service/notification.proto

package android.service.notification;

/** @hide */
// message ZenModeProto
public final class ZenModeProto {

    // optional .android.service.notification.ZenMode zen_mode = 1;
    public static final long ZEN_MODE = 0x0000010e00000001L;

    // repeated .android.service.notification.ZenRuleProto enabled_active_conditions = 2;
    public static final long ENABLED_ACTIVE_CONDITIONS = 0x0000020b00000002L;

    // optional int32 suppressed_effects = 3;
    public static final long SUPPRESSED_EFFECTS = 0x0000010500000003L;

    // repeated .android.content.ComponentNameProto suppressors = 4;
    public static final long SUPPRESSORS = 0x0000020b00000004L;

    // optional .android.app.PolicyProto policy = 5;
    public static final long POLICY = 0x0000010b00000005L;

}

