// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/server/activitymanagerservice.proto

package com.android.server.am;

/** @hide */
// message ActivityManagerServiceDumpServicesProto
public final class ActivityManagerServiceDumpServicesProto {

    // optional .com.android.server.am.ActiveServicesProto active_services = 1;
    public static final long ACTIVE_SERVICES = 0x0000010b00000001L;

}

