// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/server/activitymanagerservice.proto

package com.android.server.am;

/** @hide */
// message ActivityManagerServiceDumpBroadcastsProto
public final class ActivityManagerServiceDumpBroadcastsProto {

    // message MainHandler
    public final class MainHandler {

        // optional string handler = 1;
        public static final long HANDLER = 0x0000010900000001L;

        // optional .android.os.LooperProto looper = 2;
        public static final long LOOPER = 0x0000010b00000002L;

    }

    // repeated .com.android.server.am.ReceiverListProto receiver_list = 1;
    public static final long RECEIVER_LIST = 0x0000020b00000001L;

    // optional .com.android.server.IntentResolverProto receiver_resolver = 2;
    public static final long RECEIVER_RESOLVER = 0x0000010b00000002L;

    // repeated .com.android.server.am.BroadcastQueueProto broadcast_queue = 3;
    public static final long BROADCAST_QUEUE = 0x0000020b00000003L;

    // repeated .com.android.server.am.StickyBroadcastProto sticky_broadcasts = 4;
    public static final long STICKY_BROADCASTS = 0x0000020b00000004L;

    // optional .com.android.server.am.ActivityManagerServiceDumpBroadcastsProto.MainHandler handler = 5;
    public static final long HANDLER = 0x0000010b00000005L;

}

