// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/server/activitymanagerservice.proto

package com.android.server.am;

/** @hide */
// message AppTimeTrackerProto
public final class AppTimeTrackerProto {

    // message PackageTime
    public final class PackageTime {

        // optional string package = 1;
        public static final long PACKAGE = 0x0000010900000001L;

        // optional int64 duration_ms = 2;
        public static final long DURATION_MS = 0x0000010300000002L;

    }

    // optional string receiver = 1;
    public static final long RECEIVER = 0x0000010900000001L;

    // optional int64 total_duration_ms = 2;
    public static final long TOTAL_DURATION_MS = 0x0000010300000002L;

    // repeated .com.android.server.am.AppTimeTrackerProto.PackageTime package_times = 3;
    public static final long PACKAGE_TIMES = 0x0000020b00000003L;

    // optional .android.util.Duration started_time = 4;
    public static final long STARTED_TIME = 0x0000010b00000004L;

    // optional string started_package = 5;
    public static final long STARTED_PACKAGE = 0x0000010900000005L;

}

