// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/server/activitymanagerservice.proto

package com.android.server.am;

/** @hide */
// message BroadcastFilterProto
public final class BroadcastFilterProto {

    // optional .android.content.IntentFilterProto intent_filter = 1;
    public static final long INTENT_FILTER = 0x0000010b00000001L;

    // optional string required_permission = 2;
    public static final long REQUIRED_PERMISSION = 0x0000010900000002L;

    // optional string hex_hash = 3;
    public static final long HEX_HASH = 0x0000010900000003L;

    // optional int32 owning_user_id = 4;
    public static final long OWNING_USER_ID = 0x0000010500000004L;

}

