// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/server/activitymanagerservice.proto

package com.android.server.am;

/** @hide */
// message MemInfoDumpProto
public final class MemInfoDumpProto {

    // message ProcessMemory
    public final class ProcessMemory {

        // message MemoryInfo
        public final class MemoryInfo {

            // optional string name = 1;
            public static final long NAME = 0x0000010900000001L;

            // optional int32 total_pss_kb = 2;
            public static final long TOTAL_PSS_KB = 0x0000010500000002L;

            // optional int32 clean_pss_kb = 3;
            public static final long CLEAN_PSS_KB = 0x0000010500000003L;

            // optional int32 shared_dirty_kb = 4;
            public static final long SHARED_DIRTY_KB = 0x0000010500000004L;

            // optional int32 private_dirty_kb = 5;
            public static final long PRIVATE_DIRTY_KB = 0x0000010500000005L;

            // optional int32 shared_clean_kb = 6;
            public static final long SHARED_CLEAN_KB = 0x0000010500000006L;

            // optional int32 private_clean_kb = 7;
            public static final long PRIVATE_CLEAN_KB = 0x0000010500000007L;

            // optional int32 dirty_swap_kb = 8;
            public static final long DIRTY_SWAP_KB = 0x0000010500000008L;

            // optional int32 dirty_swap_pss_kb = 9;
            public static final long DIRTY_SWAP_PSS_KB = 0x0000010500000009L;

        }

        // message HeapInfo
        public final class HeapInfo {

            // optional .com.android.server.am.MemInfoDumpProto.ProcessMemory.MemoryInfo mem_info = 1;
            public static final long MEM_INFO = 0x0000010b00000001L;

            // optional int32 heap_size_kb = 2;
            public static final long HEAP_SIZE_KB = 0x0000010500000002L;

            // optional int32 heap_alloc_kb = 3;
            public static final long HEAP_ALLOC_KB = 0x0000010500000003L;

            // optional int32 heap_free_kb = 4;
            public static final long HEAP_FREE_KB = 0x0000010500000004L;

        }

        // message AppSummary
        public final class AppSummary {

            // optional int32 java_heap_pss_kb = 1;
            public static final long JAVA_HEAP_PSS_KB = 0x0000010500000001L;

            // optional int32 native_heap_pss_kb = 2;
            public static final long NATIVE_HEAP_PSS_KB = 0x0000010500000002L;

            // optional int32 code_pss_kb = 3;
            public static final long CODE_PSS_KB = 0x0000010500000003L;

            // optional int32 stack_pss_kb = 4;
            public static final long STACK_PSS_KB = 0x0000010500000004L;

            // optional int32 graphics_pss_kb = 5;
            public static final long GRAPHICS_PSS_KB = 0x0000010500000005L;

            // optional int32 private_other_pss_kb = 6;
            public static final long PRIVATE_OTHER_PSS_KB = 0x0000010500000006L;

            // optional int32 system_pss_kb = 7;
            public static final long SYSTEM_PSS_KB = 0x0000010500000007L;

            // optional int32 total_swap_pss = 8;
            public static final long TOTAL_SWAP_PSS = 0x0000010500000008L;

            // optional int32 total_swap_kb = 9;
            public static final long TOTAL_SWAP_KB = 0x0000010500000009L;

        }

        // optional int32 pid = 1;
        public static final long PID = 0x0000010500000001L;

        // optional string process_name = 2;
        public static final long PROCESS_NAME = 0x0000010900000002L;

        // optional .com.android.server.am.MemInfoDumpProto.ProcessMemory.HeapInfo native_heap = 3;
        public static final long NATIVE_HEAP = 0x0000010b00000003L;

        // optional .com.android.server.am.MemInfoDumpProto.ProcessMemory.HeapInfo dalvik_heap = 4;
        public static final long DALVIK_HEAP = 0x0000010b00000004L;

        // repeated .com.android.server.am.MemInfoDumpProto.ProcessMemory.MemoryInfo other_heaps = 5;
        public static final long OTHER_HEAPS = 0x0000020b00000005L;

        // optional .com.android.server.am.MemInfoDumpProto.ProcessMemory.MemoryInfo unknown_heap = 6;
        public static final long UNKNOWN_HEAP = 0x0000010b00000006L;

        // optional .com.android.server.am.MemInfoDumpProto.ProcessMemory.HeapInfo total_heap = 7;
        public static final long TOTAL_HEAP = 0x0000010b00000007L;

        // repeated .com.android.server.am.MemInfoDumpProto.ProcessMemory.MemoryInfo dalvik_details = 8;
        public static final long DALVIK_DETAILS = 0x0000020b00000008L;

        // optional .com.android.server.am.MemInfoDumpProto.ProcessMemory.AppSummary app_summary = 9;
        public static final long APP_SUMMARY = 0x0000010b00000009L;

    }

    // message AppData
    public final class AppData {

        // message ObjectStats
        public final class ObjectStats {

            // optional int32 view_instance_count = 1;
            public static final long VIEW_INSTANCE_COUNT = 0x0000010500000001L;

            // optional int32 view_root_instance_count = 2;
            public static final long VIEW_ROOT_INSTANCE_COUNT = 0x0000010500000002L;

            // optional int32 app_context_instance_count = 3;
            public static final long APP_CONTEXT_INSTANCE_COUNT = 0x0000010500000003L;

            // optional int32 activity_instance_count = 4;
            public static final long ACTIVITY_INSTANCE_COUNT = 0x0000010500000004L;

            // optional int32 global_asset_count = 5;
            public static final long GLOBAL_ASSET_COUNT = 0x0000010500000005L;

            // optional int32 global_asset_manager_count = 6;
            public static final long GLOBAL_ASSET_MANAGER_COUNT = 0x0000010500000006L;

            // optional int32 local_binder_object_count = 7;
            public static final long LOCAL_BINDER_OBJECT_COUNT = 0x0000010500000007L;

            // optional int32 proxy_binder_object_count = 8;
            public static final long PROXY_BINDER_OBJECT_COUNT = 0x0000010500000008L;

            // optional int64 parcel_memory_kb = 9;
            public static final long PARCEL_MEMORY_KB = 0x0000010300000009L;

            // optional int32 parcel_count = 10;
            public static final long PARCEL_COUNT = 0x000001050000000aL;

            // optional int32 binder_object_death_count = 11;
            public static final long BINDER_OBJECT_DEATH_COUNT = 0x000001050000000bL;

            // optional int32 open_ssl_socket_count = 12;
            public static final long OPEN_SSL_SOCKET_COUNT = 0x000001050000000cL;

            // optional int32 webview_instance_count = 13;
            public static final long WEBVIEW_INSTANCE_COUNT = 0x000001050000000dL;

        }

        // message SqlStats
        public final class SqlStats {

            // message Database
            public final class Database {

                // optional string name = 1;
                public static final long NAME = 0x0000010900000001L;

                // optional int32 page_size = 2;
                public static final long PAGE_SIZE = 0x0000010500000002L;

                // optional int32 db_size = 3;
                public static final long DB_SIZE = 0x0000010500000003L;

                // optional int32 lookaside_b = 4;
                public static final long LOOKASIDE_B = 0x0000010500000004L;

                // optional string cache = 5;
                public static final long CACHE = 0x0000010900000005L;

            }

            // optional int32 memory_used_kb = 1;
            public static final long MEMORY_USED_KB = 0x0000010500000001L;

            // optional int32 pagecache_overflow_kb = 2;
            public static final long PAGECACHE_OVERFLOW_KB = 0x0000010500000002L;

            // optional int32 malloc_size_kb = 3;
            public static final long MALLOC_SIZE_KB = 0x0000010500000003L;

            // repeated .com.android.server.am.MemInfoDumpProto.AppData.SqlStats.Database databases = 4;
            public static final long DATABASES = 0x0000020b00000004L;

        }

        // optional .com.android.server.am.MemInfoDumpProto.ProcessMemory process_memory = 1;
        public static final long PROCESS_MEMORY = 0x0000010b00000001L;

        // optional .com.android.server.am.MemInfoDumpProto.AppData.ObjectStats objects = 2;
        public static final long OBJECTS = 0x0000010b00000002L;

        // optional .com.android.server.am.MemInfoDumpProto.AppData.SqlStats sql = 3;
        public static final long SQL = 0x0000010b00000003L;

        // optional string asset_allocations = 4;
        public static final long ASSET_ALLOCATIONS = 0x0000010900000004L;

        // optional string unreachable_memory = 5;
        public static final long UNREACHABLE_MEMORY = 0x0000010900000005L;

    }

    // message MemItem
    public final class MemItem {

        // optional string tag = 1;
        public static final long TAG = 0x0000010900000001L;

        // optional string label = 2;
        public static final long LABEL = 0x0000010900000002L;

        // optional int32 id = 3;
        public static final long ID = 0x0000010500000003L;

        // optional bool is_proc = 4;
        public static final long IS_PROC = 0x0000010800000004L;

        // optional bool has_activities = 5;
        public static final long HAS_ACTIVITIES = 0x0000010800000005L;

        // optional int64 pss_kb = 6;
        public static final long PSS_KB = 0x0000010300000006L;

        // optional int64 swap_pss_kb = 7;
        public static final long SWAP_PSS_KB = 0x0000010300000007L;

        // repeated .com.android.server.am.MemInfoDumpProto.MemItem sub_items = 8;
        public static final long SUB_ITEMS = 0x0000020b00000008L;

    }

    // optional int64 uptime_duration_ms = 1;
    public static final long UPTIME_DURATION_MS = 0x0000010300000001L;

    // optional int64 elapsed_realtime_ms = 2;
    public static final long ELAPSED_REALTIME_MS = 0x0000010300000002L;

    // repeated .com.android.server.am.MemInfoDumpProto.ProcessMemory native_processes = 3;
    public static final long NATIVE_PROCESSES = 0x0000020b00000003L;

    // repeated .com.android.server.am.MemInfoDumpProto.AppData app_processes = 4;
    public static final long APP_PROCESSES = 0x0000020b00000004L;

    // repeated .com.android.server.am.MemInfoDumpProto.MemItem total_pss_by_process = 5;
    public static final long TOTAL_PSS_BY_PROCESS = 0x0000020b00000005L;

    // repeated .com.android.server.am.MemInfoDumpProto.MemItem total_pss_by_oom_adjustment = 6;
    public static final long TOTAL_PSS_BY_OOM_ADJUSTMENT = 0x0000020b00000006L;

    // repeated .com.android.server.am.MemInfoDumpProto.MemItem total_pss_by_category = 7;
    public static final long TOTAL_PSS_BY_CATEGORY = 0x0000020b00000007L;

    // optional int64 total_ram_kb = 8;
    public static final long TOTAL_RAM_KB = 0x0000010300000008L;

    // optional .com.android.internal.app.procstats.ProcessStatsProto.MemoryFactor status = 9;
    public static final long STATUS = 0x0000010e00000009L;

    // optional int64 cached_pss_kb = 10;
    public static final long CACHED_PSS_KB = 0x000001030000000aL;

    // optional int64 cached_kernel_kb = 11;
    public static final long CACHED_KERNEL_KB = 0x000001030000000bL;

    // optional int64 free_kb = 12;
    public static final long FREE_KB = 0x000001030000000cL;

    // optional int64 used_pss_kb = 13;
    public static final long USED_PSS_KB = 0x000001030000000dL;

    // optional int64 used_kernel_kb = 14;
    public static final long USED_KERNEL_KB = 0x000001030000000eL;

    // optional int64 lost_ram_kb = 15;
    public static final long LOST_RAM_KB = 0x000001030000000fL;

    // optional int64 total_zram_kb = 16;
    public static final long TOTAL_ZRAM_KB = 0x0000010300000010L;

    // optional int64 zram_physical_used_in_swap_kb = 17;
    public static final long ZRAM_PHYSICAL_USED_IN_SWAP_KB = 0x0000010300000011L;

    // optional int64 total_zram_swap_kb = 18;
    public static final long TOTAL_ZRAM_SWAP_KB = 0x0000010300000012L;

    // optional int64 ksm_sharing_kb = 19;
    public static final long KSM_SHARING_KB = 0x0000010300000013L;

    // optional int64 ksm_shared_kb = 20;
    public static final long KSM_SHARED_KB = 0x0000010300000014L;

    // optional int64 ksm_unshared_kb = 21;
    public static final long KSM_UNSHARED_KB = 0x0000010300000015L;

    // optional int64 ksm_volatile_kb = 22;
    public static final long KSM_VOLATILE_KB = 0x0000010300000016L;

    // optional int32 tuning_mb = 23;
    public static final long TUNING_MB = 0x0000010500000017L;

    // optional int32 tuning_large_mb = 24;
    public static final long TUNING_LARGE_MB = 0x0000010500000018L;

    // optional int64 oom_kb = 25;
    public static final long OOM_KB = 0x0000010300000019L;

    // optional int64 restore_limit_kb = 26;
    public static final long RESTORE_LIMIT_KB = 0x000001030000001aL;

    // optional bool is_low_ram_device = 27;
    public static final long IS_LOW_RAM_DEVICE = 0x000001080000001bL;

    // optional bool is_high_end_gfx = 28;
    public static final long IS_HIGH_END_GFX = 0x000001080000001cL;

}

