// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/server/activitymanagerservice.proto

package com.android.server.am;

/** @hide */
// message ProcessRecordProto
public final class ProcessRecordProto {

    // optional int32 pid = 1;
    public static final long PID = 0x0000010500000001L;

    // optional string process_name = 2;
    public static final long PROCESS_NAME = 0x0000010900000002L;

    // optional int32 uid = 3;
    public static final long UID = 0x0000010500000003L;

    // optional int32 user_id = 4;
    public static final long USER_ID = 0x0000010500000004L;

    // optional int32 app_id = 5;
    public static final long APP_ID = 0x0000010500000005L;

    // optional int32 isolated_app_id = 6;
    public static final long ISOLATED_APP_ID = 0x0000010500000006L;

    // optional bool persistent = 7;
    public static final long PERSISTENT = 0x0000010800000007L;

}

