// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/server/activitymanagerservice.proto

package com.android.server.am;

/** @hide */
// message ProcessToGcProto
public final class ProcessToGcProto {

    // optional .com.android.server.am.ProcessRecordProto proc = 1;
    public static final long PROC = 0x0000010b00000001L;

    // optional bool report_low_memory = 2;
    public static final long REPORT_LOW_MEMORY = 0x0000010800000002L;

    // optional int64 now_uptime_ms = 3;
    public static final long NOW_UPTIME_MS = 0x0000010300000003L;

    // optional int64 last_gced_ms = 4;
    public static final long LAST_GCED_MS = 0x0000010300000004L;

    // optional int64 last_low_memory_ms = 5;
    public static final long LAST_LOW_MEMORY_MS = 0x0000010300000005L;

}

