// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/server/activitymanagerservice.proto

package com.android.server.am;

/** @hide */
// message ServiceRecordProto
public final class ServiceRecordProto {

    // message AppInfo
    public final class AppInfo {

        // optional string base_dir = 1;
        public static final long BASE_DIR = 0x0000010900000001L;

        // optional string res_dir = 2;
        public static final long RES_DIR = 0x0000010900000002L;

        // optional string data_dir = 3;
        public static final long DATA_DIR = 0x0000010900000003L;

    }

    // message Foreground
    public final class Foreground {

        // optional int32 id = 1;
        public static final long ID = 0x0000010500000001L;

        // optional .android.app.NotificationProto notification = 2;
        public static final long NOTIFICATION = 0x0000010b00000002L;

    }

    // message Start
    public final class Start {

        // optional bool start_requested = 1;
        public static final long START_REQUESTED = 0x0000010800000001L;

        // optional bool delayed_stop = 2;
        public static final long DELAYED_STOP = 0x0000010800000002L;

        // optional bool stop_if_killed = 3;
        public static final long STOP_IF_KILLED = 0x0000010800000003L;

        // optional bool call_start = 4;
        public static final long CALL_START = 0x0000010800000004L;

        // optional int32 last_start_id = 5;
        public static final long LAST_START_ID = 0x0000010500000005L;

    }

    // message ExecuteNesting
    public final class ExecuteNesting {

        // optional int32 execute_nesting = 1;
        public static final long EXECUTE_NESTING = 0x0000010500000001L;

        // optional bool execute_fg = 2;
        public static final long EXECUTE_FG = 0x0000010800000002L;

        // optional .android.util.Duration executing_start = 3;
        public static final long EXECUTING_START = 0x0000010b00000003L;

    }

    // message Crash
    public final class Crash {

        // optional int32 restart_count = 1;
        public static final long RESTART_COUNT = 0x0000010500000001L;

        // optional .android.util.Duration restart_delay = 2;
        public static final long RESTART_DELAY = 0x0000010b00000002L;

        // optional .android.util.Duration next_restart_time = 3;
        public static final long NEXT_RESTART_TIME = 0x0000010b00000003L;

        // optional int32 crash_count = 4;
        public static final long CRASH_COUNT = 0x0000010500000004L;

    }

    // message StartItem
    public final class StartItem {

        // optional int32 id = 1;
        public static final long ID = 0x0000010500000001L;

        // optional .android.util.Duration duration = 2;
        public static final long DURATION = 0x0000010b00000002L;

        // optional int32 delivery_count = 3;
        public static final long DELIVERY_COUNT = 0x0000010500000003L;

        // optional int32 done_executing_count = 4;
        public static final long DONE_EXECUTING_COUNT = 0x0000010500000004L;

        // optional .android.content.IntentProto intent = 5;
        public static final long INTENT = 0x0000010b00000005L;

        // optional .com.android.server.am.NeededUriGrantsProto needed_grants = 6;
        public static final long NEEDED_GRANTS = 0x0000010b00000006L;

        // optional .com.android.server.am.UriPermissionOwnerProto uri_permissions = 7;
        public static final long URI_PERMISSIONS = 0x0000010b00000007L;

    }

    // optional string short_name = 1;
    public static final long SHORT_NAME = 0x0000010900000001L;

    // optional bool is_running = 2;
    public static final long IS_RUNNING = 0x0000010800000002L;

    // optional int32 pid = 3;
    public static final long PID = 0x0000010500000003L;

    // optional .android.content.IntentProto intent = 4;
    public static final long INTENT = 0x0000010b00000004L;

    // optional string package_name = 5;
    public static final long PACKAGE_NAME = 0x0000010900000005L;

    // optional string process_name = 6;
    public static final long PROCESS_NAME = 0x0000010900000006L;

    // optional string permission = 7;
    public static final long PERMISSION = 0x0000010900000007L;

    // optional .com.android.server.am.ServiceRecordProto.AppInfo appinfo = 8;
    public static final long APPINFO = 0x0000010b00000008L;

    // optional .com.android.server.am.ProcessRecordProto app = 9;
    public static final long APP = 0x0000010b00000009L;

    // optional .com.android.server.am.ProcessRecordProto isolated_proc = 10;
    public static final long ISOLATED_PROC = 0x0000010b0000000aL;

    // optional bool whitelist_manager = 11;
    public static final long WHITELIST_MANAGER = 0x000001080000000bL;

    // optional bool delayed = 12;
    public static final long DELAYED = 0x000001080000000cL;

    // optional .com.android.server.am.ServiceRecordProto.Foreground foreground = 13;
    public static final long FOREGROUND = 0x0000010b0000000dL;

    // optional .android.util.Duration create_real_time = 14;
    public static final long CREATE_REAL_TIME = 0x0000010b0000000eL;

    // optional .android.util.Duration starting_bg_timeout = 15;
    public static final long STARTING_BG_TIMEOUT = 0x0000010b0000000fL;

    // optional .android.util.Duration last_activity_time = 16;
    public static final long LAST_ACTIVITY_TIME = 0x0000010b00000010L;

    // optional .android.util.Duration restart_time = 17;
    public static final long RESTART_TIME = 0x0000010b00000011L;

    // optional bool created_from_fg = 18;
    public static final long CREATED_FROM_FG = 0x0000010800000012L;

    // optional .com.android.server.am.ServiceRecordProto.Start start = 19;
    public static final long START = 0x0000010b00000013L;

    // optional .com.android.server.am.ServiceRecordProto.ExecuteNesting execute = 20;
    public static final long EXECUTE = 0x0000010b00000014L;

    // optional .android.util.Duration destory_time = 21;
    public static final long DESTORY_TIME = 0x0000010b00000015L;

    // optional .com.android.server.am.ServiceRecordProto.Crash crash = 22;
    public static final long CRASH = 0x0000010b00000016L;

    // repeated .com.android.server.am.ServiceRecordProto.StartItem delivered_starts = 23;
    public static final long DELIVERED_STARTS = 0x0000020b00000017L;

    // repeated .com.android.server.am.ServiceRecordProto.StartItem pending_starts = 24;
    public static final long PENDING_STARTS = 0x0000020b00000018L;

    // repeated .com.android.server.am.IntentBindRecordProto bindings = 25;
    public static final long BINDINGS = 0x0000020b00000019L;

    // repeated .com.android.server.am.ConnectionRecordProto connections = 26;
    public static final long CONNECTIONS = 0x0000020b0000001aL;

}

