// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/server/activitymanagerservice.proto

package com.android.server.am;

/** @hide */
// message TaskRecordProto
public final class TaskRecordProto {

    // optional .com.android.server.wm.ConfigurationContainerProto configuration_container = 1;
    public static final long CONFIGURATION_CONTAINER = 0x0000010b00000001L;

    // optional int32 id = 2;
    public static final long ID = 0x0000010500000002L;

    // repeated .com.android.server.am.ActivityRecordProto activities = 3;
    public static final long ACTIVITIES = 0x0000020b00000003L;

    // optional int32 stack_id = 4;
    public static final long STACK_ID = 0x0000010500000004L;

    // optional .android.graphics.RectProto last_non_fullscreen_bounds = 5;
    public static final long LAST_NON_FULLSCREEN_BOUNDS = 0x0000010b00000005L;

    // optional string real_activity = 6;
    public static final long REAL_ACTIVITY = 0x0000010900000006L;

    // optional string orig_activity = 7;
    public static final long ORIG_ACTIVITY = 0x0000010900000007L;

    // optional int32 activity_type = 8;
    public static final long ACTIVITY_TYPE = 0x0000010500000008L;

    // optional int32 resize_mode = 9;
    public static final long RESIZE_MODE = 0x0000010500000009L;

    // optional bool fullscreen = 10;
    public static final long FULLSCREEN = 0x000001080000000aL;

    // optional .android.graphics.RectProto bounds = 11;
    public static final long BOUNDS = 0x0000010b0000000bL;

    // optional int32 min_width = 12;
    public static final long MIN_WIDTH = 0x000001050000000cL;

    // optional int32 min_height = 13;
    public static final long MIN_HEIGHT = 0x000001050000000dL;

}

