// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/server/activitymanagerservice.proto

package com.android.server.am;

/** @hide */
// message UriPermissionOwnerProto
public final class UriPermissionOwnerProto {

    // optional string owner = 1;
    public static final long OWNER = 0x0000010900000001L;

    // repeated .com.android.server.am.GrantUriProto read_perms = 2;
    public static final long READ_PERMS = 0x0000020b00000002L;

    // repeated .com.android.server.am.GrantUriProto write_perms = 3;
    public static final long WRITE_PERMS = 0x0000020b00000003L;

}

