// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/os/looper.proto

package android.os;

/** @hide */
// message LooperProto
public final class LooperProto {

    // optional string thread_name = 1;
    public static final long THREAD_NAME = 0x0000010900000001L;

    // optional int64 thread_id = 2;
    public static final long THREAD_ID = 0x0000010300000002L;

    // optional .android.os.MessageQueueProto queue = 3;
    public static final long QUEUE = 0x0000010b00000003L;

}

