// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/os/pagetypeinfo.proto

package android.os;

/** @hide */
// message PageTypeInfoProto
public final class PageTypeInfoProto {

    // message MigrateType
    public final class MigrateType {

        // optional int32 node = 1;
        public static final long NODE = 0x0000010500000001L;

        // optional string zone = 2;
        public static final long ZONE = 0x0000010900000002L;

        // optional string type = 3;
        public static final long TYPE = 0x0000010900000003L;

        // repeated int32 free_pages_count = 4;
        public static final long FREE_PAGES_COUNT = 0x0000020500000004L;

    }

    // message Block
    public final class Block {

        // optional int32 node = 1;
        public static final long NODE = 0x0000010500000001L;

        // optional string zone = 2;
        public static final long ZONE = 0x0000010900000002L;

        // optional int32 unmovable = 3;
        public static final long UNMOVABLE = 0x0000010500000003L;

        // optional int32 reclaimable = 4;
        public static final long RECLAIMABLE = 0x0000010500000004L;

        // optional int32 movable = 5;
        public static final long MOVABLE = 0x0000010500000005L;

        // optional int32 cma = 6;
        public static final long CMA = 0x0000010500000006L;

        // optional int32 reserve = 7;
        public static final long RESERVE = 0x0000010500000007L;

        // optional int32 isolate = 8;
        public static final long ISOLATE = 0x0000010500000008L;

        // optional int32 highatomic = 9;
        public static final long HIGHATOMIC = 0x0000010500000009L;

    }

    // optional int32 page_block_order = 1;
    public static final long PAGE_BLOCK_ORDER = 0x0000010500000001L;

    // optional int32 pages_per_block = 2;
    public static final long PAGES_PER_BLOCK = 0x0000010500000002L;

    // repeated .android.os.PageTypeInfoProto.MigrateType migrate_types = 3;
    public static final long MIGRATE_TYPES = 0x0000020b00000003L;

    // repeated .android.os.PageTypeInfoProto.Block blocks = 4;
    public static final long BLOCKS = 0x0000020b00000004L;

}

