// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/os/persistablebundle.proto

package android.os;

/** @hide */
// message PersistableBundleProto
public final class PersistableBundleProto {

    // optional int32 parcelled_data_size = 1;
    public static final long PARCELLED_DATA_SIZE = 0x0000010500000001L;

    // optional string map_data = 2;
    public static final long MAP_DATA = 0x0000010900000002L;

}

