// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/os/powermanager.proto

package android.os;

/** @hide */
// message PowerManagerProto
public final class PowerManagerProto {

    // enum UserActivityEvent
    public static final int USER_ACTIVITY_EVENT_OTHER = 0;
    public static final int USER_ACTIVITY_EVENT_BUTTON = 1;
    public static final int USER_ACTIVITY_EVENT_TOUCH = 2;
    public static final int USER_ACTIVITY_EVENT_ACCESSIBILITY = 3;

    // message WakeLock
    public final class WakeLock {

        // optional string tag = 1;
        public static final long TAG = 0x0000010900000001L;

        // optional string package_name = 2;
        public static final long PACKAGE_NAME = 0x0000010900000002L;

        // optional bool held = 3;
        public static final long HELD = 0x0000010800000003L;

        // optional int32 internal_count = 4;
        public static final long INTERNAL_COUNT = 0x0000010500000004L;

        // optional .android.os.WorkSourceProto work_source = 5;
        public static final long WORK_SOURCE = 0x0000010b00000005L;

    }

}

