// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/os/powermanager.proto

package android.os;

/** @hide */
// message PowerManagerInternalProto
public final class PowerManagerInternalProto {

    // enum Wakefulness
    public static final int WAKEFULNESS_ASLEEP = 0;
    public static final int WAKEFULNESS_AWAKE = 1;
    public static final int WAKEFULNESS_DREAMING = 2;
    public static final int WAKEFULNESS_DOZING = 3;

}

