// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/service/graphicsstats.proto

package android.service;

/** @hide */
// message GraphicsStatsProto
public final class GraphicsStatsProto {

    // optional string package_name = 1;
    public static final long PACKAGE_NAME = 0x0000010900000001L;

    // optional int64 version_code = 2;
    public static final long VERSION_CODE = 0x0000010300000002L;

    // optional int64 stats_start = 3;
    public static final long STATS_START = 0x0000010300000003L;

    // optional int64 stats_end = 4;
    public static final long STATS_END = 0x0000010300000004L;

    // optional .android.service.GraphicsStatsJankSummaryProto summary = 5;
    public static final long SUMMARY = 0x0000010b00000005L;

    // repeated .android.service.GraphicsStatsHistogramBucketProto histogram = 6;
    public static final long HISTOGRAM = 0x0000020b00000006L;

}

