// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/service/netstats.proto

package android.service;

/** @hide */
// message NetworkInterfaceProto
public final class NetworkInterfaceProto {

    // optional string interface = 1;
    public static final long INTERFACE = 0x0000010900000001L;

    // optional .android.service.NetworkIdentitySetProto identities = 2;
    public static final long IDENTITIES = 0x0000010b00000002L;

}

