// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/service/battery.proto

package android.service.battery;

/** @hide */
// message BatteryServiceDumpProto
public final class BatteryServiceDumpProto {

    // optional bool are_updates_stopped = 1;
    public static final long ARE_UPDATES_STOPPED = 0x0000010800000001L;

    // optional .android.os.BatteryPluggedStateEnum plugged = 2;
    public static final long PLUGGED = 0x0000010e00000002L;

    // optional int32 max_charging_current = 3;
    public static final long MAX_CHARGING_CURRENT = 0x0000010500000003L;

    // optional int32 max_charging_voltage = 4;
    public static final long MAX_CHARGING_VOLTAGE = 0x0000010500000004L;

    // optional int32 charge_counter = 5;
    public static final long CHARGE_COUNTER = 0x0000010500000005L;

    // optional .android.os.BatteryStatusEnum status = 6;
    public static final long STATUS = 0x0000010e00000006L;

    // optional .android.os.BatteryHealthEnum health = 7;
    public static final long HEALTH = 0x0000010e00000007L;

    // optional bool is_present = 8;
    public static final long IS_PRESENT = 0x0000010800000008L;

    // optional int32 level = 9;
    public static final long LEVEL = 0x0000010500000009L;

    // optional int32 scale = 10;
    public static final long SCALE = 0x000001050000000aL;

    // optional int32 voltage = 11;
    public static final long VOLTAGE = 0x000001050000000bL;

    // optional int32 temperature = 12;
    public static final long TEMPERATURE = 0x000001050000000cL;

    // optional string technology = 13;
    public static final long TECHNOLOGY = 0x000001090000000dL;

}

