/* AUTO-GENERATED FILE. DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found. It
 * should not be modified by hand.
 */

package com.android.colorpicker;

public final class R {
  public static final class dimen {
    public static int color_swatch_large=0x00000000;
    public static int color_swatch_margins_large=0x00000000;
    public static int color_swatch_margins_small=0x00000000;
    public static int color_swatch_small=0x00000000;
  }
  public static final class drawable {
    public static int color_picker_swatch=0x00000000;
    public static int ic_colorpicker_swatch_selected=0x00000000;
  }
  public static final class id {
    public static int color_picker=0x00000000;
    public static int color_picker_checkmark=0x00000000;
    public static int color_picker_swatch=0x00000000;
  }
  public static final class layout {
    public static int color_picker_dialog=0x00000000;
    public static int color_picker_swatch=0x00000000;
  }
  public static final class string {
    /**
     * Default title for color picker dialog [CHAR LIMIT=30]
     */
    public static int color_picker_default_title=0x00000000;
    /**
     * Content description for a color square.
     */
    public static int color_swatch_description=0x00000000;
    /**
     * Content description for a selected color square.
     */
    public static int color_swatch_description_selected=0x00000000;
  }
}