// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/view/enums.proto

package android.view;

/** @hide */
public final class ViewProtoEnums {

    // enum DisplayStateEnum
    public static final int DISPLAY_STATE_UNKNOWN = 0;
    public static final int DISPLAY_STATE_OFF = 1;
    public static final int DISPLAY_STATE_ON = 2;
    public static final int DISPLAY_STATE_DOZE = 3;
    public static final int DISPLAY_STATE_DOZE_SUSPEND = 4;
    public static final int DISPLAY_STATE_VR = 5;
    public static final int DISPLAY_STATE_ON_SUSPEND = 6;

}
