// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/os/batterytype.proto

package android.os;

/** @hide */
// message BatteryTypeProto
public final class BatteryTypeProto {

    // optional string type = 1;
    public static final long TYPE = 0x0000010900000001L;

}

