// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/os/cpufreq.proto

package android.os;

/** @hide */
// message CpuFreqProto
public final class CpuFreqProto {

    // message Stats
    public final class Stats {

        // message TimeInState
        public final class TimeInState {

            // optional int32 state_khz = 1;
            public static final long STATE_KHZ = 0x0000010500000001L;

            // optional int64 time_jiffy = 2;
            public static final long TIME_JIFFY = 0x0000010300000002L;

        }

        // optional string cpu_name = 1;
        public static final long CPU_NAME = 0x0000010900000001L;

        // repeated .android.os.CpuFreqProto.Stats.TimeInState times = 2;
        public static final long TIMES = 0x0000020b00000002L;

    }

    // optional int32 jiffy_hz = 1;
    public static final long JIFFY_HZ = 0x0000010500000001L;

    // repeated .android.os.CpuFreqProto.Stats cpu_freqs = 2;
    public static final long CPU_FREQS = 0x0000020b00000002L;

}

