// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/os/data.proto

package android.os;

/** @hide */
// message GZippedFileProto
public final class GZippedFileProto {

    // optional string filename = 1;
    public static final long FILENAME = 0x0000010900000001L;

    // optional bytes gzipped_data = 2;
    public static final long GZIPPED_DATA = 0x0000010c00000002L;

}

