// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/libs/incident/proto/android/os/header.proto

package android.os;

/** @hide */
// message IncidentHeaderProto
public final class IncidentHeaderProto {

    // message StatsdConfigKey
    public final class StatsdConfigKey {

        // optional int32 uid = 1;
        public static final long UID = 0x0000010500000001L;

        // optional int64 id = 2;
        public static final long ID = 0x0000010300000002L;

    }

    // optional int64 alert_id = 1;
    public static final long ALERT_ID = 0x0000010300000001L;

    // optional string reason = 2;
    public static final long REASON = 0x0000010900000002L;

    // optional .android.os.IncidentHeaderProto.StatsdConfigKey config_key = 3;
    public static final long CONFIG_KEY = 0x0000010b00000003L;

}

