// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/os/ps.proto

package android.os;

/** @hide */
// message PsProto
public final class PsProto {

    // message Process
    public final class Process {

        // enum ProcessStateCode
        public static final int STATE_UNKNOWN = 0;
        public static final int STATE_D = 1;
        public static final int STATE_R = 2;
        public static final int STATE_S = 3;
        public static final int STATE_T = 4;
        public static final int STATE_TRACING = 5;
        public static final int STATE_X = 6;
        public static final int STATE_Z = 7;

        // enum SchedulingPolicy
        public static final int SCH_OTHER = 0;
        public static final int SCH_NORMAL = 0;
        public static final int SCH_FIFO = 1;
        public static final int SCH_RR = 2;
        public static final int SCH_BATCH = 3;
        public static final int SCH_ISO = 4;
        public static final int SCH_IDLE = 5;

        // enum Policy
        public static final int POLICY_UNKNOWN = 0;
        public static final int POLICY_FG = 1;
        public static final int POLICY_BG = 2;
        public static final int POLICY_TA = 3;

        // optional string label = 1;
        public static final long LABEL = 0x0000010900000001L;

        // optional string user = 2;
        public static final long USER = 0x0000010900000002L;

        // optional int32 pid = 3;
        public static final long PID = 0x0000010500000003L;

        // optional int32 tid = 4;
        public static final long TID = 0x0000010500000004L;

        // optional int32 ppid = 5;
        public static final long PPID = 0x0000010500000005L;

        // optional int32 vsz = 6;
        public static final long VSZ = 0x0000010500000006L;

        // optional int32 rss = 7;
        public static final long RSS = 0x0000010500000007L;

        // optional string wchan = 8;
        public static final long WCHAN = 0x0000010900000008L;

        // optional string addr = 9;
        public static final long ADDR = 0x0000010900000009L;

        // optional .android.os.PsProto.Process.ProcessStateCode s = 10;
        public static final long S = 0x0000010e0000000aL;

        // optional int32 pri = 11;
        public static final long PRI = 0x000001050000000bL;

        // optional sint32 ni = 12;
        public static final long NI = 0x000001110000000cL;

        // optional string rtprio = 13;
        public static final long RTPRIO = 0x000001090000000dL;

        // optional .android.os.PsProto.Process.SchedulingPolicy sch = 14;
        public static final long SCH = 0x0000010e0000000eL;

        // optional .android.os.PsProto.Process.Policy pcy = 15;
        public static final long PCY = 0x0000010e0000000fL;

        // optional string time = 16;
        public static final long TIME = 0x0000010900000010L;

        // optional string cmd = 17;
        public static final long CMD = 0x0000010900000011L;

    }

    // repeated .android.os.PsProto.Process processes = 1;
    public static final long PROCESSES = 0x0000020b00000001L;

}

