// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/os/system_properties.proto

package android.os;

/** @hide */
// message SystemPropertiesProto
public final class SystemPropertiesProto {

    // message Property
    public final class Property {

        // optional string name = 1;
        public static final long NAME = 0x0000010900000001L;

        // optional string value = 2;
        public static final long VALUE = 0x0000010900000002L;

    }

    // message AacDrc
    public final class AacDrc {

        // optional int32 boost = 1;
        public static final long BOOST = 0x0000010500000001L;

        // optional int32 cut = 2;
        public static final long CUT = 0x0000010500000002L;

        // optional int32 enc_target_level = 3;
        public static final long ENC_TARGET_LEVEL = 0x0000010500000003L;

        // optional int32 heavy = 4;
        public static final long HEAVY = 0x0000010500000004L;

        // optional int32 reference_level = 5;
        public static final long REFERENCE_LEVEL = 0x0000010500000005L;

    }

    // message Aaudio
    public final class Aaudio {

        // optional int32 hw_burst_min_usec = 1;
        public static final long HW_BURST_MIN_USEC = 0x0000010500000001L;

        // optional int32 minimum_sleep_usec = 2;
        public static final long MINIMUM_SLEEP_USEC = 0x0000010500000002L;

        // optional int32 mixer_bursts = 3;
        public static final long MIXER_BURSTS = 0x0000010500000003L;

        // optional int32 mmap_exclusive_policy = 4;
        public static final long MMAP_EXCLUSIVE_POLICY = 0x0000010500000004L;

        // optional int32 mmap_policy = 5;
        public static final long MMAP_POLICY = 0x0000010500000005L;

        // optional int32 wakeup_delay_usec = 6;
        public static final long WAKEUP_DELAY_USEC = 0x0000010500000006L;

    }

    // message Camera
    public final class Camera {

        // optional bool disable_zsl_mode = 1;
        public static final long DISABLE_ZSL_MODE = 0x0000010800000001L;

        // optional int32 fifo_disable = 2;
        public static final long FIFO_DISABLE = 0x0000010500000002L;

    }

    // message DalvikVm
    public final class DalvikVm {

        // optional string appimageformat = 1;
        public static final long APPIMAGEFORMAT = 0x0000010900000001L;

        // optional string backgroundgctype = 2;
        public static final long BACKGROUNDGCTYPE = 0x0000010900000002L;

        // optional bool checkjni = 3;
        public static final long CHECKJNI = 0x0000010800000003L;

        // optional string dex2oat_filter = 4;
        public static final long DEX2OAT_FILTER = 0x0000010900000004L;

        // optional string dex2oat_flags = 5;
        public static final long DEX2OAT_FLAGS = 0x0000010900000005L;

        // optional int32 dex2oat_threads = 6;
        public static final long DEX2OAT_THREADS = 0x0000010500000006L;

        // optional string dex2oat_Xms = 7;
        public static final long DEX2OAT_XMS = 0x0000010900000007L;

        // optional string dex2oat_Xmx = 8;
        public static final long DEX2OAT_XMX = 0x0000010900000008L;

        // optional bool dexopt_secondary = 9;
        public static final long DEXOPT_SECONDARY = 0x0000010800000009L;

        // optional string execution_mode = 10;
        public static final long EXECUTION_MODE = 0x000001090000000aL;

        // optional string extra_opts = 11;
        public static final long EXTRA_OPTS = 0x000001090000000bL;

        // optional string gctype = 12;
        public static final long GCTYPE = 0x000001090000000cL;

        // optional string heapgrowthlimit = 13;
        public static final long HEAPGROWTHLIMIT = 0x000001090000000dL;

        // optional string heapmaxfree = 14;
        public static final long HEAPMAXFREE = 0x000001090000000eL;

        // optional string heapminfree = 15;
        public static final long HEAPMINFREE = 0x000001090000000fL;

        // optional string heapsize = 16;
        public static final long HEAPSIZE = 0x0000010900000010L;

        // optional string heapstartsize = 17;
        public static final long HEAPSTARTSIZE = 0x0000010900000011L;

        // optional double heaptargetutilization = 18;
        public static final long HEAPTARGETUTILIZATION = 0x0000010100000012L;

        // optional int32 hot_startup_method_samples = 19;
        public static final long HOT_STARTUP_METHOD_SAMPLES = 0x0000010500000013L;

        // optional string image_dex2oat_filter = 20;
        public static final long IMAGE_DEX2OAT_FILTER = 0x0000010900000014L;

        // optional string image_dex2oat_flags = 21;
        public static final long IMAGE_DEX2OAT_FLAGS = 0x0000010900000015L;

        // optional int32 image_dex2oat_threads = 22;
        public static final long IMAGE_DEX2OAT_THREADS = 0x0000010500000016L;

        // optional string image_dex2oat_Xms = 23;
        public static final long IMAGE_DEX2OAT_XMS = 0x0000010900000017L;

        // optional string image_dex2oat_Xmx = 24;
        public static final long IMAGE_DEX2OAT_XMX = 0x0000010900000018L;

        // optional string isa_arm_features = 25;
        public static final long ISA_ARM_FEATURES = 0x0000010900000019L;

        // optional string isa_arm_variant = 26;
        public static final long ISA_ARM_VARIANT = 0x000001090000001aL;

        // optional string isa_arm64_features = 27;
        public static final long ISA_ARM64_FEATURES = 0x000001090000001bL;

        // optional string isa_arm64_variant = 28;
        public static final long ISA_ARM64_VARIANT = 0x000001090000001cL;

        // optional string isa_mips_features = 29;
        public static final long ISA_MIPS_FEATURES = 0x000001090000001dL;

        // optional string isa_mips_variant = 30;
        public static final long ISA_MIPS_VARIANT = 0x000001090000001eL;

        // optional string isa_mips64_features = 31;
        public static final long ISA_MIPS64_FEATURES = 0x000001090000001fL;

        // optional string isa_mips64_variant = 32;
        public static final long ISA_MIPS64_VARIANT = 0x0000010900000020L;

        // optional string isa_unknown_features = 33;
        public static final long ISA_UNKNOWN_FEATURES = 0x0000010900000021L;

        // optional string isa_unknown_variant = 34;
        public static final long ISA_UNKNOWN_VARIANT = 0x0000010900000022L;

        // optional string isa_x86_64_features = 35;
        public static final long ISA_X86_64_FEATURES = 0x0000010900000023L;

        // optional string isa_x86_64_variant = 36;
        public static final long ISA_X86_64_VARIANT = 0x0000010900000024L;

        // optional string isa_x86_features = 37;
        public static final long ISA_X86_FEATURES = 0x0000010900000025L;

        // optional string isa_x86_variant = 38;
        public static final long ISA_X86_VARIANT = 0x0000010900000026L;

        // optional string jitinitialsize = 39;
        public static final long JITINITIALSIZE = 0x0000010900000027L;

        // optional string jitmaxsize = 40;
        public static final long JITMAXSIZE = 0x0000010900000028L;

        // optional int32 jitprithreadweight = 41;
        public static final long JITPRITHREADWEIGHT = 0x0000010500000029L;

        // optional int32 jitthreshold = 42;
        public static final long JITTHRESHOLD = 0x000001050000002aL;

        // optional int32 jittransitionweight = 43;
        public static final long JITTRANSITIONWEIGHT = 0x000001050000002bL;

        // optional string jniopts = 44;
        public static final long JNIOPTS = 0x000001090000002cL;

        // optional int32 lockprof_threshold = 45;
        public static final long LOCKPROF_THRESHOLD = 0x000001050000002dL;

        // optional bool method_trace = 46;
        public static final long METHOD_TRACE = 0x000001080000002eL;

        // optional string method_trace_file = 47;
        public static final long METHOD_TRACE_FILE = 0x000001090000002fL;

        // optional int32 method_trace_file_siz = 48;
        public static final long METHOD_TRACE_FILE_SIZ = 0x0000010500000030L;

        // optional bool method_trace_stream = 49;
        public static final long METHOD_TRACE_STREAM = 0x0000010800000031L;

        // optional bool profilesystemserver = 50;
        public static final long PROFILESYSTEMSERVER = 0x0000010800000032L;

        // optional string stack_trace_dir = 51;
        public static final long STACK_TRACE_DIR = 0x0000010900000033L;

        // optional bool usejit = 52;
        public static final long USEJIT = 0x0000010800000034L;

        // optional bool usejitprofiles = 53;
        public static final long USEJITPROFILES = 0x0000010800000035L;

        // optional int32 zygote_max_boot_retry = 54;
        public static final long ZYGOTE_MAX_BOOT_RETRY = 0x0000010500000036L;

    }

    // message InitSvc
    public final class InitSvc {

        // enum Status
        public static final int STATUS_UNKNOWN = 0;
        public static final int STATUS_RUNNING = 1;
        public static final int STATUS_STOPPED = 2;

        // optional .android.os.SystemPropertiesProto.InitSvc.Status adbd = 1;
        public static final long ADBD = 0x0000010e00000001L;

        // optional .android.os.SystemPropertiesProto.InitSvc.Status audioserver = 2;
        public static final long AUDIOSERVER = 0x0000010e00000002L;

        // optional .android.os.SystemPropertiesProto.InitSvc.Status bootanim = 3;
        public static final long BOOTANIM = 0x0000010e00000003L;

        // optional .android.os.SystemPropertiesProto.InitSvc.Status bufferhubd = 4;
        public static final long BUFFERHUBD = 0x0000010e00000004L;

        // optional .android.os.SystemPropertiesProto.InitSvc.Status cameraserver = 5;
        public static final long CAMERASERVER = 0x0000010e00000005L;

        // optional .android.os.SystemPropertiesProto.InitSvc.Status clear_bcb = 6;
        public static final long CLEAR_BCB = 0x0000010e00000006L;

        // optional .android.os.SystemPropertiesProto.InitSvc.Status drm = 7;
        public static final long DRM = 0x0000010e00000007L;

        // optional .android.os.SystemPropertiesProto.InitSvc.Status gatekeeperd = 8;
        public static final long GATEKEEPERD = 0x0000010e00000008L;

        // optional .android.os.SystemPropertiesProto.InitSvc.Status healthd = 9;
        public static final long HEALTHD = 0x0000010e00000009L;

        // optional .android.os.SystemPropertiesProto.InitSvc.Status hidl_memory = 10;
        public static final long HIDL_MEMORY = 0x0000010e0000000aL;

        // optional .android.os.SystemPropertiesProto.InitSvc.Status hostapd = 11;
        public static final long HOSTAPD = 0x0000010e0000000bL;

        // optional .android.os.SystemPropertiesProto.InitSvc.Status hwservicemanager = 12;
        public static final long HWSERVICEMANAGER = 0x0000010e0000000cL;

        // optional .android.os.SystemPropertiesProto.InitSvc.Status installd = 13;
        public static final long INSTALLD = 0x0000010e0000000dL;

        // optional .android.os.SystemPropertiesProto.InitSvc.Status keystore = 14;
        public static final long KEYSTORE = 0x0000010e0000000eL;

        // optional .android.os.SystemPropertiesProto.InitSvc.Status lmkd = 15;
        public static final long LMKD = 0x0000010e0000000fL;

        // optional .android.os.SystemPropertiesProto.InitSvc.Status logd = 16;
        public static final long LOGD = 0x0000010e00000010L;

        // optional .android.os.SystemPropertiesProto.InitSvc.Status logd_reinit = 17;
        public static final long LOGD_REINIT = 0x0000010e00000011L;

        // optional .android.os.SystemPropertiesProto.InitSvc.Status media = 18;
        public static final long MEDIA = 0x0000010e00000012L;

        // optional .android.os.SystemPropertiesProto.InitSvc.Status mediadrm = 19;
        public static final long MEDIADRM = 0x0000010e00000013L;

        // optional .android.os.SystemPropertiesProto.InitSvc.Status mediaextractor = 20;
        public static final long MEDIAEXTRACTOR = 0x0000010e00000014L;

        // optional .android.os.SystemPropertiesProto.InitSvc.Status mediametrics = 21;
        public static final long MEDIAMETRICS = 0x0000010e00000015L;

        // optional .android.os.SystemPropertiesProto.InitSvc.Status netd = 22;
        public static final long NETD = 0x0000010e00000016L;

        // optional .android.os.SystemPropertiesProto.InitSvc.Status performanced = 23;
        public static final long PERFORMANCED = 0x0000010e00000017L;

        // optional .android.os.SystemPropertiesProto.InitSvc.Status ril_daemon = 24;
        public static final long RIL_DAEMON = 0x0000010e00000018L;

        // optional .android.os.SystemPropertiesProto.InitSvc.Status servicemanager = 25;
        public static final long SERVICEMANAGER = 0x0000010e00000019L;

        // optional .android.os.SystemPropertiesProto.InitSvc.Status storaged = 26;
        public static final long STORAGED = 0x0000010e0000001aL;

        // optional .android.os.SystemPropertiesProto.InitSvc.Status surfaceflinger = 27;
        public static final long SURFACEFLINGER = 0x0000010e0000001bL;

        // optional .android.os.SystemPropertiesProto.InitSvc.Status thermalservice = 28;
        public static final long THERMALSERVICE = 0x0000010e0000001cL;

        // optional .android.os.SystemPropertiesProto.InitSvc.Status tombstoned = 29;
        public static final long TOMBSTONED = 0x0000010e0000001dL;

        // optional .android.os.SystemPropertiesProto.InitSvc.Status ueventd = 30;
        public static final long UEVENTD = 0x0000010e0000001eL;

        // optional .android.os.SystemPropertiesProto.InitSvc.Status update_engine = 31;
        public static final long UPDATE_ENGINE = 0x0000010e0000001fL;

        // optional .android.os.SystemPropertiesProto.InitSvc.Status update_verifier_nonencrypted = 32;
        public static final long UPDATE_VERIFIER_NONENCRYPTED = 0x0000010e00000020L;

        // optional .android.os.SystemPropertiesProto.InitSvc.Status virtual_touchpad = 33;
        public static final long VIRTUAL_TOUCHPAD = 0x0000010e00000021L;

        // optional .android.os.SystemPropertiesProto.InitSvc.Status vndservicemanager = 34;
        public static final long VNDSERVICEMANAGER = 0x0000010e00000022L;

        // optional .android.os.SystemPropertiesProto.InitSvc.Status vold = 35;
        public static final long VOLD = 0x0000010e00000023L;

        // optional .android.os.SystemPropertiesProto.InitSvc.Status vr_hwc = 36;
        public static final long VR_HWC = 0x0000010e00000024L;

        // optional .android.os.SystemPropertiesProto.InitSvc.Status webview_zygote32 = 37;
        public static final long WEBVIEW_ZYGOTE32 = 0x0000010e00000025L;

        // optional .android.os.SystemPropertiesProto.InitSvc.Status wificond = 38;
        public static final long WIFICOND = 0x0000010e00000026L;

        // optional .android.os.SystemPropertiesProto.InitSvc.Status wpa_supplicant = 39;
        public static final long WPA_SUPPLICANT = 0x0000010e00000027L;

        // optional .android.os.SystemPropertiesProto.InitSvc.Status zygote = 40;
        public static final long ZYGOTE = 0x0000010e00000028L;

        // optional .android.os.SystemPropertiesProto.InitSvc.Status zygote_secondary = 41;
        public static final long ZYGOTE_SECONDARY = 0x0000010e00000029L;

    }

    // message Log
    public final class Log {

        // optional string tag_WifiHAL = 1;
        public static final long TAG_WIFI_HAL = 0x0000010900000001L;

        // optional string tag_stats_log = 2;
        public static final long TAG_STATS_LOG = 0x0000010900000002L;

    }

    // message Persist
    public final class Persist {

        // optional string config_calibration_fac = 1;
        public static final long CONFIG_CALIBRATION_FAC = 0x0000010900000001L;

        // optional int32 dbg_volte_avail_ovr = 2;
        public static final long DBG_VOLTE_AVAIL_OVR = 0x0000010500000002L;

        // optional int32 dbg_vt_avail_ovr = 3;
        public static final long DBG_VT_AVAIL_OVR = 0x0000010500000003L;

        // optional int32 dbg_wfc_avail_ovr = 4;
        public static final long DBG_WFC_AVAIL_OVR = 0x0000010500000004L;

        // optional int32 radio_airplane_mode_on = 5;
        public static final long RADIO_AIRPLANE_MODE_ON = 0x0000010500000005L;

        // optional string radio_multisim_config = 6;
        public static final long RADIO_MULTISIM_CONFIG = 0x0000010900000006L;

        // optional int32 rcs_supported = 7;
        public static final long RCS_SUPPORTED = 0x0000010500000007L;

        // optional bool sys_crash_rcu = 8;
        public static final long SYS_CRASH_RCU = 0x0000010800000008L;

        // optional string sys_dalvik_vm_lib_2 = 9;
        public static final long SYS_DALVIK_VM_LIB_2 = 0x0000010900000009L;

        // optional float sys_sf_color_saturation = 10;
        public static final long SYS_SF_COLOR_SATURATION = 0x000001020000000aL;

        // optional string sys_timezone = 11;
        public static final long SYS_TIMEZONE = 0x000001090000000bL;

    }

    // message PmDexopt
    public final class PmDexopt {

        // optional string ab_ota = 1;
        public static final long AB_OTA = 0x0000010900000001L;

        // optional string bg_dexopt = 2;
        public static final long BG_DEXOPT = 0x0000010900000002L;

        // optional string boot = 3;
        public static final long BOOT = 0x0000010900000003L;

        // optional string first_boot = 4;
        public static final long FIRST_BOOT = 0x0000010900000004L;

        // optional string install = 5;
        public static final long INSTALL = 0x0000010900000005L;

    }

    // message Ro
    public final class Ro {

        // message Boot
        public final class Boot {

            // optional string avb_version = 1;
            public static final long AVB_VERSION = 0x0000010900000001L;

            // optional string baseband = 2;
            public static final long BASEBAND = 0x0000010900000002L;

            // optional string bootdevice = 3;
            public static final long BOOTDEVICE = 0x0000010900000003L;

            // optional string bootloader = 4;
            public static final long BOOTLOADER = 0x0000010900000004L;

            // repeated string boottime = 5;
            public static final long BOOTTIME = 0x0000020900000005L;

            // optional string console = 6;
            public static final long CONSOLE = 0x0000010900000006L;

            // optional int32 fake_battery = 7;
            public static final long FAKE_BATTERY = 0x0000010500000007L;

            // optional string hardware = 8;
            public static final long HARDWARE = 0x0000010900000008L;

            // optional string hardware_color = 9;
            public static final long HARDWARE_COLOR = 0x0000010900000009L;

            // optional string hardware_revision = 10;
            public static final long HARDWARE_REVISION = 0x000001090000000aL;

            // optional string hardware_sku = 11;
            public static final long HARDWARE_SKU = 0x000001090000000bL;

            // optional string keymaster = 12;
            public static final long KEYMASTER = 0x000001090000000cL;

            // optional string mode = 13;
            public static final long MODE = 0x000001090000000dL;

            // optional string revision = 14;
            public static final long REVISION = 0x000001090000000eL;

            // optional string slot_suffix = 15;
            public static final long SLOT_SUFFIX = 0x000001090000000fL;

            // optional string vbmeta_avb_version = 16;
            public static final long VBMETA_AVB_VERSION = 0x0000010900000010L;

            // optional string vendor_overlay_theme = 17;
            public static final long VENDOR_OVERLAY_THEME = 0x0000010900000011L;

            // optional string verifiedbootstate = 18;
            public static final long VERIFIEDBOOTSTATE = 0x0000010900000012L;

            // optional string veritymode = 19;
            public static final long VERITYMODE = 0x0000010900000013L;

            // optional string wificountrycode = 20;
            public static final long WIFICOUNTRYCODE = 0x0000010900000014L;

        }

        // message BootImage
        public final class BootImage {

            // optional string build_date = 1;
            public static final long BUILD_DATE = 0x0000010900000001L;

            // optional int64 build_date_utc = 2;
            public static final long BUILD_DATE_UTC = 0x0000010300000002L;

            // optional string build_fingerprint = 3;
            public static final long BUILD_FINGERPRINT = 0x0000010900000003L;

        }

        // message Build
        public final class Build {

            // message Version
            public final class Version {

                // optional string base_os = 1;
                public static final long BASE_OS = 0x0000010900000001L;

                // optional string codename = 2;
                public static final long CODENAME = 0x0000010900000002L;

                // optional string incremental = 3;
                public static final long INCREMENTAL = 0x0000010900000003L;

                // optional int32 preview_sdk = 4;
                public static final long PREVIEW_SDK = 0x0000010500000004L;

                // optional string release = 5;
                public static final long RELEASE = 0x0000010900000005L;

                // optional int32 sdk = 6;
                public static final long SDK = 0x0000010500000006L;

                // optional string security_patch = 7;
                public static final long SECURITY_PATCH = 0x0000010900000007L;

            }

            // optional string date = 1;
            public static final long DATE = 0x0000010900000001L;

            // optional int64 date_utc = 2;
            public static final long DATE_UTC = 0x0000010300000002L;

            // optional string description = 3;
            public static final long DESCRIPTION = 0x0000010900000003L;

            // optional string display_id = 4;
            public static final long DISPLAY_ID = 0x0000010900000004L;

            // optional string host = 5;
            public static final long HOST = 0x0000010900000005L;

            // optional string id = 6;
            public static final long ID = 0x0000010900000006L;

            // optional string product = 7;
            public static final long PRODUCT = 0x0000010900000007L;

            // optional bool system_root_image = 8;
            public static final long SYSTEM_ROOT_IMAGE = 0x0000010800000008L;

            // optional string tags = 9;
            public static final long TAGS = 0x0000010900000009L;

            // optional string type = 10;
            public static final long TYPE = 0x000001090000000aL;

            // optional string user = 11;
            public static final long USER = 0x000001090000000bL;

            // optional .android.os.SystemPropertiesProto.Ro.Build.Version version = 12;
            public static final long VERSION = 0x0000010b0000000cL;

        }

        // message Config
        public final class Config {

            // optional string alarm_alert = 1;
            public static final long ALARM_ALERT = 0x0000010900000001L;

            // optional int32 media_vol_steps = 2;
            public static final long MEDIA_VOL_STEPS = 0x0000010500000002L;

            // optional string notification_sound = 3;
            public static final long NOTIFICATION_SOUND = 0x0000010900000003L;

            // optional string ringtone = 4;
            public static final long RINGTONE = 0x0000010900000004L;

            // optional int32 vc_call_vol_steps = 5;
            public static final long VC_CALL_VOL_STEPS = 0x0000010500000005L;

        }

        // message Hardware
        public final class Hardware {

            // optional string value = 1;
            public static final long VALUE = 0x0000010900000001L;

            // optional string activity_recognition = 2;
            public static final long ACTIVITY_RECOGNITION = 0x0000010900000002L;

            // optional string audio = 3;
            public static final long AUDIO = 0x0000010900000003L;

            // optional string audio_policy = 4;
            public static final long AUDIO_POLICY = 0x0000010900000004L;

            // optional string audio_a2dp = 5;
            public static final long AUDIO_A2DP = 0x0000010900000005L;

            // optional string audio_primary = 6;
            public static final long AUDIO_PRIMARY = 0x0000010900000006L;

            // optional string audio_usb = 7;
            public static final long AUDIO_USB = 0x0000010900000007L;

            // optional string bootctrl = 8;
            public static final long BOOTCTRL = 0x0000010900000008L;

            // optional string camera = 9;
            public static final long CAMERA = 0x0000010900000009L;

            // optional string consumerir = 10;
            public static final long CONSUMERIR = 0x000001090000000aL;

            // optional string context_hub = 11;
            public static final long CONTEXT_HUB = 0x000001090000000bL;

            // optional string egl = 12;
            public static final long EGL = 0x000001090000000cL;

            // optional string fingerprint = 13;
            public static final long FINGERPRINT = 0x000001090000000dL;

            // optional string flp = 14;
            public static final long FLP = 0x000001090000000eL;

            // optional string gatekeeper = 15;
            public static final long GATEKEEPER = 0x000001090000000fL;

            // optional string gps = 16;
            public static final long GPS = 0x0000010900000010L;

            // optional string gralloc = 17;
            public static final long GRALLOC = 0x0000010900000011L;

            // optional string hdmi_cec = 18;
            public static final long HDMI_CEC = 0x0000010900000012L;

            // optional string hwcomposer = 19;
            public static final long HWCOMPOSER = 0x0000010900000013L;

            // optional string input = 20;
            public static final long INPUT = 0x0000010900000014L;

            // optional string keystore = 21;
            public static final long KEYSTORE = 0x0000010900000015L;

            // optional string lights = 22;
            public static final long LIGHTS = 0x0000010900000016L;

            // optional string local_time = 23;
            public static final long LOCAL_TIME = 0x0000010900000017L;

            // optional string memtrack = 24;
            public static final long MEMTRACK = 0x0000010900000018L;

            // optional string nfc = 25;
            public static final long NFC = 0x0000010900000019L;

            // optional string nfc_nci = 26;
            public static final long NFC_NCI = 0x000001090000001aL;

            // optional string nfc_tag = 27;
            public static final long NFC_TAG = 0x000001090000001bL;

            // optional string nvram = 28;
            public static final long NVRAM = 0x000001090000001cL;

            // optional string power = 29;
            public static final long POWER = 0x000001090000001dL;

            // optional string radio = 30;
            public static final long RADIO = 0x000001090000001eL;

            // optional string sensors = 31;
            public static final long SENSORS = 0x000001090000001fL;

            // optional string sound_trigger = 32;
            public static final long SOUND_TRIGGER = 0x0000010900000020L;

            // optional string thermal = 33;
            public static final long THERMAL = 0x0000010900000021L;

            // optional string tv_input = 34;
            public static final long TV_INPUT = 0x0000010900000022L;

            // optional string type = 35;
            public static final long TYPE = 0x0000010900000023L;

            // optional string vehicle = 36;
            public static final long VEHICLE = 0x0000010900000024L;

            // optional string vibrator = 37;
            public static final long VIBRATOR = 0x0000010900000025L;

            // optional string virtual_device = 38;
            public static final long VIRTUAL_DEVICE = 0x0000010900000026L;

            // optional string vulkan = 39;
            public static final long VULKAN = 0x0000010900000027L;

        }

        // message Product
        public final class Product {

            // message Vendor
            public final class Vendor {

                // optional string brand = 1;
                public static final long BRAND = 0x0000010900000001L;

                // optional string device = 2;
                public static final long DEVICE = 0x0000010900000002L;

                // optional string manufacturer = 3;
                public static final long MANUFACTURER = 0x0000010900000003L;

                // optional string model = 4;
                public static final long MODEL = 0x0000010900000004L;

                // optional string name = 5;
                public static final long NAME = 0x0000010900000005L;

            }

            // optional string board = 1;
            public static final long BOARD = 0x0000010900000001L;

            // optional string brand = 2;
            public static final long BRAND = 0x0000010900000002L;

            // optional string cpu_abi = 3;
            public static final long CPU_ABI = 0x0000010900000003L;

            // repeated string cpu_abilist = 4;
            public static final long CPU_ABILIST = 0x0000020900000004L;

            // repeated string cpu_abilist32 = 5;
            public static final long CPU_ABILIST32 = 0x0000020900000005L;

            // repeated string cpu_abilist64 = 6;
            public static final long CPU_ABILIST64 = 0x0000020900000006L;

            // optional string device = 7;
            public static final long DEVICE = 0x0000010900000007L;

            // optional int32 first_api_level = 8;
            public static final long FIRST_API_LEVEL = 0x0000010500000008L;

            // optional string manufacturer = 9;
            public static final long MANUFACTURER = 0x0000010900000009L;

            // optional string model = 10;
            public static final long MODEL = 0x000001090000000aL;

            // optional string name = 11;
            public static final long NAME = 0x000001090000000bL;

            // optional .android.os.SystemPropertiesProto.Ro.Product.Vendor vendor = 12;
            public static final long VENDOR = 0x0000010b0000000cL;

        }

        // message Telephony
        public final class Telephony {

            // optional bool call_ring_multiple = 1;
            public static final long CALL_RING_MULTIPLE = 0x0000010800000001L;

            // optional int32 default_cdma_sub = 2;
            public static final long DEFAULT_CDMA_SUB = 0x0000010500000002L;

            // optional int32 default_network = 3;
            public static final long DEFAULT_NETWORK = 0x0000010500000003L;

        }

        // message Vendor
        public final class Vendor {

            // optional string build_date = 1;
            public static final long BUILD_DATE = 0x0000010900000001L;

            // optional int64 build_date_utc = 2;
            public static final long BUILD_DATE_UTC = 0x0000010300000002L;

            // optional string build_fingerprint = 3;
            public static final long BUILD_FINGERPRINT = 0x0000010900000003L;

        }

        // optional bool adb_secure = 1;
        public static final long ADB_SECURE = 0x0000010800000001L;

        // optional string arch = 2;
        public static final long ARCH = 0x0000010900000002L;

        // optional bool audio_ignore_effects = 3;
        public static final long AUDIO_IGNORE_EFFECTS = 0x0000010800000003L;

        // optional bool audio_monitorRotation = 4;
        public static final long AUDIO_MONITOR_ROTATION = 0x0000010800000004L;

        // optional string baseband = 5;
        public static final long BASEBAND = 0x0000010900000005L;

        // optional string board_platform = 6;
        public static final long BOARD_PLATFORM = 0x0000010900000006L;

        // optional .android.os.SystemPropertiesProto.Ro.Boot boot = 7;
        public static final long BOOT = 0x0000010b00000007L;

        // optional .android.os.SystemPropertiesProto.Ro.BootImage bootimage = 8;
        public static final long BOOTIMAGE = 0x0000010b00000008L;

        // optional string bootloader = 9;
        public static final long BOOTLOADER = 0x0000010900000009L;

        // optional string bootmode = 10;
        public static final long BOOTMODE = 0x000001090000000aL;

        // optional .android.os.SystemPropertiesProto.Ro.Build build = 11;
        public static final long BUILD = 0x0000010b0000000bL;

        // optional bool camera_notify_nfc = 12;
        public static final long CAMERA_NOTIFY_NFC = 0x000001080000000cL;

        // optional string carrier = 13;
        public static final long CARRIER = 0x000001090000000dL;

        // optional bool com_android_dataroaming = 14;
        public static final long COM_ANDROID_DATAROAMING = 0x000001080000000eL;

        // optional bool com_android_prov_mobiledata = 15;
        public static final long COM_ANDROID_PROV_MOBILEDATA = 0x000001080000000fL;

        // optional string com_google_clientidbase = 16;
        public static final long COM_GOOGLE_CLIENTIDBASE = 0x0000010900000010L;

        // optional .android.os.SystemPropertiesProto.Ro.Config config = 17;
        public static final long CONFIG = 0x0000010b00000011L;

        // optional string control_privapp_permissions = 18;
        public static final long CONTROL_PRIVAPP_PERMISSIONS = 0x0000010900000012L;

        // optional int32 cp_system_other_odex = 19;
        public static final long CP_SYSTEM_OTHER_ODEX = 0x0000010500000013L;

        // optional string crypto_scrypt_params = 20;
        public static final long CRYPTO_SCRYPT_PARAMS = 0x0000010900000014L;

        // optional string crypto_state = 21;
        public static final long CRYPTO_STATE = 0x0000010900000015L;

        // optional string crypto_type = 22;
        public static final long CRYPTO_TYPE = 0x0000010900000016L;

        // optional string dalvik_vm_native_bridge = 23;
        public static final long DALVIK_VM_NATIVE_BRIDGE = 0x0000010900000017L;

        // optional bool debuggable = 24;
        public static final long DEBUGGABLE = 0x0000010800000018L;

        // optional string frp_pst = 25;
        public static final long FRP_PST = 0x0000010900000019L;

        // optional string gfx_driver_0 = 26;
        public static final long GFX_DRIVER_0 = 0x000001090000001aL;

        // optional .android.os.SystemPropertiesProto.Ro.Hardware hardware = 27;
        public static final long HARDWARE = 0x0000010b0000001bL;

        // optional int32 kernel_qemu = 28;
        public static final long KERNEL_QEMU = 0x000001050000001cL;

        // optional int32 kernel_qemu_gles = 29;
        public static final long KERNEL_QEMU_GLES = 0x000001050000001dL;

        // optional int32 oem_unlock_supported = 30;
        public static final long OEM_UNLOCK_SUPPORTED = 0x000001050000001eL;

        // optional int32 opengles_version = 31;
        public static final long OPENGLES_VERSION = 0x000001050000001fL;

        // optional .android.os.SystemPropertiesProto.Ro.Product product = 32;
        public static final long PRODUCT = 0x0000010b00000020L;

        // optional int32 property_service_version = 33;
        public static final long PROPERTY_SERVICE_VERSION = 0x0000010500000021L;

        // optional string retaildemo_video_path = 34;
        public static final long RETAILDEMO_VIDEO_PATH = 0x0000010900000022L;

        // optional string revision = 35;
        public static final long REVISION = 0x0000010900000023L;

        // optional int32 sf_lcd_density = 36;
        public static final long SF_LCD_DENSITY = 0x0000010500000024L;

        // optional bool storage_manager_enabled = 37;
        public static final long STORAGE_MANAGER_ENABLED = 0x0000010800000025L;

        // optional .android.os.SystemPropertiesProto.Ro.Telephony telephony = 38;
        public static final long TELEPHONY = 0x0000010b00000026L;

        // optional string url_legal = 39;
        public static final long URL_LEGAL = 0x0000010900000027L;

        // optional string url_legal_android_privacy = 40;
        public static final long URL_LEGAL_ANDROID_PRIVACY = 0x0000010900000028L;

        // optional .android.os.SystemPropertiesProto.Ro.Vendor vendor = 41;
        public static final long VENDOR = 0x0000010b00000029L;

        // optional string vndk_version = 42;
        public static final long VNDK_VERSION = 0x000001090000002aL;

        // optional int32 vts_coverage = 43;
        public static final long VTS_COVERAGE = 0x000001050000002bL;

        // optional string zygote = 44;
        public static final long ZYGOTE = 0x000001090000002cL;

    }

    // message Sys
    public final class Sys {

        // message Usb
        public final class Usb {

            // optional string config = 1;
            public static final long CONFIG = 0x0000010900000001L;

            // optional int32 configfs = 2;
            public static final long CONFIGFS = 0x0000010500000002L;

            // optional string controller = 3;
            public static final long CONTROLLER = 0x0000010900000003L;

            // optional int32 ffs_max_read = 4;
            public static final long FFS_MAX_READ = 0x0000010500000004L;

            // optional int32 ffs_max_write = 5;
            public static final long FFS_MAX_WRITE = 0x0000010500000005L;

            // optional int32 ffs_mtp_ready = 6;
            public static final long FFS_MTP_READY = 0x0000010500000006L;

            // optional int32 ffs_ready = 7;
            public static final long FFS_READY = 0x0000010500000007L;

            // optional int32 mtp_device_type = 8;
            public static final long MTP_DEVICE_TYPE = 0x0000010500000008L;

            // optional string state = 9;
            public static final long STATE = 0x0000010900000009L;

        }

        // optional int32 boot_completed = 1;
        public static final long BOOT_COMPLETED = 0x0000010500000001L;

        // optional int32 boot_from_charger_mode = 2;
        public static final long BOOT_FROM_CHARGER_MODE = 0x0000010500000002L;

        // optional int32 retaildemo_enabled = 3;
        public static final long RETAILDEMO_ENABLED = 0x0000010500000003L;

        // optional string shutdown_requested = 4;
        public static final long SHUTDOWN_REQUESTED = 0x0000010900000004L;

        // optional .android.os.SystemPropertiesProto.Sys.Usb usb = 5;
        public static final long USB = 0x0000010b00000005L;

    }

    // repeated .android.os.SystemPropertiesProto.Property extra_properties = 1;
    public static final long EXTRA_PROPERTIES = 0x0000020b00000001L;

    // optional .android.os.SystemPropertiesProto.AacDrc aac_drc = 2;
    public static final long AAC_DRC = 0x0000010b00000002L;

    // optional .android.os.SystemPropertiesProto.Aaudio aaudio = 3;
    public static final long AAUDIO = 0x0000010b00000003L;

    // optional int32 af_fast_track_multiplier = 4;
    public static final long AF_FAST_TRACK_MULTIPLIER = 0x0000010500000004L;

    // optional .android.os.SystemPropertiesProto.Camera camera = 5;
    public static final long CAMERA = 0x0000010b00000005L;

    // optional .android.os.SystemPropertiesProto.DalvikVm dalvik_vm = 6;
    public static final long DALVIK_VM = 0x0000010b00000006L;

    // optional bool drm_64bit_enabled = 7;
    public static final long DRM_64BIT_ENABLED = 0x0000010800000007L;

    // optional bool drm_service_enabled = 8;
    public static final long DRM_SERVICE_ENABLED = 0x0000010800000008L;

    // optional bool dumpstate_dry_run = 9;
    public static final long DUMPSTATE_DRY_RUN = 0x0000010800000009L;

    // optional string gsm_sim_operator_numeric = 10;
    public static final long GSM_SIM_OPERATOR_NUMERIC = 0x000001090000000aL;

    // optional bool hal_instrumentation_enable = 11;
    public static final long HAL_INSTRUMENTATION_ENABLE = 0x000001080000000bL;

    // optional .android.os.SystemPropertiesProto.InitSvc init_svc = 12;
    public static final long INIT_SVC = 0x0000010b0000000cL;

    // optional bool keyguard_no_require_sim = 13;
    public static final long KEYGUARD_NO_REQUIRE_SIM = 0x000001080000000dL;

    // optional string libc_debug_malloc_options = 14;
    public static final long LIBC_DEBUG_MALLOC_OPTIONS = 0x000001090000000eL;

    // optional string libc_debug_malloc_program = 15;
    public static final long LIBC_DEBUG_MALLOC_PROGRAM = 0x000001090000000fL;

    // optional .android.os.SystemPropertiesProto.Log log = 16;
    public static final long LOG = 0x0000010b00000010L;

    // optional bool media_mediadrmservice_enable = 17;
    public static final long MEDIA_MEDIADRMSERVICE_ENABLE = 0x0000010800000011L;

    // optional bool media_recorder_show_manufacturer_and_model = 18;
    public static final long MEDIA_RECORDER_SHOW_MANUFACTURER_AND_MODEL = 0x0000010800000012L;

    // optional .android.os.SystemPropertiesProto.Persist persist = 19;
    public static final long PERSIST = 0x0000010b00000013L;

    // optional .android.os.SystemPropertiesProto.PmDexopt pm_dexopt = 20;
    public static final long PM_DEXOPT = 0x0000010b00000014L;

    // optional .android.os.SystemPropertiesProto.Ro ro = 21;
    public static final long RO = 0x0000010b00000015L;

    // optional string sendbug_preferred_domain = 22;
    public static final long SENDBUG_PREFERRED_DOMAIN = 0x0000010900000016L;

    // optional int32 service_bootanim_exit = 23;
    public static final long SERVICE_BOOTANIM_EXIT = 0x0000010500000017L;

    // optional .android.os.SystemPropertiesProto.Sys sys = 24;
    public static final long SYS = 0x0000010b00000018L;

    // optional int32 telephony_lteOnCdmaDevice = 25;
    public static final long TELEPHONY_LTE_ON_CDMA_DEVICE = 0x0000010500000019L;

    // optional int32 tombstoned_max_tombstone_count = 26;
    public static final long TOMBSTONED_MAX_TOMBSTONE_COUNT = 0x000001050000001aL;

    // optional string vold_decrypt = 27;
    public static final long VOLD_DECRYPT = 0x000001090000001bL;

    // optional int32 vold_post_fs_data_done = 28;
    public static final long VOLD_POST_FS_DATA_DONE = 0x000001050000001cL;

    // optional int32 vts_native_server_on = 29;
    public static final long VTS_NATIVE_SERVER_ON = 0x000001050000001dL;

    // optional string wifi_direct_interface = 30;
    public static final long WIFI_DIRECT_INTERFACE = 0x000001090000001eL;

    // optional string wifi_interface = 31;
    public static final long WIFI_INTERFACE = 0x000001090000001fL;

}

