// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/os/batterystats.proto

package android.os;

/** @hide */
// message UidProto
public final class UidProto {

    // message Package
    public final class Package {

        // message Service
        public final class Service {

            // optional string name = 1;
            public static final long NAME = 0x0000010900000001L;

            // optional int64 start_duration_ms = 2;
            public static final long START_DURATION_MS = 0x0000010300000002L;

            // optional int32 start_count = 3;
            public static final long START_COUNT = 0x0000010500000003L;

            // optional int32 launch_count = 4;
            public static final long LAUNCH_COUNT = 0x0000010500000004L;

        }

        // optional string name = 1;
        public static final long NAME = 0x0000010900000001L;

        // repeated .android.os.UidProto.Package.Service services = 2;
        public static final long SERVICES = 0x0000020b00000002L;

    }

    // message BluetoothMisc
    public final class BluetoothMisc {

        // optional .android.os.TimerProto apportioned_ble_scan = 1;
        public static final long APPORTIONED_BLE_SCAN = 0x0000010b00000001L;

        // optional .android.os.TimerProto background_ble_scan = 2;
        public static final long BACKGROUND_BLE_SCAN = 0x0000010b00000002L;

        // optional .android.os.TimerProto unoptimized_ble_scan = 3;
        public static final long UNOPTIMIZED_BLE_SCAN = 0x0000010b00000003L;

        // optional .android.os.TimerProto background_unoptimized_ble_scan = 4;
        public static final long BACKGROUND_UNOPTIMIZED_BLE_SCAN = 0x0000010b00000004L;

        // optional int32 ble_scan_result_count = 5;
        public static final long BLE_SCAN_RESULT_COUNT = 0x0000010500000005L;

        // optional int32 background_ble_scan_result_count = 6;
        public static final long BACKGROUND_BLE_SCAN_RESULT_COUNT = 0x0000010500000006L;

    }

    // message Cpu
    public final class Cpu {

        // enum ProcessState
        public static final int TOP = 0;
        public static final int FOREGROUND_SERVICE = 1;
        public static final int FOREGROUND = 2;
        public static final int BACKGROUND = 3;
        public static final int TOP_SLEEPING = 4;
        public static final int HEAVY_WEIGHT = 5;
        public static final int CACHED = 6;

        // message ByFrequency
        public final class ByFrequency {

            // optional int32 frequency_index = 1;
            public static final long FREQUENCY_INDEX = 0x0000010500000001L;

            // optional int64 total_duration_ms = 2;
            public static final long TOTAL_DURATION_MS = 0x0000010300000002L;

            // optional int64 screen_off_duration_ms = 3;
            public static final long SCREEN_OFF_DURATION_MS = 0x0000010300000003L;

        }

        // message ByProcessState
        public final class ByProcessState {

            // optional .android.os.UidProto.Cpu.ProcessState process_state = 1;
            public static final long PROCESS_STATE = 0x0000010e00000001L;

            // repeated .android.os.UidProto.Cpu.ByFrequency by_frequency = 2;
            public static final long BY_FREQUENCY = 0x0000020b00000002L;

        }

        // optional int64 user_duration_ms = 1;
        public static final long USER_DURATION_MS = 0x0000010300000001L;

        // optional int64 system_duration_ms = 2;
        public static final long SYSTEM_DURATION_MS = 0x0000010300000002L;

        // repeated .android.os.UidProto.Cpu.ByFrequency by_frequency = 3;
        public static final long BY_FREQUENCY = 0x0000020b00000003L;

        // repeated .android.os.UidProto.Cpu.ByProcessState by_process_state = 4;
        public static final long BY_PROCESS_STATE = 0x0000020b00000004L;

    }

    // message Job
    public final class Job {

        // optional string name = 1;
        public static final long NAME = 0x0000010900000001L;

        // optional .android.os.TimerProto total = 2;
        public static final long TOTAL = 0x0000010b00000002L;

        // optional .android.os.TimerProto background = 3;
        public static final long BACKGROUND = 0x0000010b00000003L;

    }

    // message JobCompletion
    public final class JobCompletion {

        // message ReasonCount
        public final class ReasonCount {

            // optional .android.app.job.StopReasonEnum name = 1;
            public static final long NAME = 0x0000010e00000001L;

            // optional int32 count = 2;
            public static final long COUNT = 0x0000010500000002L;

        }

        // optional string name = 1;
        public static final long NAME = 0x0000010900000001L;

        // repeated .android.os.UidProto.JobCompletion.ReasonCount reason_count = 2;
        public static final long REASON_COUNT = 0x0000020b00000002L;

    }

    // message Network
    public final class Network {

        // optional int64 mobile_bytes_rx = 1;
        public static final long MOBILE_BYTES_RX = 0x0000010300000001L;

        // optional int64 mobile_bytes_tx = 2;
        public static final long MOBILE_BYTES_TX = 0x0000010300000002L;

        // optional int64 wifi_bytes_rx = 3;
        public static final long WIFI_BYTES_RX = 0x0000010300000003L;

        // optional int64 wifi_bytes_tx = 4;
        public static final long WIFI_BYTES_TX = 0x0000010300000004L;

        // optional int64 bt_bytes_rx = 5;
        public static final long BT_BYTES_RX = 0x0000010300000005L;

        // optional int64 bt_bytes_tx = 6;
        public static final long BT_BYTES_TX = 0x0000010300000006L;

        // optional int64 mobile_packets_rx = 7;
        public static final long MOBILE_PACKETS_RX = 0x0000010300000007L;

        // optional int64 mobile_packets_tx = 8;
        public static final long MOBILE_PACKETS_TX = 0x0000010300000008L;

        // optional int64 wifi_packets_rx = 9;
        public static final long WIFI_PACKETS_RX = 0x0000010300000009L;

        // optional int64 wifi_packets_tx = 10;
        public static final long WIFI_PACKETS_TX = 0x000001030000000aL;

        // optional int64 mobile_active_duration_ms = 11;
        public static final long MOBILE_ACTIVE_DURATION_MS = 0x000001030000000bL;

        // optional int32 mobile_active_count = 12;
        public static final long MOBILE_ACTIVE_COUNT = 0x000001050000000cL;

        // optional int32 mobile_wakeup_count = 13;
        public static final long MOBILE_WAKEUP_COUNT = 0x000001050000000dL;

        // optional int32 wifi_wakeup_count = 14;
        public static final long WIFI_WAKEUP_COUNT = 0x000001050000000eL;

        // optional int64 mobile_bytes_bg_rx = 15;
        public static final long MOBILE_BYTES_BG_RX = 0x000001030000000fL;

        // optional int64 mobile_bytes_bg_tx = 16;
        public static final long MOBILE_BYTES_BG_TX = 0x0000010300000010L;

        // optional int64 wifi_bytes_bg_rx = 17;
        public static final long WIFI_BYTES_BG_RX = 0x0000010300000011L;

        // optional int64 wifi_bytes_bg_tx = 18;
        public static final long WIFI_BYTES_BG_TX = 0x0000010300000012L;

        // optional int64 mobile_packets_bg_rx = 19;
        public static final long MOBILE_PACKETS_BG_RX = 0x0000010300000013L;

        // optional int64 mobile_packets_bg_tx = 20;
        public static final long MOBILE_PACKETS_BG_TX = 0x0000010300000014L;

        // optional int64 wifi_packets_bg_rx = 21;
        public static final long WIFI_PACKETS_BG_RX = 0x0000010300000015L;

        // optional int64 wifi_packets_bg_tx = 22;
        public static final long WIFI_PACKETS_BG_TX = 0x0000010300000016L;

    }

    // message PowerUseItem
    public final class PowerUseItem {

        // optional double computed_power_mah = 1;
        public static final long COMPUTED_POWER_MAH = 0x0000010100000001L;

        // optional bool should_hide = 2;
        public static final long SHOULD_HIDE = 0x0000010800000002L;

        // optional double screen_power_mah = 3;
        public static final long SCREEN_POWER_MAH = 0x0000010100000003L;

        // optional double proportional_smear_mah = 4;
        public static final long PROPORTIONAL_SMEAR_MAH = 0x0000010100000004L;

    }

    // message Process
    public final class Process {

        // optional string name = 1;
        public static final long NAME = 0x0000010900000001L;

        // optional int64 user_duration_ms = 2;
        public static final long USER_DURATION_MS = 0x0000010300000002L;

        // optional int64 system_duration_ms = 3;
        public static final long SYSTEM_DURATION_MS = 0x0000010300000003L;

        // optional int64 foreground_duration_ms = 4;
        public static final long FOREGROUND_DURATION_MS = 0x0000010300000004L;

        // optional int32 start_count = 5;
        public static final long START_COUNT = 0x0000010500000005L;

        // optional int32 anr_count = 6;
        public static final long ANR_COUNT = 0x0000010500000006L;

        // optional int32 crash_count = 7;
        public static final long CRASH_COUNT = 0x0000010500000007L;

    }

    // message StateTime
    public final class StateTime {

        // enum State
        public static final int PROCESS_STATE_TOP = 0;
        public static final int PROCESS_STATE_FOREGROUND_SERVICE = 1;
        public static final int PROCESS_STATE_FOREGROUND = 2;
        public static final int PROCESS_STATE_BACKGROUND = 3;
        public static final int PROCESS_STATE_TOP_SLEEPING = 4;
        public static final int PROCESS_STATE_HEAVY_WEIGHT = 5;
        public static final int PROCESS_STATE_CACHED = 6;

        // optional .android.os.UidProto.StateTime.State state = 1;
        public static final long STATE = 0x0000010e00000001L;

        // optional int64 duration_ms = 2;
        public static final long DURATION_MS = 0x0000010300000002L;

    }

    // message Sensor
    public final class Sensor {

        // optional int32 id = 1;
        public static final long ID = 0x0000010500000001L;

        // optional .android.os.TimerProto apportioned = 2;
        public static final long APPORTIONED = 0x0000010b00000002L;

        // optional .android.os.TimerProto background = 3;
        public static final long BACKGROUND = 0x0000010b00000003L;

    }

    // message Sync
    public final class Sync {

        // optional string name = 1;
        public static final long NAME = 0x0000010900000001L;

        // optional .android.os.TimerProto total = 2;
        public static final long TOTAL = 0x0000010b00000002L;

        // optional .android.os.TimerProto background = 3;
        public static final long BACKGROUND = 0x0000010b00000003L;

    }

    // message UserActivity
    public final class UserActivity {

        // optional .android.os.PowerManagerProto.UserActivityEvent name = 1;
        public static final long NAME = 0x0000010e00000001L;

        // optional int32 count = 2;
        public static final long COUNT = 0x0000010500000002L;

    }

    // message AggregatedWakelock
    public final class AggregatedWakelock {

        // optional int64 partial_duration_ms = 1;
        public static final long PARTIAL_DURATION_MS = 0x0000010300000001L;

        // optional int64 background_partial_duration_ms = 2;
        public static final long BACKGROUND_PARTIAL_DURATION_MS = 0x0000010300000002L;

    }

    // message Wakelock
    public final class Wakelock {

        // optional string name = 1;
        public static final long NAME = 0x0000010900000001L;

        // optional .android.os.TimerProto full = 2;
        public static final long FULL = 0x0000010b00000002L;

        // optional .android.os.TimerProto partial = 3;
        public static final long PARTIAL = 0x0000010b00000003L;

        // optional .android.os.TimerProto background_partial = 4;
        public static final long BACKGROUND_PARTIAL = 0x0000010b00000004L;

        // optional .android.os.TimerProto window = 5;
        public static final long WINDOW = 0x0000010b00000005L;

    }

    // message WakeupAlarm
    public final class WakeupAlarm {

        // optional string name = 1;
        public static final long NAME = 0x0000010900000001L;

        // optional int32 count = 2;
        public static final long COUNT = 0x0000010500000002L;

    }

    // message Wifi
    public final class Wifi {

        // optional int64 full_wifi_lock_duration_ms = 1;
        public static final long FULL_WIFI_LOCK_DURATION_MS = 0x0000010300000001L;

        // optional int64 running_duration_ms = 2;
        public static final long RUNNING_DURATION_MS = 0x0000010300000002L;

        // optional .android.os.TimerProto apportioned_scan = 3;
        public static final long APPORTIONED_SCAN = 0x0000010b00000003L;

        // optional .android.os.TimerProto background_scan = 4;
        public static final long BACKGROUND_SCAN = 0x0000010b00000004L;

    }

    // optional int32 uid = 1;
    public static final long UID = 0x0000010500000001L;

    // repeated .android.os.UidProto.Package packages = 2;
    public static final long PACKAGES = 0x0000020b00000002L;

    // optional .android.os.ControllerActivityProto bluetooth_controller = 3;
    public static final long BLUETOOTH_CONTROLLER = 0x0000010b00000003L;

    // optional .android.os.ControllerActivityProto modem_controller = 4;
    public static final long MODEM_CONTROLLER = 0x0000010b00000004L;

    // optional .android.os.ControllerActivityProto wifi_controller = 5;
    public static final long WIFI_CONTROLLER = 0x0000010b00000005L;

    // optional .android.os.UidProto.BluetoothMisc bluetooth_misc = 6;
    public static final long BLUETOOTH_MISC = 0x0000010b00000006L;

    // optional .android.os.UidProto.Cpu cpu = 7;
    public static final long CPU = 0x0000010b00000007L;

    // optional .android.os.TimerProto audio = 8;
    public static final long AUDIO = 0x0000010b00000008L;

    // optional .android.os.TimerProto camera = 9;
    public static final long CAMERA = 0x0000010b00000009L;

    // optional .android.os.TimerProto flashlight = 10;
    public static final long FLASHLIGHT = 0x0000010b0000000aL;

    // optional .android.os.TimerProto foreground_activity = 11;
    public static final long FOREGROUND_ACTIVITY = 0x0000010b0000000bL;

    // optional .android.os.TimerProto foreground_service = 12;
    public static final long FOREGROUND_SERVICE = 0x0000010b0000000cL;

    // optional .android.os.TimerProto vibrator = 13;
    public static final long VIBRATOR = 0x0000010b0000000dL;

    // optional .android.os.TimerProto video = 14;
    public static final long VIDEO = 0x0000010b0000000eL;

    // repeated .android.os.UidProto.Job jobs = 15;
    public static final long JOBS = 0x0000020b0000000fL;

    // repeated .android.os.UidProto.JobCompletion job_completion = 16;
    public static final long JOB_COMPLETION = 0x0000020b00000010L;

    // optional .android.os.UidProto.Network network = 17;
    public static final long NETWORK = 0x0000010b00000011L;

    // optional .android.os.UidProto.PowerUseItem power_use_item = 18;
    public static final long POWER_USE_ITEM = 0x0000010b00000012L;

    // repeated .android.os.UidProto.Process process = 19;
    public static final long PROCESS = 0x0000020b00000013L;

    // repeated .android.os.UidProto.StateTime states = 20;
    public static final long STATES = 0x0000020b00000014L;

    // repeated .android.os.UidProto.Sensor sensors = 21;
    public static final long SENSORS = 0x0000020b00000015L;

    // repeated .android.os.UidProto.Sync syncs = 22;
    public static final long SYNCS = 0x0000020b00000016L;

    // repeated .android.os.UidProto.UserActivity user_activity = 23;
    public static final long USER_ACTIVITY = 0x0000020b00000017L;

    // optional .android.os.UidProto.AggregatedWakelock aggregated_wakelock = 24;
    public static final long AGGREGATED_WAKELOCK = 0x0000010b00000018L;

    // repeated .android.os.UidProto.Wakelock wakelocks = 25;
    public static final long WAKELOCKS = 0x0000020b00000019L;

    // repeated .android.os.UidProto.WakeupAlarm wakeup_alarm = 26;
    public static final long WAKEUP_ALARM = 0x0000020b0000001aL;

    // optional .android.os.UidProto.Wifi wifi = 27;
    public static final long WIFI = 0x0000010b0000001bL;

    // optional .android.os.TimerProto wifi_multicast_wakelock = 28;
    public static final long WIFI_MULTICAST_WAKELOCK = 0x0000010b0000001cL;

}

