// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/server/powermanagerservice.proto

package com.android.server.power;

/** @hide */
// message WakeLockProto
public final class WakeLockProto {

    // message WakeLockFlagsProto
    public final class WakeLockFlagsProto {

        // optional bool is_acquire_causes_wakeup = 1;
        public static final long IS_ACQUIRE_CAUSES_WAKEUP = 0x0000010800000001L;

        // optional bool is_on_after_release = 2;
        public static final long IS_ON_AFTER_RELEASE = 0x0000010800000002L;

    }

    // optional .android.os.WakeLockLevelEnum lock_level = 1;
    public static final long LOCK_LEVEL = 0x0000010e00000001L;

    // optional string tag = 2;
    public static final long TAG = 0x0000010900000002L;

    // optional .com.android.server.power.WakeLockProto.WakeLockFlagsProto flags = 3;
    public static final long FLAGS = 0x0000010b00000003L;

    // optional bool is_disabled = 4;
    public static final long IS_DISABLED = 0x0000010800000004L;

    // optional int64 acq_ms = 5;
    public static final long ACQ_MS = 0x0000010300000005L;

    // optional bool is_notified_long = 6;
    public static final long IS_NOTIFIED_LONG = 0x0000010800000006L;

    // optional int32 uid = 7;
    public static final long UID = 0x0000010500000007L;

    // optional int32 pid = 8;
    public static final long PID = 0x0000010500000008L;

    // optional .android.os.WorkSourceProto work_source = 9;
    public static final long WORK_SOURCE = 0x0000010b00000009L;

}

