// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/service/usb.proto

package android.service.usb;

/** @hide */
// message UsbAlsaManagerProto
public final class UsbAlsaManagerProto {

    // optional int32 cards_parser = 1;
    public static final long CARDS_PARSER = 0x0000010500000001L;

    // repeated .android.service.usb.UsbAlsaDeviceProto alsa_devices = 2;
    public static final long ALSA_DEVICES = 0x0000020b00000002L;

    // repeated .android.service.usb.UsbMidiDeviceProto midi_devices = 3;
    public static final long MIDI_DEVICES = 0x0000020b00000003L;

}

