// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/service/usb.proto

package android.service.usb;

/** @hide */
// message UsbAccessoryProto
public final class UsbAccessoryProto {

    // optional string manufacturer = 1;
    public static final long MANUFACTURER = 0x0000010900000001L;

    // optional string model = 2;
    public static final long MODEL = 0x0000010900000002L;

    // optional string description = 3;
    public static final long DESCRIPTION = 0x0000010900000003L;

    // optional string version = 4;
    public static final long VERSION = 0x0000010900000004L;

    // optional string uri = 5;
    public static final long URI = 0x0000010900000005L;

    // optional string serial = 6;
    public static final long SERIAL = 0x0000010900000006L;

}

