// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/service/usb.proto

package android.service.usb;

/** @hide */
// message UsbPortManagerProto
public final class UsbPortManagerProto {

    // optional bool is_simulation_active = 1;
    public static final long IS_SIMULATION_ACTIVE = 0x0000010800000001L;

    // repeated .android.service.usb.UsbPortInfoProto usb_ports = 2;
    public static final long USB_PORTS = 0x0000020b00000002L;

}

