// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/service/usb.proto

package android.service.usb;

/** @hide */
// message UsbPortInfoProto
public final class UsbPortInfoProto {

    // optional .android.service.usb.UsbPortProto port = 1;
    public static final long PORT = 0x0000010b00000001L;

    // optional .android.service.usb.UsbPortStatusProto status = 2;
    public static final long STATUS = 0x0000010b00000002L;

    // optional bool can_change_mode = 3;
    public static final long CAN_CHANGE_MODE = 0x0000010800000003L;

    // optional bool can_change_power_role = 4;
    public static final long CAN_CHANGE_POWER_ROLE = 0x0000010800000004L;

    // optional bool can_change_data_role = 5;
    public static final long CAN_CHANGE_DATA_ROLE = 0x0000010800000005L;

}

