// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/service/usb.proto

package android.service.usb;

/** @hide */
// message UsbPortProto
public final class UsbPortProto {

    // enum Mode
    public static final int MODE_NONE = 0;
    public static final int MODE_UFP = 1;
    public static final int MODE_DFP = 2;
    public static final int MODE_DRP = 3;
    public static final int MODE_AUDIO_ACCESSORY = 4;
    public static final int MODE_DEBUG_ACCESSORY = 8;

    // optional string id = 1;
    public static final long ID = 0x0000010900000001L;

    // repeated .android.service.usb.UsbPortProto.Mode supported_modes = 2;
    public static final long SUPPORTED_MODES = 0x0000020e00000002L;

}

