// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/service/usb.proto

package android.service.usb;

/** @hide */
// message UsbUserSettingsManagerProto
public final class UsbUserSettingsManagerProto {

    // optional int32 user_id = 1;
    public static final long USER_ID = 0x0000010500000001L;

    // repeated .android.service.usb.UsbSettingsDevicePermissionProto device_permissions = 2;
    public static final long DEVICE_PERMISSIONS = 0x0000020b00000002L;

    // repeated .android.service.usb.UsbSettingsAccessoryPermissionProto accessory_permissions = 3;
    public static final long ACCESSORY_PERMISSIONS = 0x0000020b00000003L;

}

