// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/util/common.proto

package android.util;

/** @hide */
// message Duration
public final class Duration {

    // optional int64 start_ms = 1;
    public static final long START_MS = 0x0000010300000001L;

    // optional int64 end_ms = 2;
    public static final long END_MS = 0x0000010300000002L;

}

