// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/util/event_log_tags.proto

package android.util;

/** @hide */
// message EventLogTag
public final class EventLogTag {

    // message ValueDescriptor
    public final class ValueDescriptor {

        // enum DataType
        public static final int UNKNOWN = 0;
        public static final int INT = 1;
        public static final int LONG = 2;
        public static final int STRING = 3;
        public static final int LIST = 4;
        public static final int FLOAT = 5;

        // enum DataUnit
        public static final int UNSET = 0;
        public static final int OBJECTS = 1;
        public static final int BYTES = 2;
        public static final int MILLISECONDS = 3;
        public static final int ALLOCATIONS = 4;
        public static final int ID = 5;
        public static final int PERCENT = 6;
        public static final int SECONDS = 115;

        // optional string name = 1;
        public static final long NAME = 0x0000010900000001L;

        // optional .android.util.EventLogTag.ValueDescriptor.DataType type = 2;
        public static final long TYPE = 0x0000010e00000002L;

        // optional .android.util.EventLogTag.ValueDescriptor.DataUnit unit = 3;
        public static final long UNIT = 0x0000010e00000003L;

    }

    // optional uint32 tag_number = 1;
    public static final long TAG_NUMBER = 0x0000010d00000001L;

    // optional string tag_name = 2;
    public static final long TAG_NAME = 0x0000010900000002L;

    // repeated .android.util.EventLogTag.ValueDescriptor value_descriptors = 3;
    public static final long VALUE_DESCRIPTORS = 0x0000020b00000003L;

}

