// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/graphics/rect.proto

package android.graphics;

/** @hide */
// message RectProto
public final class RectProto {

    // optional int32 left = 1;
    public static final long LEFT = 0x0000010500000001L;

    // optional int32 top = 2;
    public static final long TOP = 0x0000010500000002L;

    // optional int32 right = 3;
    public static final long RIGHT = 0x0000010500000003L;

    // optional int32 bottom = 4;
    public static final long BOTTOM = 0x0000010500000004L;

}

