// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/service/diskstats.proto

package android.service.diskstats;

/** @hide */
// message DiskStatsServiceDumpProto
public final class DiskStatsServiceDumpProto {

    // enum EncryptionType
    public static final int ENCRYPTION_UNKNOWN = 0;
    public static final int ENCRYPTION_NONE = 1;
    public static final int ENCRYPTION_FULL_DISK = 2;
    public static final int ENCRYPTION_FILE_BASED = 3;

    // optional bool has_test_error = 1;
    public static final long HAS_TEST_ERROR = 0x0000010800000001L;

    // optional string error_message = 2;
    public static final long ERROR_MESSAGE = 0x0000010900000002L;

    // optional int32 write_512b_latency_millis = 3;
    public static final long WRITE_512B_LATENCY_MILLIS = 0x0000010500000003L;

    // repeated .android.service.diskstats.DiskStatsFreeSpaceProto partitions_free_space = 4;
    public static final long PARTITIONS_FREE_SPACE = 0x0000020b00000004L;

    // optional .android.service.diskstats.DiskStatsServiceDumpProto.EncryptionType encryption = 5;
    public static final long ENCRYPTION = 0x0000010e00000005L;

    // optional .android.service.diskstats.DiskStatsCachedValuesProto cached_folder_sizes = 6;
    public static final long CACHED_FOLDER_SIZES = 0x0000010b00000006L;

    // optional int32 benchmarked_write_speed_kbps = 7;
    public static final long BENCHMARKED_WRITE_SPEED_KBPS = 0x0000010500000007L;

}

