// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/service/diskstats.proto

package android.service.diskstats;

/** @hide */
// message DiskStatsFreeSpaceProto
public final class DiskStatsFreeSpaceProto {

    // enum Folder
    public static final int FOLDER_DATA = 0;
    public static final int FOLDER_CACHE = 1;
    public static final int FOLDER_SYSTEM = 2;

    // optional .android.service.diskstats.DiskStatsFreeSpaceProto.Folder folder = 1;
    public static final long FOLDER = 0x0000010e00000001L;

    // optional int64 available_space_kb = 2;
    public static final long AVAILABLE_SPACE_KB = 0x0000010300000002L;

    // optional int64 total_space_kb = 3;
    public static final long TOTAL_SPACE_KB = 0x0000010300000003L;

}

