// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/providers/settings/system.proto

package android.providers.settings;

/** @hide */
// message SystemSettingsProto
public final class SystemSettingsProto {

    // message Alarm
    public final class Alarm {

        // optional .android.providers.settings.SettingProto default_uri = 1;
        public static final long DEFAULT_URI = 0x0000010b00000001L;

        // optional .android.providers.settings.SettingProto alert_cache = 2;
        public static final long ALERT_CACHE = 0x0000010b00000002L;

    }

    // message Bluetooth
    public final class Bluetooth {

        // optional .android.providers.settings.SettingProto discoverability = 1;
        public static final long DISCOVERABILITY = 0x0000010b00000001L;

        // optional .android.providers.settings.SettingProto discoverability_timeout_secs = 2;
        public static final long DISCOVERABILITY_TIMEOUT_SECS = 0x0000010b00000002L;

    }

    // message DevOptions
    public final class DevOptions {

        // optional .android.providers.settings.SettingProto pointer_location = 1;
        public static final long POINTER_LOCATION = 0x0000010b00000001L;

        // optional .android.providers.settings.SettingProto show_touches = 2;
        public static final long SHOW_TOUCHES = 0x0000010b00000002L;

        // optional .android.providers.settings.SettingProto window_orientation_listener_log = 3;
        public static final long WINDOW_ORIENTATION_LISTENER_LOG = 0x0000010b00000003L;

    }

    // message DtmfTone
    public final class DtmfTone {

        // optional .android.providers.settings.SettingProto play_when_dialing = 1;
        public static final long PLAY_WHEN_DIALING = 0x0000010b00000001L;

        // optional .android.providers.settings.SettingProto type_played_when_dialing = 2;
        public static final long TYPE_PLAYED_WHEN_DIALING = 0x0000010b00000002L;

    }

    // message HapticFeedback
    public final class HapticFeedback {

        // optional .android.providers.settings.SettingProto enabled = 1;
        public static final long ENABLED = 0x0000010b00000001L;

        // optional .android.providers.settings.SettingProto intensity = 2;
        public static final long INTENSITY = 0x0000010b00000002L;

    }

    // message Lockscreen
    public final class Lockscreen {

        // optional .android.providers.settings.SettingProto sounds_enabled = 1;
        public static final long SOUNDS_ENABLED = 0x0000010b00000001L;

        // optional .android.providers.settings.SettingProto disabled = 2;
        public static final long DISABLED = 0x0000010b00000002L;

    }

    // message Notification
    public final class Notification {

        // optional .android.providers.settings.SettingProto sound = 1;
        public static final long SOUND = 0x0000010b00000001L;

        // optional .android.providers.settings.SettingProto sound_cache = 2;
        public static final long SOUND_CACHE = 0x0000010b00000002L;

        // optional .android.providers.settings.SettingProto light_pulse = 3;
        public static final long LIGHT_PULSE = 0x0000010b00000003L;

        // optional .android.providers.settings.SettingProto vibration_intensity = 4;
        public static final long VIBRATION_INTENSITY = 0x0000010b00000004L;

    }

    // message Ringtone
    public final class Ringtone {

        // optional .android.providers.settings.SettingProto default_uri = 1;
        public static final long DEFAULT_URI = 0x0000010b00000001L;

        // optional .android.providers.settings.SettingProto cache = 2;
        public static final long CACHE = 0x0000010b00000002L;

    }

    // message Rotation
    public final class Rotation {

        // optional .android.providers.settings.SettingProto accelerometer_rotation = 1;
        public static final long ACCELEROMETER_ROTATION = 0x0000010b00000001L;

        // optional .android.providers.settings.SettingProto user_rotation = 2;
        public static final long USER_ROTATION = 0x0000010b00000002L;

        // optional .android.providers.settings.SettingProto hide_rotation_lock_toggle_for_accessibility = 3;
        public static final long HIDE_ROTATION_LOCK_TOGGLE_FOR_ACCESSIBILITY = 0x0000010b00000003L;

    }

    // message Screen
    public final class Screen {

        // optional .android.providers.settings.SettingProto off_timeout = 1;
        public static final long OFF_TIMEOUT = 0x0000010b00000001L;

        // optional .android.providers.settings.SettingProto brightness = 2;
        public static final long BRIGHTNESS = 0x0000010b00000002L;

        // optional .android.providers.settings.SettingProto brightness_for_vr = 3;
        public static final long BRIGHTNESS_FOR_VR = 0x0000010b00000003L;

        // optional .android.providers.settings.SettingProto brightness_mode = 4;
        public static final long BRIGHTNESS_MODE = 0x0000010b00000004L;

        // optional .android.providers.settings.SettingProto auto_brightness_adj = 5;
        public static final long AUTO_BRIGHTNESS_ADJ = 0x0000010b00000005L;

    }

    // message Sip
    public final class Sip {

        // optional .android.providers.settings.SettingProto receive_calls = 1;
        public static final long RECEIVE_CALLS = 0x0000010b00000001L;

        // optional .android.providers.settings.SettingProto call_options = 2;
        public static final long CALL_OPTIONS = 0x0000010b00000002L;

        // optional .android.providers.settings.SettingProto always = 3;
        public static final long ALWAYS = 0x0000010b00000003L;

        // optional .android.providers.settings.SettingProto address_only = 4;
        public static final long ADDRESS_ONLY = 0x0000010b00000004L;

    }

    // message Text
    public final class Text {

        // optional .android.providers.settings.SettingProto auto_replace = 1;
        public static final long AUTO_REPLACE = 0x0000010b00000001L;

        // optional .android.providers.settings.SettingProto auto_caps = 2;
        public static final long AUTO_CAPS = 0x0000010b00000002L;

        // optional .android.providers.settings.SettingProto auto_punctuate = 3;
        public static final long AUTO_PUNCTUATE = 0x0000010b00000003L;

        // optional .android.providers.settings.SettingProto show_password = 4;
        public static final long SHOW_PASSWORD = 0x0000010b00000004L;

    }

    // message Vibrate
    public final class Vibrate {

        // optional .android.providers.settings.SettingProto on = 1;
        public static final long ON = 0x0000010b00000001L;

        // optional .android.providers.settings.SettingProto input_devices = 2;
        public static final long INPUT_DEVICES = 0x0000010b00000002L;

        // optional .android.providers.settings.SettingProto in_silent = 3;
        public static final long IN_SILENT = 0x0000010b00000003L;

        // optional .android.providers.settings.SettingProto when_ringing = 4;
        public static final long WHEN_RINGING = 0x0000010b00000004L;

    }

    // message Volume
    public final class Volume {

        // optional .android.providers.settings.SettingProto ring = 1;
        public static final long RING = 0x0000010b00000001L;

        // optional .android.providers.settings.SettingProto system = 2;
        public static final long SYSTEM = 0x0000010b00000002L;

        // optional .android.providers.settings.SettingProto voice = 3;
        public static final long VOICE = 0x0000010b00000003L;

        // optional .android.providers.settings.SettingProto music = 4;
        public static final long MUSIC = 0x0000010b00000004L;

        // optional .android.providers.settings.SettingProto alarm = 5;
        public static final long ALARM = 0x0000010b00000005L;

        // optional .android.providers.settings.SettingProto notification = 6;
        public static final long NOTIFICATION = 0x0000010b00000006L;

        // optional .android.providers.settings.SettingProto bluetooth_sco = 7;
        public static final long BLUETOOTH_SCO = 0x0000010b00000007L;

        // optional .android.providers.settings.SettingProto accessibility = 8;
        public static final long ACCESSIBILITY = 0x0000010b00000008L;

        // optional .android.providers.settings.SettingProto master = 9;
        public static final long MASTER = 0x0000010b00000009L;

        // optional .android.providers.settings.SettingProto master_mono = 10;
        public static final long MASTER_MONO = 0x0000010b0000000aL;

        // optional .android.providers.settings.SettingProto mode_ringer_streams_affected = 11;
        public static final long MODE_RINGER_STREAMS_AFFECTED = 0x0000010b0000000bL;

        // optional .android.providers.settings.SettingProto mute_streams_affected = 12;
        public static final long MUTE_STREAMS_AFFECTED = 0x0000010b0000000cL;

    }

    // repeated .android.providers.settings.SettingsOperationProto historical_operations = 1;
    public static final long HISTORICAL_OPERATIONS = 0x0000020b00000001L;

    // optional .android.providers.settings.SettingProto advanced_settings = 2;
    public static final long ADVANCED_SETTINGS = 0x0000010b00000002L;

    // optional .android.providers.settings.SystemSettingsProto.Alarm alarm = 3;
    public static final long ALARM = 0x0000010b00000003L;

    // optional .android.providers.settings.SystemSettingsProto.Bluetooth bluetooth = 4;
    public static final long BLUETOOTH = 0x0000010b00000004L;

    // optional .android.providers.settings.SettingProto date_format = 5;
    public static final long DATE_FORMAT = 0x0000010b00000005L;

    // optional .android.providers.settings.SettingProto display_color_mode = 6;
    public static final long DISPLAY_COLOR_MODE = 0x0000010b00000006L;

    // optional .android.providers.settings.SystemSettingsProto.DevOptions developer_options = 7;
    public static final long DEVELOPER_OPTIONS = 0x0000010b00000007L;

    // optional .android.providers.settings.SystemSettingsProto.DtmfTone dtmf_tone = 8;
    public static final long DTMF_TONE = 0x0000010b00000008L;

    // optional .android.providers.settings.SettingProto egg_mode = 9;
    public static final long EGG_MODE = 0x0000010b00000009L;

    // optional .android.providers.settings.SettingProto end_button_behavior = 10;
    public static final long END_BUTTON_BEHAVIOR = 0x0000010b0000000aL;

    // optional .android.providers.settings.SettingProto font_scale = 11;
    public static final long FONT_SCALE = 0x0000010b0000000bL;

    // optional .android.providers.settings.SystemSettingsProto.HapticFeedback haptic_feedback = 12;
    public static final long HAPTIC_FEEDBACK = 0x0000010b0000000cL;

    // optional .android.providers.settings.SettingProto hearing_aid = 13;
    public static final long HEARING_AID = 0x0000010b0000000dL;

    // optional .android.providers.settings.SettingProto lock_to_app_enabled = 14;
    public static final long LOCK_TO_APP_ENABLED = 0x0000010b0000000eL;

    // optional .android.providers.settings.SystemSettingsProto.Lockscreen lockscreen = 15;
    public static final long LOCKSCREEN = 0x0000010b0000000fL;

    // optional .android.providers.settings.SettingProto media_button_receiver = 16;
    public static final long MEDIA_BUTTON_RECEIVER = 0x0000010b00000010L;

    // optional .android.providers.settings.SystemSettingsProto.Notification notification = 17;
    public static final long NOTIFICATION = 0x0000010b00000011L;

    // optional .android.providers.settings.SettingProto pointer_speed = 18;
    public static final long POINTER_SPEED = 0x0000010b00000012L;

    // optional .android.providers.settings.SystemSettingsProto.Ringtone ringtone = 19;
    public static final long RINGTONE = 0x0000010b00000013L;

    // optional .android.providers.settings.SystemSettingsProto.Rotation rotation = 20;
    public static final long ROTATION = 0x0000010b00000014L;

    // optional .android.providers.settings.SystemSettingsProto.Screen screen = 22;
    public static final long SCREEN = 0x0000010b00000016L;

    // optional .android.providers.settings.SettingProto setup_wizard_has_run = 23;
    public static final long SETUP_WIZARD_HAS_RUN = 0x0000010b00000017L;

    // optional .android.providers.settings.SettingProto show_battery_percent = 24;
    public static final long SHOW_BATTERY_PERCENT = 0x0000010b00000018L;

    // optional .android.providers.settings.SettingProto show_gtalk_service_status = 25;
    public static final long SHOW_GTALK_SERVICE_STATUS = 0x0000010b00000019L;

    // optional .android.providers.settings.SystemSettingsProto.Sip sip = 26;
    public static final long SIP = 0x0000010b0000001aL;

    // optional .android.providers.settings.SettingProto sound_effects_enabled = 27;
    public static final long SOUND_EFFECTS_ENABLED = 0x0000010b0000001bL;

    // optional .android.providers.settings.SettingProto system_locales = 28;
    public static final long SYSTEM_LOCALES = 0x0000010b0000001cL;

    // optional .android.providers.settings.SystemSettingsProto.Text text = 29;
    public static final long TEXT = 0x0000010b0000001dL;

    // optional .android.providers.settings.SettingProto time_12_24 = 30;
    public static final long TIME_12_24 = 0x0000010b0000001eL;

    // optional .android.providers.settings.SettingProto tty_mode = 31;
    public static final long TTY_MODE = 0x0000010b0000001fL;

    // optional .android.providers.settings.SystemSettingsProto.Vibrate vibrate = 32;
    public static final long VIBRATE = 0x0000010b00000020L;

    // optional .android.providers.settings.SystemSettingsProto.Volume volume = 33;
    public static final long VOLUME = 0x0000010b00000021L;

    // optional .android.providers.settings.SettingProto when_to_make_wifi_calls = 34;
    public static final long WHEN_TO_MAKE_WIFI_CALLS = 0x0000010b00000022L;

}

