// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/server/activitymanagerservice.proto

package com.android.server.am;

/** @hide */
// message ActivityManagerServiceProto
public final class ActivityManagerServiceProto {

    // optional .com.android.server.am.ActivityManagerServiceDumpActivitiesProto activities = 1;
    public static final long ACTIVITIES = 0x0000010b00000001L;

    // optional .com.android.server.am.ActivityManagerServiceDumpBroadcastsProto broadcasts = 2;
    public static final long BROADCASTS = 0x0000010b00000002L;

    // optional .com.android.server.am.ActivityManagerServiceDumpServicesProto services = 3;
    public static final long SERVICES = 0x0000010b00000003L;

    // optional .com.android.server.am.ActivityManagerServiceDumpProcessesProto processes = 4;
    public static final long PROCESSES = 0x0000010b00000004L;

}

