// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/server/activitymanagerservice.proto

package com.android.server.am;

/** @hide */
// message ActiveInstrumentationProto
public final class ActiveInstrumentationProto {

    // optional .android.content.ComponentNameProto class = 1;
    public static final long CLASS = 0x0000010b00000001L;

    // optional bool finished = 2;
    public static final long FINISHED = 0x0000010800000002L;

    // repeated .com.android.server.am.ProcessRecordProto running_processes = 3;
    public static final long RUNNING_PROCESSES = 0x0000020b00000003L;

    // repeated string target_processes = 4;
    public static final long TARGET_PROCESSES = 0x0000020900000004L;

    // optional .android.content.pm.ApplicationInfoProto target_info = 5;
    public static final long TARGET_INFO = 0x0000010b00000005L;

    // optional string profile_file = 6;
    public static final long PROFILE_FILE = 0x0000010900000006L;

    // optional string watcher = 7;
    public static final long WATCHER = 0x0000010900000007L;

    // optional string ui_automation_connection = 8;
    public static final long UI_AUTOMATION_CONNECTION = 0x0000010900000008L;

    // optional string arguments = 9;
    public static final long ARGUMENTS = 0x0000010900000009L;

}

