// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/server/activitymanagerservice.proto

package com.android.server.am;

/** @hide */
// message ActivityManagerServiceDumpProcessesProto
public final class ActivityManagerServiceDumpProcessesProto {

    // message LruProcesses
    public final class LruProcesses {

        // optional int32 size = 1;
        public static final long SIZE = 0x0000010500000001L;

        // optional int32 non_act_at = 2;
        public static final long NON_ACT_AT = 0x0000010500000002L;

        // optional int32 non_svc_at = 3;
        public static final long NON_SVC_AT = 0x0000010500000003L;

        // repeated .com.android.server.am.ProcessOomProto list = 4;
        public static final long LIST = 0x0000020b00000004L;

    }

    // message ScreenCompatPackage
    public final class ScreenCompatPackage {

        // optional string package = 1;
        public static final long PACKAGE = 0x0000010900000001L;

        // optional int32 mode = 2;
        public static final long MODE = 0x0000010500000002L;

    }

    // message UidObserverRegistrationProto
    public final class UidObserverRegistrationProto {

        // message ProcState
        public final class ProcState {

            // optional int32 uid = 1;
            public static final long UID = 0x0000010500000001L;

            // optional int32 state = 2;
            public static final long STATE = 0x0000010500000002L;

        }

        // optional int32 uid = 1;
        public static final long UID = 0x0000010500000001L;

        // optional string package = 2;
        public static final long PACKAGE = 0x0000010900000002L;

        // repeated .android.app.UidObserverFlag flags = 3;
        public static final long FLAGS = 0x0000020e00000003L;

        // optional int32 cut_point = 4;
        public static final long CUT_POINT = 0x0000010500000004L;

        // repeated .com.android.server.am.ActivityManagerServiceDumpProcessesProto.UidObserverRegistrationProto.ProcState last_proc_states = 5;
        public static final long LAST_PROC_STATES = 0x0000020b00000005L;

    }

    // message PendingTempWhitelist
    public final class PendingTempWhitelist {

        // optional int32 target_uid = 1;
        public static final long TARGET_UID = 0x0000010500000001L;

        // optional int64 duration_ms = 2;
        public static final long DURATION_MS = 0x0000010300000002L;

        // optional string tag = 3;
        public static final long TAG = 0x0000010900000003L;

    }

    // message SleepStatus
    public final class SleepStatus {

        // optional .android.os.PowerManagerInternalProto.Wakefulness wakefulness = 1;
        public static final long WAKEFULNESS = 0x0000010e00000001L;

        // repeated string sleep_tokens = 2;
        public static final long SLEEP_TOKENS = 0x0000020900000002L;

        // optional bool sleeping = 3;
        public static final long SLEEPING = 0x0000010800000003L;

        // optional bool shutting_down = 4;
        public static final long SHUTTING_DOWN = 0x0000010800000004L;

        // optional bool test_pss_mode = 5;
        public static final long TEST_PSS_MODE = 0x0000010800000005L;

    }

    // message Voice
    public final class Voice {

        // optional string session = 1;
        public static final long SESSION = 0x0000010900000001L;

        // optional .android.os.PowerManagerProto.WakeLock wakelock = 2;
        public static final long WAKELOCK = 0x0000010b00000002L;

    }

    // message DebugApp
    public final class DebugApp {

        // optional string debug_app = 1;
        public static final long DEBUG_APP = 0x0000010900000001L;

        // optional string orig_debug_app = 2;
        public static final long ORIG_DEBUG_APP = 0x0000010900000002L;

        // optional bool debug_transient = 3;
        public static final long DEBUG_TRANSIENT = 0x0000010800000003L;

        // optional bool orig_wait_for_debugger = 4;
        public static final long ORIG_WAIT_FOR_DEBUGGER = 0x0000010800000004L;

    }

    // message MemWatchProcess
    public final class MemWatchProcess {

        // message Process
        public final class Process {

            // message MemStats
            public final class MemStats {

                // optional int32 uid = 1;
                public static final long UID = 0x0000010500000001L;

                // optional string size = 2;
                public static final long SIZE = 0x0000010900000002L;

                // optional string report_to = 3;
                public static final long REPORT_TO = 0x0000010900000003L;

            }

            // optional string name = 1;
            public static final long NAME = 0x0000010900000001L;

            // repeated .com.android.server.am.ActivityManagerServiceDumpProcessesProto.MemWatchProcess.Process.MemStats mem_stats = 2;
            public static final long MEM_STATS = 0x0000020b00000002L;

        }

        // message Dump
        public final class Dump {

            // optional string proc_name = 1;
            public static final long PROC_NAME = 0x0000010900000001L;

            // optional string file = 2;
            public static final long FILE = 0x0000010900000002L;

            // optional int32 pid = 3;
            public static final long PID = 0x0000010500000003L;

            // optional int32 uid = 4;
            public static final long UID = 0x0000010500000004L;

        }

        // repeated .com.android.server.am.ActivityManagerServiceDumpProcessesProto.MemWatchProcess.Process procs = 1;
        public static final long PROCS = 0x0000020b00000001L;

        // optional .com.android.server.am.ActivityManagerServiceDumpProcessesProto.MemWatchProcess.Dump dump = 2;
        public static final long DUMP = 0x0000010b00000002L;

    }

    // message Profile
    public final class Profile {

        // optional string app_name = 1;
        public static final long APP_NAME = 0x0000010900000001L;

        // optional .com.android.server.am.ProcessRecordProto proc = 2;
        public static final long PROC = 0x0000010b00000002L;

        // optional .android.app.ProfilerInfoProto info = 3;
        public static final long INFO = 0x0000010b00000003L;

        // optional int32 type = 4;
        public static final long TYPE = 0x0000010500000004L;

    }

    // message Controller
    public final class Controller {

        // optional string controller = 1;
        public static final long CONTROLLER = 0x0000010900000001L;

        // optional bool is_a_monkey = 2;
        public static final long IS_A_MONKEY = 0x0000010800000002L;

    }

    // repeated .com.android.server.am.ProcessRecordProto procs = 1;
    public static final long PROCS = 0x0000020b00000001L;

    // repeated .com.android.server.am.ProcessRecordProto isolated_procs = 2;
    public static final long ISOLATED_PROCS = 0x0000020b00000002L;

    // repeated .com.android.server.am.ActiveInstrumentationProto active_instrumentations = 3;
    public static final long ACTIVE_INSTRUMENTATIONS = 0x0000020b00000003L;

    // repeated .com.android.server.am.UidRecordProto active_uids = 4;
    public static final long ACTIVE_UIDS = 0x0000020b00000004L;

    // repeated .com.android.server.am.UidRecordProto validate_uids = 5;
    public static final long VALIDATE_UIDS = 0x0000020b00000005L;

    // optional .com.android.server.am.ActivityManagerServiceDumpProcessesProto.LruProcesses lru_procs = 6;
    public static final long LRU_PROCS = 0x0000010b00000006L;

    // repeated .com.android.server.am.ProcessRecordProto pids_self_locked = 7;
    public static final long PIDS_SELF_LOCKED = 0x0000020b00000007L;

    // repeated .com.android.server.am.ImportanceTokenProto important_procs = 8;
    public static final long IMPORTANT_PROCS = 0x0000020b00000008L;

    // repeated .com.android.server.am.ProcessRecordProto persistent_starting_procs = 9;
    public static final long PERSISTENT_STARTING_PROCS = 0x0000020b00000009L;

    // repeated .com.android.server.am.ProcessRecordProto removed_procs = 10;
    public static final long REMOVED_PROCS = 0x0000020b0000000aL;

    // repeated .com.android.server.am.ProcessRecordProto on_hold_procs = 11;
    public static final long ON_HOLD_PROCS = 0x0000020b0000000bL;

    // repeated .com.android.server.am.ProcessToGcProto gc_procs = 12;
    public static final long GC_PROCS = 0x0000020b0000000cL;

    // optional .com.android.server.am.AppErrorsProto app_errors = 13;
    public static final long APP_ERRORS = 0x0000010b0000000dL;

    // optional .com.android.server.am.UserControllerProto user_controller = 14;
    public static final long USER_CONTROLLER = 0x0000010b0000000eL;

    // optional .com.android.server.am.ProcessRecordProto home_proc = 15;
    public static final long HOME_PROC = 0x0000010b0000000fL;

    // optional .com.android.server.am.ProcessRecordProto previous_proc = 16;
    public static final long PREVIOUS_PROC = 0x0000010b00000010L;

    // optional int64 previous_proc_visible_time_ms = 17;
    public static final long PREVIOUS_PROC_VISIBLE_TIME_MS = 0x0000010300000011L;

    // optional .com.android.server.am.ProcessRecordProto heavy_weight_proc = 18;
    public static final long HEAVY_WEIGHT_PROC = 0x0000010b00000012L;

    // optional .android.content.ConfigurationProto global_configuration = 19;
    public static final long GLOBAL_CONFIGURATION = 0x0000010b00000013L;

    // optional bool config_will_change = 21;
    public static final long CONFIG_WILL_CHANGE = 0x0000010800000015L;

    // repeated .com.android.server.am.ActivityManagerServiceDumpProcessesProto.ScreenCompatPackage screen_compat_packages = 22;
    public static final long SCREEN_COMPAT_PACKAGES = 0x0000020b00000016L;

    // repeated .com.android.server.am.ActivityManagerServiceDumpProcessesProto.UidObserverRegistrationProto uid_observers = 23;
    public static final long UID_OBSERVERS = 0x0000020b00000017L;

    // repeated int32 device_idle_whitelist = 24;
    public static final long DEVICE_IDLE_WHITELIST = 0x0000020500000018L;

    // repeated int32 device_idle_temp_whitelist = 25;
    public static final long DEVICE_IDLE_TEMP_WHITELIST = 0x0000020500000019L;

    // repeated .com.android.server.am.ActivityManagerServiceDumpProcessesProto.PendingTempWhitelist pending_temp_whitelist = 26;
    public static final long PENDING_TEMP_WHITELIST = 0x0000020b0000001aL;

    // optional .com.android.server.am.ActivityManagerServiceDumpProcessesProto.SleepStatus sleep_status = 27;
    public static final long SLEEP_STATUS = 0x0000010b0000001bL;

    // optional .com.android.server.am.ActivityManagerServiceDumpProcessesProto.Voice running_voice = 28;
    public static final long RUNNING_VOICE = 0x0000010b0000001cL;

    // optional .com.android.server.am.VrControllerProto vr_controller = 29;
    public static final long VR_CONTROLLER = 0x0000010b0000001dL;

    // optional .com.android.server.am.ActivityManagerServiceDumpProcessesProto.DebugApp debug = 30;
    public static final long DEBUG = 0x0000010b0000001eL;

    // optional .com.android.server.am.AppTimeTrackerProto current_tracker = 31;
    public static final long CURRENT_TRACKER = 0x0000010b0000001fL;

    // optional .com.android.server.am.ActivityManagerServiceDumpProcessesProto.MemWatchProcess mem_watch_processes = 32;
    public static final long MEM_WATCH_PROCESSES = 0x0000010b00000020L;

    // optional string track_allocation_app = 33;
    public static final long TRACK_ALLOCATION_APP = 0x0000010900000021L;

    // optional .com.android.server.am.ActivityManagerServiceDumpProcessesProto.Profile profile = 34;
    public static final long PROFILE = 0x0000010b00000022L;

    // optional string native_debugging_app = 35;
    public static final long NATIVE_DEBUGGING_APP = 0x0000010900000023L;

    // optional bool always_finish_activities = 36;
    public static final long ALWAYS_FINISH_ACTIVITIES = 0x0000010800000024L;

    // optional .com.android.server.am.ActivityManagerServiceDumpProcessesProto.Controller controller = 37;
    public static final long CONTROLLER = 0x0000010b00000025L;

    // optional int32 total_persistent_procs = 38;
    public static final long TOTAL_PERSISTENT_PROCS = 0x0000010500000026L;

    // optional bool processes_ready = 39;
    public static final long PROCESSES_READY = 0x0000010800000027L;

    // optional bool system_ready = 40;
    public static final long SYSTEM_READY = 0x0000010800000028L;

    // optional bool booted = 41;
    public static final long BOOTED = 0x0000010800000029L;

    // optional int32 factory_test = 42;
    public static final long FACTORY_TEST = 0x000001050000002aL;

    // optional bool booting = 43;
    public static final long BOOTING = 0x000001080000002bL;

    // optional bool call_finish_booting = 44;
    public static final long CALL_FINISH_BOOTING = 0x000001080000002cL;

    // optional bool boot_animation_complete = 45;
    public static final long BOOT_ANIMATION_COMPLETE = 0x000001080000002dL;

    // optional int64 last_power_check_uptime_ms = 46;
    public static final long LAST_POWER_CHECK_UPTIME_MS = 0x000001030000002eL;

    // optional .android.os.PowerManagerProto.WakeLock going_to_sleep = 47;
    public static final long GOING_TO_SLEEP = 0x0000010b0000002fL;

    // optional .android.os.PowerManagerProto.WakeLock launching_activity = 48;
    public static final long LAUNCHING_ACTIVITY = 0x0000010b00000030L;

    // optional int32 adj_seq = 49;
    public static final long ADJ_SEQ = 0x0000010500000031L;

    // optional int32 lru_seq = 50;
    public static final long LRU_SEQ = 0x0000010500000032L;

    // optional int32 num_non_cached_procs = 51;
    public static final long NUM_NON_CACHED_PROCS = 0x0000010500000033L;

    // optional int32 num_cached_hidden_procs = 52;
    public static final long NUM_CACHED_HIDDEN_PROCS = 0x0000010500000034L;

    // optional int32 num_service_procs = 53;
    public static final long NUM_SERVICE_PROCS = 0x0000010500000035L;

    // optional int32 new_num_service_procs = 54;
    public static final long NEW_NUM_SERVICE_PROCS = 0x0000010500000036L;

    // optional bool allow_lower_mem_level = 55;
    public static final long ALLOW_LOWER_MEM_LEVEL = 0x0000010800000037L;

    // optional int32 last_memory_level = 56;
    public static final long LAST_MEMORY_LEVEL = 0x0000010500000038L;

    // optional int32 last_num_processes = 57;
    public static final long LAST_NUM_PROCESSES = 0x0000010500000039L;

    // optional .android.util.Duration last_idle_time = 58;
    public static final long LAST_IDLE_TIME = 0x0000010b0000003aL;

    // optional int64 low_ram_since_last_idle_ms = 59;
    public static final long LOW_RAM_SINCE_LAST_IDLE_MS = 0x000001030000003bL;

}

