// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/server/activitymanagerservice.proto

package com.android.server.am;

/** @hide */
// message ActivityRecordProto
public final class ActivityRecordProto {

    // optional .com.android.server.wm.ConfigurationContainerProto configuration_container = 1;
    public static final long CONFIGURATION_CONTAINER = 0x0000010b00000001L;

    // optional .com.android.server.wm.IdentifierProto identifier = 2;
    public static final long IDENTIFIER = 0x0000010b00000002L;

    // optional string state = 3;
    public static final long STATE = 0x0000010900000003L;

    // optional bool visible = 4;
    public static final long VISIBLE = 0x0000010800000004L;

    // optional bool front_of_task = 5;
    public static final long FRONT_OF_TASK = 0x0000010800000005L;

    // optional int32 proc_id = 6;
    public static final long PROC_ID = 0x0000010500000006L;

    // optional bool translucent = 7;
    public static final long TRANSLUCENT = 0x0000010800000007L;

}

