// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/server/activitymanagerservice.proto

package com.android.server.am;

/** @hide */
// message ActivityManagerServiceDumpActivitiesProto
public final class ActivityManagerServiceDumpActivitiesProto {

    // optional .com.android.server.am.ActivityStackSupervisorProto activity_stack_supervisor = 1;
    public static final long ACTIVITY_STACK_SUPERVISOR = 0x0000010b00000001L;

}

