// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/server/activitymanagerservice.proto

package com.android.server.am;

/** @hide */
// message ReceiverListProto
public final class ReceiverListProto {

    // optional .com.android.server.am.ProcessRecordProto app = 1;
    public static final long APP = 0x0000010b00000001L;

    // optional int32 pid = 2;
    public static final long PID = 0x0000010500000002L;

    // optional int32 uid = 3;
    public static final long UID = 0x0000010500000003L;

    // optional int32 user = 4;
    public static final long USER = 0x0000010500000004L;

    // optional .com.android.server.am.BroadcastRecordProto current = 5;
    public static final long CURRENT = 0x0000010b00000005L;

    // optional bool linked_to_death = 6;
    public static final long LINKED_TO_DEATH = 0x0000010800000006L;

    // repeated .com.android.server.am.BroadcastFilterProto filters = 7;
    public static final long FILTERS = 0x0000020b00000007L;

    // optional string hex_hash = 8;
    public static final long HEX_HASH = 0x0000010900000008L;

}

