// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/content/configuration.proto

package android.content;

/** @hide */
// message DeviceConfigurationProto
public final class DeviceConfigurationProto {

    // optional uint32 stable_screen_width_px = 1;
    public static final long STABLE_SCREEN_WIDTH_PX = 0x0000010d00000001L;

    // optional uint32 stable_screen_height_px = 2;
    public static final long STABLE_SCREEN_HEIGHT_PX = 0x0000010d00000002L;

    // optional uint32 stable_density_dpi = 3;
    public static final long STABLE_DENSITY_DPI = 0x0000010d00000003L;

    // optional uint64 total_ram = 4;
    public static final long TOTAL_RAM = 0x0000010400000004L;

    // optional bool low_ram = 5;
    public static final long LOW_RAM = 0x0000010800000005L;

    // optional uint32 max_cores = 6;
    public static final long MAX_CORES = 0x0000010d00000006L;

    // optional bool has_secure_screen_lock = 7;
    public static final long HAS_SECURE_SCREEN_LOCK = 0x0000010800000007L;

    // optional uint32 opengl_version = 8;
    public static final long OPENGL_VERSION = 0x0000010d00000008L;

    // repeated string opengl_extensions = 9;
    public static final long OPENGL_EXTENSIONS = 0x0000020900000009L;

    // repeated string shared_libraries = 10;
    public static final long SHARED_LIBRARIES = 0x000002090000000aL;

    // repeated string features = 11;
    public static final long FEATURES = 0x000002090000000bL;

    // repeated string cpu_architectures = 12;
    public static final long CPU_ARCHITECTURES = 0x000002090000000cL;

}

