// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/content/intent.proto

package android.content;

/** @hide */
// message IntentFilterProto
public final class IntentFilterProto {

    // repeated string actions = 1;
    public static final long ACTIONS = 0x0000020900000001L;

    // repeated string categories = 2;
    public static final long CATEGORIES = 0x0000020900000002L;

    // repeated string data_schemes = 3;
    public static final long DATA_SCHEMES = 0x0000020900000003L;

    // repeated .android.os.PatternMatcherProto data_scheme_specs = 4;
    public static final long DATA_SCHEME_SPECS = 0x0000020b00000004L;

    // repeated .android.content.AuthorityEntryProto data_authorities = 5;
    public static final long DATA_AUTHORITIES = 0x0000020b00000005L;

    // repeated .android.os.PatternMatcherProto data_paths = 6;
    public static final long DATA_PATHS = 0x0000020b00000006L;

    // repeated string data_types = 7;
    public static final long DATA_TYPES = 0x0000020900000007L;

    // optional int32 priority = 8;
    public static final long PRIORITY = 0x0000010500000008L;

    // optional bool has_partial_types = 9;
    public static final long HAS_PARTIAL_TYPES = 0x0000010800000009L;

    // optional bool get_auto_verify = 10;
    public static final long GET_AUTO_VERIFY = 0x000001080000000aL;

}

