// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/service/usb.proto

package android.service.usb;

/** @hide */
// message UsbConnectionRecordProto
public final class UsbConnectionRecordProto {

    // optional string device_address = 1;
    public static final long DEVICE_ADDRESS = 0x0000010900000001L;

    // optional .android.service.UsbConnectionRecordMode mode = 2;
    public static final long MODE = 0x0000010e00000002L;

    // optional int64 timestamp = 3;
    public static final long TIMESTAMP = 0x0000010300000003L;

    // optional int32 manufacturer = 4;
    public static final long MANUFACTURER = 0x0000010500000004L;

    // optional int32 product = 5;
    public static final long PRODUCT = 0x0000010500000005L;

    // optional .android.service.usb.UsbIsHeadsetProto is_headset = 6;
    public static final long IS_HEADSET = 0x0000010b00000006L;

}

