// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/service/usb.proto

package android.service.usb;

/** @hide */
// message UsbProfileGroupSettingsManagerProto
public final class UsbProfileGroupSettingsManagerProto {

    // optional int32 parent_user_id = 1;
    public static final long PARENT_USER_ID = 0x0000010500000001L;

    // repeated .android.service.usb.UsbSettingsDevicePreferenceProto device_preferences = 2;
    public static final long DEVICE_PREFERENCES = 0x0000020b00000002L;

    // repeated .android.service.usb.UsbSettingsAccessoryPreferenceProto accessory_preferences = 3;
    public static final long ACCESSORY_PREFERENCES = 0x0000020b00000003L;

}

