// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/service/usb.proto

package android.service.usb;

/** @hide */
// message UsbSettingsManagerProto
public final class UsbSettingsManagerProto {

    // repeated .android.service.usb.UsbUserSettingsManagerProto user_settings = 1;
    public static final long USER_SETTINGS = 0x0000020b00000001L;

    // repeated .android.service.usb.UsbProfileGroupSettingsManagerProto profile_group_settings = 2;
    public static final long PROFILE_GROUP_SETTINGS = 0x0000020b00000002L;

}

