// Generated by protoc-gen-javastream. DO NOT MODIFY.
// source: frameworks/base/core/proto/android/service/usb.proto

package android.service.usb;

/** @hide */
// message UsbSettingsAccessoryPermissionProto
public final class UsbSettingsAccessoryPermissionProto {

    // optional string accessory_description = 1;
    public static final long ACCESSORY_DESCRIPTION = 0x0000010900000001L;

    // repeated int32 uids = 2;
    public static final long UIDS = 0x0000020500000002L;

}

